### ISSUE TITLE
Videos doesn't start since the last update

### ISSUE THREAD

**Issue by kireerik** [feross/webtorrent-desktop#1000]
Videos doesn't start since the [latest release](https://github.com/feross/webtorrent-desktop/releases/tag/v0.17.0) using VLC on 64bit Windows 10.

The [previous release](https://github.com/feross/webtorrent-desktop/releases/tag/v0.16.0) works fine. Unfortunately it automatically updates it self randomly and there is no option on the user interface to turn off auto updates. So this combination is really frustrating.

**Comment by mathiasvr** [comment]
Sorry about that, this has been fixed #985 and will be released in next version!

**Comment by feross** [comment]
@mathiasvr Yep, good idea!

@kireerik Sorry about this. The bug is already fixed, so we'll release a new version later tonight.

**Comment by kireerik** [comment]
I am sorry for creating a duplicated issue.

Otherwise I think an on-off switch for the silent automatic updates would be great to have under the preferences menu.

**Comment by dcposch** [comment]
@kireerik Chrome doesn't have an "off" switch for automatic updates.

The fewer buttons, the better.

If you really want a specific version with no auto updater, you can use the portable ZIP.

**Comment by kireerik** [comment]
I see, and I agree with you.

I think it would be also great if a video doesn't starts in WebTorrent (for example because of unsupported audio), than it would automatically start using the external player (for example VLC) without asking it. So you can instantly get rid off two unnecessary additional buttons in my opinion. What do you think? Do you already have an issue for this?

**Comment by feross** [comment]
> I think it would be also great if a video doesn't starts in WebTorrent (for example because of unsupported audio), than it would automatically start using the external player (for example VLC) without asking it.

You can go to Preferences and tell WebTorrent to always use VLC to open media files. Have you tried that?

**Comment by kireerik** [comment]
Yes of course, and that works fine, but I would like to use WebTorrent player if possible and if not than using external player (which is VLC in my case).

**Comment by feross** [comment]
Hm, I understand where you're coming from. But I think it would be confusing if some videos opened in WebTorrent and others in VLC with no explanation. The real solution is to make WebTorrent play 99% of videos without needing an external player. That solution will come soon, I hope.

**Comment by kireerik** [comment]
Yes, I mostly agree with you. What about to add an option to disable the promt dialog in preferences menu? So adding something like this, if "Play torrent media files using WebTorrent" option is active:
> Play torrent media files using external player immediately (without error prompt) if WebTorrent cannot play them.

Or a shorter version like this:
> Start external player immediately if WebTorrent cannot play the media file.

**Comment by feross** [comment]
We try to implement only the most important features that a torrent app needs, and to make those features as good as they can possibly be. This focus on only the most important features prevents the app from getting overloaded with knobs and dials that may only benefit a small percentage of users.

Instead of adding another preference, we'll just focus on getting WebTorrent to play most videos, so we don't ever need to send users to VLC. That's what I think is the right solution. Hope you understand.

**Comment by feross** [comment]
Version v0.17.1 is released which should fix your issue.
