### ISSUE TITLE
VLC doesn't open torrent movies

### ISSUE THREAD

**Issue by FUNNO** [feross/webtorrent-desktop#1006]
WebTorrent Desktop Version : 0.17.0 

operating system and version: Mac OS Sierra

I used to open torrent movies that are downloading in VLC just by clicking the red play button
now nothing opens when i click play  ( now it is white in 0.17.0  ) although i am sure that VLC is the chosen program to open torrent movies in settings..

Please help .. thanks

**Comment by feross** [comment]
Sorry that this stopped working for you. This was fixed in v0.17.1. See the changelog: https://github.com/feross/webtorrent-desktop/releases/tag/v0.17.1

You can open the app, wait 5 minutes, and then restart the app. This will get you on the latest version.
