### ISSUE TITLE
0.17.1 still broken on mac

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1007]
Fans spinning hard, the whole system is extremely slow. I see the interface but after 2 minutes it's slow to respond.

I am on a Macbook Pro 2015 with SSD disks.

I have about 10 movies 20gb average.

**Comment by ethaniel** [comment]
Falling back to 0.10.0. It's a little slow on start, but works better after a minute or so.

**Comment by feross** [comment]
Sorry to hear about this. Let's track this in your original issue: https://github.com/feross/webtorrent-desktop/issues/1001
