### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by smolleyes** [feross/webtorrent-desktop#1022]
Hi feross

good work on this, very clean :)

just three idears

1/ have right click to poste http link or drag n drop of .torrent links not only magnets
2/ and think this is one is a real problem ... :)
exemple:

i start a torrent, the player start then tell me "video or audio codec not supported", ok but now i have a chromecast/upnp/airplay player and want to send the file on one of them

i can t ! if i m right there s no global settings and in your popup i only have the choice to open an external player or cancel ( then it return to homepage)

think you can simply add a select in the audio/video popup with the detected devices with a label like 'send to network player'

cancel | open with external player | open with network player

3/ a transcoder thru ffmpeg to play any codecs in the app player :)

just an idear :)...

thanks

**Comment by feross** [comment]
Thanks for the positive feedback! In the future, please open separate issues for each suggestion. We'll take your feedback into account.
