### ISSUE TITLE
Pause All button

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#1027]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.1
**What operating system and version?**
Mac ,Linux ,Windows
**What did you do?**
try to pause all the torrents 
**What did you expect to happen?**
Pause all button 
**What actually happened?**
Button is absent

Can we add pause all button ? It will really help the users. 

thankyou!

**Comment by feross** [comment]
I'm fine adding a new "Transfers" menu that has:

- Pause All
- Resume All

Later we can put the speed limit stuff in there too.
