### ISSUE TITLE
Publish a PPA

### ISSUE THREAD

**Issue by peteruithoven** [feross/webtorrent-desktop#1028]
I've seen some related issues (https://github.com/feross/webtorrent-desktop/issues/629, https://github.com/feross/webtorrent-desktop/issues/190) but nothing to track publishing to a ppa?

**Comment by feross** [comment]
Yeah, would love to do this so Debian/Ubuntu users get automatic updates.

**Comment by larfadin** [comment]
What about a snap package ? It will auto update and work on more distrib than a ppa ?

http://snapcraft.io/

**Comment by peteruithoven** [comment]
@larfadin that's a much better idea! I'll open a new issue.

**Comment by peteruithoven** [comment]
New issue: https://github.com/feross/webtorrent-desktop/issues/1071

**Comment by jasmines** [comment]
Snap is not a good choice for me.
Vote for a ppa!
