### ISSUE TITLE
Error: Unexpected response to PTTH/1.0 Upgrade request

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#1032]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** Mac, Windows

From our telemetry error logs, we picked up this error. It occurred 10 times today.

```
Processes: window, platforms: darwin win32, versions: 0.16.0 0.17.1 0.17.2
Error: Unexpected response to PTTH/1.0 Upgrade request
    at .../node_modules/reverse-http/index.js:50:32
    at .../node_modules/consume-http-header/index.js:12:5
    at done (.../node_modules/consume-until/index.js:52:5)
    at Socket.consume (.../node_modules/consume-until/index.js:33:7)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
```

**Comment by ncortines** [comment]
seems to be related to **airplay** module..

Got the same error while trying to use it as a standalone from the command line:

> $ airplayer totally-legal-movie.mkv 
> (node:32405) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Unexpected response to PTTH/1.0 Upgrade request
>     at /usr/local/lib/node_modules/airplayer/node_modules/reverse-http/index.js:50:32
>     at /usr/local/lib/node_modules/airplayer/node_modules/consume-http-header/index.js:12:5
>     at done (/usr/local/lib/node_modules/airplayer/node_modules/consume-until/index.js:52:5)
>     at Socket.consume (/usr/local/lib/node_modules/airplayer/node_modules/consume-until/index.js:33:7)
>     at Socket.g (events.js:291:16)
>     at emitNone (events.js:86:13)
>     at Socket.emit (events.js:185:7)
>     at emitReadable_ (_stream_readable.js:432:10)
>     at emitReadable (_stream_readable.js:426:7)
>     at readableAddChunk (_stream_readable.js:187:13)

**Comment by ncortines** [comment]
Opened an issue https://github.com/watson/airplayer/issues/3

**Comment by feross** [comment]
Closing in favor of https://github.com/watson/airplayer/issues/3
