### ISSUE TITLE
WT ignoring my request only to download only 1 file

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1047]
I've opened a torrent and deselected all files in it except the first one, expecting it to download only that one. For some reason it keeps downloading something even though my file has already downloaded. See screenshot.

You can see that my file is 951 MB and it downloaded 1.7 GB.

![image](https://cloud.githubusercontent.com/assets/941973/19413212/f8a261aa-9337-11e6-8775-a63cef5c6c1f.png)

I assume that that bug has something to do with me adding the magnet link as a torrent and it been given a wrong status. At first, all the files were marked for download and I deselect all except the first one within first 5 seconds.

**Comment by ethaniel** [comment]
Now I am experiencing a new bug.
When I click play on the second file, it starts downloading and the player opens asking me to switch to VLC. When I click "cancel" I am returned to the main screen and the download slowly stops in 5 seconds.

This is what I see when I clicked "cancel". Note the peers available.
![image](https://cloud.githubusercontent.com/assets/941973/19413717/c03457ec-9346-11e6-8fe8-74b5af10e583.png)

**Comment by ethaniel** [comment]
That's weird. I just started WebTorrent. While it was rehashing my latest torrent, I asked it to download another file. After a minute or so it told me that the download is complete, the torrent switch to "seeding", however the file was downloaded only partially.

![image](https://cloud.githubusercontent.com/assets/941973/19420113/c9d5b20a-93f5-11e6-806c-46e1292c8d72.png)

**Comment by ethaniel** [comment]
This evening I opened WebTorrent again and the partially downloaded torrent started rehashing.
A few seconds later (while it was still rehashing) I added s01e11 and s01e12 to the download queue. 

s01e11 was downloaded. s01e12 wasn't touched at all.

![image](https://cloud.githubusercontent.com/assets/941973/19488437/f28788c6-9577-11e6-96a9-cd4b5a732b13.png)

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
