### ISSUE TITLE
Feature Request: Tracker Checker and Ratio

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent-desktop#1049]
So I'm working on building a website and I want to make it basically a private tracker that runs on webtorrent and yes I do know that WT always requires DHT but I mean more in the sense of ratios and being able to organize all my torrents. So how difficult would it be or how long would it take before you can add 1: ratios to the desktop application. and 2: add a menu that shows the response and peer count of each tracker, ie

wss://webtorrent.io:80 - announce ok - 14 Seeders 7 Leechers 

Or does the WT tracker machine not operate with normal tracker announce requests and responses? 

Also to avoid making another issue, how possible or efficient would it be to make a seedbox style version of WT Desktop, so instead of being able to stream it operates and appears similar to a regular BitTorrent client and can manage trackers and record ratio and so forth. Cause the CLi version can be cumbersome when it comes to seeding and having to make a new window for every torrent added.

**Comment by feross** [comment]
It's really a lot easier to track progress on each individual issue you mentioned if you make an issue for each topic.

> how long would it take before you can add ratios to the desktop application

Do you mean per-torrent ratios? Or a global ratio? Honestly, this doesn't seem useful for 90% of users, so it's not a top priority. Especially if it complicates the UI. But there may be a subtle way to show it. 

> add a menu that shows the response and peer count of each tracker, ie

This seems even more specific. I don't think we'll add this.

> Or does the WT tracker machine not operate with normal tracker announce requests and responses?

There are normal tracker announces and responses. The underlying webtorrent library does expose this information: https://github.com/feross/webtorrent

> it operates and appears similar to a regular BitTorrent client and can manage trackers and record ratio and so forth

I saw another project trying to build a more traditional torrent client UI using webtorrent. https://github.com/FaCuZ/torrentmedia Not sure what the status or progress on that is. Maybe you can help that effort out?

Honestly, though, the underlying webtorrent library does expose the information and functionality you're looking for, so I would consider writing some code to get exactly what you want.

**Comment by Edward-Stryfe** [comment]
Ok thank you for pointing me out to that project. The reason I was hoping for these features, was that I wanted to be able to test the connection of my tracker and DNS services once I get a domain on the IP. I was hoping that with that I'd be able to setup my tracker and discern my uptime. Cause using the NodeJSCli to run the tracker while that is all fine and easy, the problem is that I cannot seem to find a method that confirms the WSS:// tracker is functioning properly since the Desktop version and the browser versions don't display announces. Come to think of it since you said the announces are similar would it be able write a quick segment of JS up so that it'll display the announces in the browser for all the trackers?

That's the only concern I have with the tracker announcing. Because as of now half the trackers could be dead and no one knows cause how could they. As well as the tracker i'm setting up could be improperly configured while I go sharing it anyway. Maybe if that is possible adding it to the /docs page of the website.

But the ratio was less important and was hoping just to have it added in the little corner to the right so it's out of the way but visible. It seems like it would take longer to build a global ratio.

**Comment by feross** [comment]
You can check that your wss tracker is working by enabling wss only and then visiting it's `/stats` page. For example, this is what it looks like in practice on a community-run tracker: https://tracker.btorrent.xyz/stats
