### ISSUE TITLE
Sorry we can't play that file, Audio codec unsupported.

### ISSUE THREAD

**Issue by riaandb7** [feross/webtorrent-desktop#1051]
Version 0.17.2 (0.97.2) (64-bit)

Windows 10 Pro 64bit

Tried to seed a video file/create torrent

Expected audio to be supported, normal MP3 audio on video file

"Sorry we can't play that file, Audio codec unsupported."

Which audio codec should I use?

![image](https://cloud.githubusercontent.com/assets/8146772/19463623/e9b32476-94f5-11e6-8eff-15a7539c51d2.png)

**Comment by feross** [comment]
Can you try opening the same file in Chrome? Let me know if it plays there.

That will help us determine if it's an issue with Chrome not supporting the codec combination you're using, or if it's a bug in how we're detecting unsupported codecs.

**Comment by MacgyverJohnson** [comment]
Hi there @feross 
This is a amazinggg!! software. Working exactly as it says.
I have experienced the aforementioned problem when playing HEVC x265(720p/1080p) videos....but 1080p x264 works well.....So can you add LAV filters for playing HEVC x265 videos? X265 is really popular nowadays...any option to use it if K-lite codec pack which contains Madvr and Lav filters? External codecs would be a really awesome thing to have
BTW when played with external player vlc/potplayer it is working/streaming up nicely
Thanks

**Comment by jo2dan23** [comment]
does this to me also. have had it happen multiple times.

**Comment by orchestor** [comment]
Same problems here

**Comment by RaphyRaph** [comment]
Happens all the time.

**Comment by feross** [comment]
When this happens to you, one thing that would help us out is (once the download is fully complete),  try to open the file in Chrome. If Chrome can play the file but WebTorrent can't, then we might have a bug.

But, if Chrome also can't play the file, then unfortunately that's currently the expected behavior since we can only play what Chrome can play.

**Comment by orchestor** [comment]
magnet:?xt=urn:btih:a1729ee981db056cbb3b8756a65d473aa1ffea03&dn=%5B+www.CpasBien.cm+%5D+Criminal.2016.FRENCH.BRRIP.XviD-ShowFr.avi&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
