### ISSUE TITLE
Sure you want to delete?

### ISSUE THREAD

**Issue by jimmywarting** [feross/webtorrent-desktop#1057]
**What version of WebTorrent Desktop?**
Version 0.17.2 (0.97.2)

**What operating system and version?**
Mac OS

**What did you do?**
Right click -> Remove Data Files

**What did you expect to happen?**
The "Remove data" button should use the autofocus attribute

**What actually happened?**
The "are you sure you want to delete this" is a bit annoying. I'm 99.9999% sure  sure about my choice so i just want to hit space bar with my other hand where the thumb is laying perfectly on spacebar most of the time just waiting to be pressed down.

Even better would be a "Don't ask again" option
![skarmavbild 2016-10-24 kl 20 58 53](https://cloud.githubusercontent.com/assets/1148376/19659660/1d82380a-9a2d-11e6-8c01-9c1bc2299202.png)

**Comment by mathiasvr** [comment]
I think this makes sense, so made a PR #1058.
For the 'Don't ask again' option etc. please follow discussion at #970.

**Comment by Flet** [comment]
Thanks @mathiasvr!
