### ISSUE TITLE
Something is terribly broken with multi-file torrents.

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1059]
Apart from the bugs I've listed previously, one of my torrent is shown as downloading at 236 MB/s while being at 100%. This happened when I just opened WT and it starting rehashing a incomplete torrent.

![image](https://cloud.githubusercontent.com/assets/941973/19739156/8bd3f460-9bc2-11e6-8421-e6590e1e0df5.png)

**Comment by alexisvincent** [comment]
Can second this. Files mark as 100% when they definitely aren't.

**Comment by feross** [comment]
@ethaniel Please don't post about copyright infringement, we can't help if it's clear that you're using WebTorrent for infringement.
