### ISSUE TITLE
WebTorrent-Desktop Cannot Show SoftSub :(

### ISSUE THREAD

**Issue by MarcosxSenpai** [feross/webtorrent-desktop#1061]
**What version of WebTorrent Desktop?**
Version 0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
Windows 10 Home (Versión 1607)

**What did you do?**
I tried to play a movie with softsub

**What did you expect to happen?**
Play the movie with softsub

**What actually happened?**
The movie play without subtitles

**Comment by demoneaux** [comment]
Closing as duplicate of #526.
