### ISSUE TITLE
Creating torrent from folder which contains subfolders

### ISSUE THREAD

**Issue by Zippersk** [feross/webtorrent-desktop#1063]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
win 10

**What did you do?**
I create torrent from folder1 which has this structure:

```
folder1─┬─folder2───bbb.txt
        └──aaa.txt
```

**What did you expect to happen?**
I expected that the torrent files will looks:
```
folder1/aaa.txt
folder1/folder2/bbb.txt
```

**What actually happened?**
Everything from subfolders was copied to folder1
torrent structure looks like this:
```
folder1/aaa.txt
folder1/bbb.txt
```
Why torrents can't add subfolder?

**Comment by mathiasvr** [comment]
This is a known webtorrent issue https://github.com/feross/webtorrent/issues/845.

**Comment by feross** [comment]
Closing as duplicate
