### ISSUE TITLE
AC-3 audio support + Chromecast subtitles

### ISSUE THREAD

**Issue by alexandrepsc** [feross/webtorrent-desktop#1066]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2)
**What operating system and version?**
Windows10
**What did you expect to happen?**
Decode AC-3 audio and show subtitles on TV
**What actually happened?**
Don't decode AC-3 or display subtitles

I really love WebTorrent but it would be great if it could decode AC-3 audio, because most movies use it, and it would be great if subtitles could appear on TV

Thanks

**Comment by jimmywarting** [comment]
AC3 support can be tracked here: #350

**Comment by jonathanobino** [comment]
Subtitle support for chrome cast would be awesome!

**Comment by feross** [comment]
Chromecast subtitle support can be tracked here: https://github.com/feross/webtorrent-desktop/issues/530

Closing as duplicate.
