### ISSUE TITLE
cant play this file

### ISSUE THREAD

**Issue by Ghost0s** [feross/webtorrent-desktop#1072]
*Version 0.17.2 (0.97.2) (64-bit)

Windows 7 x64

past a magnet links for movie 
1-magnet:?xt=urn:btih:47b626e0d7e7e8b37cf4f47cd460c4cc2d4b8831&dn=Dog.Eat.Dog.2016.HDRip.XViD-ETRG&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fzer0day.to%3A1337%2Fannounce&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

2-magnet:?xt=urn:btih:a911009f632bfb8e8ecbc8ea19c91fa06c1fb5f2&dn=Sully.2016.HC.HDRip.XViD.AC3-ETRG&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fzer0day.to%3A1337%2Fannounce&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

i expect watching 

Error saying it cannot play it

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
