### ISSUE TITLE
Ubuntu - Video Seeking - Control Issue

### ISSUE THREAD

**Issue by benwinding** [feross/webtorrent-desktop#1073]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
Ubuntu 16.10

**What did you do?**
Just seeking while streaming a torrent file

**What actually happened?**
The seeking control drags out like the following picture
![screenshot from 2016-11-13 20-14-57](https://cloud.githubusercontent.com/assets/11782590/20244808/2a20ddca-a9df-11e6-9fd0-35cde0ce0796.png)

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
