### ISSUE TITLE
[Request] add button better using

### ISSUE THREAD

**Issue by Gelo3D** [feross/webtorrent-desktop#1075]
[Device][Test Platform]
Laptop Toshiba L50-B-125
PROCESSOR : INTEL i5-4200U 2x1,6 - 2,3 GHz
RAM : 4GB DDR3 1,6GHz
SSD : 120 GB SATA3 M2 Micro Data MD500
HDD : 750 GB SATA3 TOSHIBA MQ01ABD075
GRAPHIC : AMD RADEON R7 M260 + 
APP VERSION : 0.17.2 (0.97.2) 64bit
![screenshot_1](https://cloud.githubusercontent.com/assets/15075411/20249892/aacbb1b0-aa03-11e6-8486-2f83902586f3.png)

Request is add to button '+' 3 options.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
