### ISSUE TITLE
Sort files in alphabetical order

### ISSUE THREAD

**Issue by Icx4Lemon** [feross/webtorrent-desktop#1076]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2 (0.97.2)
**What operating system and version?**
Windows 10 x64
**What did you do?**
I loaded a torrent with many files 
**What did you expect to happen?**
The files should have been sorted correctly
**What actually happened?**
The files were in a random order

**Comment by feross** [comment]
We used to sort file names alphabetically, but we don't do it anymore. Instead, we just show the files in the order that the torrent file lists them. It's up to the torrent file creator to put the files in a sensical order.
