### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zeke** [feross/webtorrent-desktop#1077]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.17.2

**What operating system and version?**

Yosemite

**What did you do?**

Tried to open the app.

**What did you expect to happen?**

App should start.

**What actually happened?**

Black screen. Contents of devtools:

![screen shot 2016-11-16 at 5 56 41 pm](https://cloud.githubusercontent.com/assets/2289/20373296/0a979e28-ac26-11e6-9e7f-b25e9d1e5dd2.png)

> torrent-summary.js:55 Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by feross** [comment]
This isn't good. @zeke Does this happen *every* time you open the app?

Maybe there was a bug in a schema migration and your data file isn't in good shape now? To get things working again, you can run: `rm ~/Library/Application\ Support/WebTorrent/config.json`

**Comment by zeke** [comment]
> Does this happen every time you open the app?

Yep, but removing `config.json` seems to have done the trick. Thanks!

**Comment by zeke** [comment]
..or should this issue remain open?

**Comment by feross** [comment]
I'll re-open if there are other reports like this :)
