### ISSUE TITLE
2 Fullscreen view options

### ISSUE THREAD

**Issue by Meadowcottage** [feross/webtorrent-desktop#1079]
**Version: 0.17.2 (0.97.2)**
**OS: MacOS**

**Issue:**
There are currently 2 methods of opening fullscreen, double clicking the window/using the menu item OR clicking the fullscreen window option in the top left.
Double clicking goes into fullscreen and runs fine and doesn't need to be fixed in any way. However the window fullscreen button results in fullscreen, but with a cropped view.

**Non-zoomed:**
![](https://i.imgur.com/051mvEv.png)

**Zoomed:**
![](https://i.imgur.com/khWHyPa.png)

**Comment by arinazari** [comment]
I have the same version on macOS --- I don't get a zoomed vs non-zoomed version depending on how I enter full-screen but in either case I still see the menu/navigation bars.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
