### ISSUE TITLE
Clicking on Magnet Link on Chrome or any browser doesn't work like it is in uTorrent

### ISSUE THREAD

**Issue by junaidinam** [feross/webtorrent-desktop#1081]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (64-bit)
**What operating system and version?**
Windows 10      Version	10.0.14393 Build 14393
**What did you do?**
Clicked on Magnet link
**What did you expect to happen?**
Web Torrent should opne up
**What actually happened?**
Nothing

**Comment by junaidinam** [comment]
I would like to work on it. How can i contribute?

**Comment by feross** [comment]
Have you made WebTorrent the default app in the Preferences?

<img width="417" alt="screen shot 2016-11-20 at 9 59 55 pm" src="https://cloud.githubusercontent.com/assets/121766/20467753/b4b1eb36-af6c-11e6-818b-5448e1e095e8.png">

**Comment by demoneaux** [comment]
@feross this issue still exists, as the default file/protocol handlers are not re-installed after each update. Hence, on Windows computers, they would point to the location of older versions of the app, which would be deleted. Hence, even though WebTorrent is the default, magnet and torrent links still can't be opened by default. I've created #997 to solve this, although there hasn't been much feedback.

**Comment by feross** [comment]
@demoneaux Cool, good to know
