### ISSUE TITLE
App run with main black screen.

### ISSUE THREAD

**Issue by thanhbinh8715** [feross/webtorrent-desktop#1086]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2
**What operating system and version?**
Windows 8
**What did you do?**
I've just download and try first time run project
**What did you expect to happen?**

**What actually happened?**

**Comment by thanhbinh8715** [comment]
Hi !

I've just download and try first time run project. After run comment 'npm start' then App start with main content is black. 
![electron_2016-11-28_14-20-04](https://cloud.githubusercontent.com/assets/16287392/20659391/df9fee38-b575-11e6-88c1-49c30fa01fa0.png)
Please help ! Thanks !

**Comment by FerreiraRaphael** [comment]
having the same issue

**Comment by thanhbinh8715** [comment]
@FerreiraRaphael 
hey you ! i fixed this problem. I think you have got same my problem. Please try downgrade of packages below to extract:
"react": "^15.2.1",
"react-dom": "^15.2.1",

You can check version on your machine by command : 
![cmd_2016-11-29_10-41-20](https://cloud.githubusercontent.com/assets/16287392/20695679/6bd132f4-b620-11e6-9629-0f90f220749b.png)

if don't same version with me. You need run 2 command below : 
```
npm install react@15.2.1
npm install react-dom@15.2.1
```

hope this helpful for you.

**Comment by FerreiraRaphael** [comment]
Nice man, thanks

**Comment by feross** [comment]
This issue is due to a breaking change in react@15.4.0. It can be fixed by updating the version of `react-tap-event-plugin` to 2.0.0. Fixed on master.
