### ISSUE TITLE
Downloads files from a large torrent that I didn't choose

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1089]
When I import a large torrent (a whole season from series) and quickly deselect the files that I don't need to be downloaded, WTD ignores my selection and keeps downloading the whole torrent.

For example, I need only 1 file out of 10. I import the torrent. Deselect 9 files. But WTD keeps downloading them like nothing happened.

**Comment by feross** [comment]
Duplicate of https://github.com/feross/webtorrent-desktop/issues/719
