### ISSUE TITLE
The client never starts downloading

### ISSUE THREAD

**Issue by hjpotter92** [feross/webtorrent-desktop#1091]
**What version of WebTorrent Desktop?**
0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
Debian stretch (testing)

**What did you do?**
Downloaded WTD `deb` from the [website](https://webtorrent.io/desktop/). Installed and started the client and added a magnet link.

**What actually happened?**
The client just shows trying to fetch magnet information. When launching the client via terminal, the following lines are repeated over and over:

```
[3666:1204/013822:ERROR:webrtcsession.cc(1226)] ConnectDataChannel called when data_channel_ is NULL.
```

**Comment by feross** [comment]
Maybe the magnet link you added has no peers? Maybe you're on a network that blocks BitTorrent traffic?

If you try another magnet link or try again from another network, does it start working?

That console output is actually harmless. See this issue: https://github.com/feross/webtorrent-desktop/issues/85

**Comment by feross** [comment]
Also, if you see this happen again, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by hjpotter92** [comment]
That's strange. The downloads are now working normally after rebooting my system. There might be some configuration issues while installing?

I'll close the issue for now. Will try to reproduce this on another system. I'd surely provide the logs as mentioned above.

Thanks

**Comment by feross** [comment]
@hjpotter92 Thanks!
