### ISSUE TITLE
Option to ignore files smaller then x Bytes

### ISSUE THREAD

**Issue by jimmywarting** [feross/webtorrent-desktop#1092]
frequently get a bunch of small files I don't want/need. An option to ignore/hide those would be highly appreciated

**Comment by feross** [comment]
Thanks for the feature request!

WebTorrent Desktop values simplicity and beautiful design, which sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs, and to make those features as good as they can possibly be. This focus on only the most important features prevents the app from getting overloaded with knobs and dials that may only benefit a small percentage of users.

For that reason, I don't think it makes sense to implement this feature.
