### ISSUE TITLE
Torrent file download not working

### ISSUE THREAD

**Issue by sonchulmin** [feross/webtorrent-desktop#1098]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (32-bit)

**What operating system and version?**
Ubuntu 14.02

**What did you do?**
I tried to download 
magnet:?xt=urn:btih:46c5af9e2075d9af06f280b55b65cf9b44eb9fe7&dn=cs231n-CNNs&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

**What did you expect to happen?**
Download 10GB of content.

**What actually happened?**
Download stops at 8.2MB and no more progress.
By the way, I tried libtorrent client_test and uTorrent. Both work fine.

**Comment by feross** [comment]
WebTorrent currently doesn't have a very good reconnect behavior if you lose your Internet connection. When that happens, you can pause then start the torrent using the checkbox.
