### ISSUE TITLE
Torrents not loading.

### ISSUE THREAD

**Issue by rosweed** [feross/webtorrent-desktop#1100]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (64-bit)
**What operating system and version?**
Windows 10 Pro
**What did you do?**
I tried to download torrents.
**What did you expect to happen?**
I expected it to work as it has in past.
**What actually happened?**
The loading torrent message just sits there, and says downloading torrent info. I have just switched to a new computer, and perhaps that is the problem.

**Comment by feross** [comment]
Does this happen for all torrents or just for a single torrent?

**Comment by rosweed** [comment]
Hello. I discovered that Webtorrent does not work if I am using a VPN.

**Comment by feross** [comment]
This sounds like an issue with your VPN configuration. It has worked fine when I've tested it with a VPN. Other users also haven't reported issues.

What type of VPN are you using? Which provider? What protocol is in use? What OS and version?

**Comment by rosweed** [comment]
Hi. I use Tunnelbear. I don't know the protocol. I am using Windows 10 pro.

**Comment by feross** [comment]
I don't think there's anything we can do here. We're not doing anything that ought to prevent a VPN from working with the app. Absent further information, there is nothing we can fix here.
