### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by vincentfkc** [feross/webtorrent-desktop#1103]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu) 0.17.2

**What operating system and version?** win10 64bits

**What did you do?** build

**What did you expect to happen?** build

**What actually happened?** build

C:\webtorrent-desktop-0.17.2>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Invalid name: "WebTorrent, LLC"
npm WARN webtorrent-desktop-0.17.2 No description
npm WARN webtorrent-desktop-0.17.2 No repository field.
npm WARN webtorrent-desktop-0.17.2 No README data
npm WARN webtorrent-desktop-0.17.2 No license field.

**Comment by feross** [comment]
These are all warnings and can be safely ignored. Though it's unclear to me why your copy of the `package.json` is missing all the normal fields like description, repository, etc.
