### ISSUE TITLE
Feature RSS feed initiated torrenting

### ISSUE THREAD

**Issue by rayvahey** [feross/webtorrent-desktop#1104]
Hi,

I would like to add a feature that automatically initiates torrenting from user specified feed sources. The desktop app could make a periodic polling check to each of those sources at intervals specified by the user. (except for a sensible minimum) 
Seeding defaults would be set to the installation default and overridable in the configuration by the user.

Is anyone currently working/designing similar?

A typical use case for this is someone who follows certain video channels and wants to have the fresh content available and/or is a willing contributor to seeding. 

Cheers
Ray

**Comment by feross** [comment]
This is an excellent idea and one that the team supports. See the issue here: #856

**Comment by Openmedianetwork** [comment]
I would love this feture as it would make pushing out 1000's of CC video we have on peertube when it goes BETA soon. A link to our thinking https://github.com/Openmedianetwork/visionOntv/wiki/Seedbox
