### ISSUE TITLE
Incognito Torents

### ISSUE THREAD

**Issue by bofinbabu** [feross/webtorrent-desktop#1105]
I really enjoy WebTorrent-Desktop app's built-in media player.
As a regular user, I'd love if we can add a feature like incognito media torrents, where torrent + data will be deleted right after one finish watching it. Additional features to protect privacy can also be added in this mode.

**Comment by feross** [comment]
This is an interesting idea, but I don't think it's very easy to implement. The way we show torrents right now is in the main list view. We can't let the user select which file to stream without adding the torrent to the main list view.

So, while it sounds neat to have an incognito mode that deletes the torrent when the player closes, it wouldn't work with our current UI paradigm.

If we had ideas for other unique privacy features, I think we could justify making a whole Incognito Window (Command+Shift+N) implementation where torrents in that list behave differently.
