### ISSUE TITLE
Seeding gets unticked after video playback

### ISSUE THREAD

**Issue by arinazari** [feross/webtorrent-desktop#1110]
**What version of WebTorrent Desktop?** Version 0.17.2

**What operating system and version?** macOS Sierra 10.12.2

**What did you do?** Untick "Seeding" (this successfully stops seeding); Enter playback for torrent (*.mp4 video); Press back button.

**What did you expect to happen?** "Seeding" to remain unticked. 

**What actually happened?** "Seeding" is back to being ticked. It's not clear to me if the torrent is actually seeding or this is just the UX.

**Comment by feross** [comment]
Seeding starts up again since we're using the torrent library to support streaming right now. So it must be added. We talked about removing this limitation before, but I can't find the issue now.

**Comment by desci** [comment]
@feross i think it's #1023

**Comment by feross** [comment]
Thanks, @desci. Closing this as duplicate. :)
