### ISSUE TITLE
Fullscreen video does not hide menu/navigation controls

### ISSUE THREAD

**Issue by arinazari** [feross/webtorrent-desktop#1111]
**What version of WebTorrent Desktop?** Version 0.17.2

**What operating system and version?** MacOS Sierra 10.12.2

**What did you do?** Enter fullscreen video playback by either double clicking the screen or pressing the fullscreen button.

**What did you expect to happen?** For the video playback control bar @ bottom and the navigation bar @ the top to autohide.

**What actually happened?** They remain visible throughout full-screen playback.

**Comment by feross** [comment]
If your mouse is on top of the controls, then they will not auto-hide. You need to leave the mouse on the video itself.
