### ISSUE TITLE
Cant play Flac Audio

### ISSUE THREAD

**Issue by sneda** [feross/webtorrent-desktop#1124]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Ubuntu 64   16.04
**What did you do?**
trying to stream audio format flac 
**What did you expect to happen?**
play flac audio, i have the last version of firefox (51.0.1 64 bits)  flac compatible
**What actually happened?**
download start, but i cant play (play symbol doesnt appear), with others audio format it work normally.

Thanks for your help

**Comment by feross** [comment]
Thanks for the report. This will be fixed in the next version of WebTorrent Desktop. See: https://github.com/feross/webtorrent-desktop/issues/1127
