### ISSUE TITLE
MPC-HC can't render video

### ISSUE THREAD

**Issue by mikhaelkh** [feross/webtorrent-desktop#1126]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
latest (0.18.0)
**What operating system and version?**
Windows 10 x64
**What did you do?**
Select external player to [MPC-HC](https://mpc-hc.org/) and disable "Play torrent media files using WebTorrent", then start "Sintel"

**What did you expect to happen?**
MPC-HC playing video nornally

**What actually happened?**
MPC-HC failed to play video even when it completely downloaded.

**Comment by feross** [comment]
Does mpc-hc support playing from an http url? Can you try playing the following url in the player? Most players support doing this:

```
vlc https://webtorrent.io/torrents/sintel-1024-surround.mp4
```

If that doesn't work, then WebTorrent streaming won't work with mpc-hc.

**Comment by mikhaelkh** [comment]
Opening `https://webtorrent.io/torrents/sintel-1024-surround.mp4` in MPC-HC works fine.
The problem is with some samples: Big Buck Bunny works fine, Cosmos Laundromat and Sintel - won't start, 
Tears of Steel - incorrect length, moreover different from time to time. Even downloaded videos load a significant amount of time if load at all.
Also, [MPC-BE](https://sourceforge.net/projects/mpcbe/) works fine with all sample videos in WebTorrent Desktop, starts playing finished downloads instantly.
Maybe it's a problem with MPC-HC, in that case I urge you to file a bug in their [bugtracker](https://trac.mpc-hc.org/wiki/How_to_Report_Issues), you can provide far more inrofmation than I am.

**Comment by feross** [comment]
Why not just use VLC? I've never heard of MPC-HC. Is it widely used?

If WebTorrent Desktop works with other video players for you, then it's clearly a bug with MPC-HC. I don't want to set a precedent that we'll go and file bugs on every possible video player that doesn't work exactly right with WebTorrent. We only officially support VLC. If you want bugs in MPC-HC fixed, then I suggest that you open an issue there. Sorry, but I have limited development time and have to use it wisely.

If it's useful, you can start an http server that behaves just like the one in WebTorrent Desktop by instally Node.js and running:

```
npm install webtorrent-cli -g
webtorrent "magnet:..." --
```

From there, they can copy the http link from the resulting output.

**Comment by mikhaelkh** [comment]
1. Yes, it is very widely used. MPC-HC is the largest open source alternative to VLC. If you don’t like how much bloat VLC took on over the past few years, and if you don’t like PotPlayer’s closed source development, then this is the media player for you. The only big problem is that MPC-HC is Windows-only.
2. MPC-HC plays `https://webtorrent.io/torrents/sintel-1024-surround.mp4` just fine. The problem is with WebTorrent Desktop's way of communicating with external players.

**Comment by mikhaelkh** [comment]
Here is my ticket to MPC-HC team: https://trac.mpc-hc.org/ticket/6054

**Comment by feross** [comment]
@mikhaelkh Thanks for the info about usage of MPC-HC. I'll keep that in mind and test how it behaves on Windows from time-to-time. Also, thanks for taking the initiative and opening a ticket in their tracker.

**Comment by mikhaelkh** [comment]
It seems MPC-HC need to implement overriding source filters.
This seems to be implemented in MPC-BE and MPC-BE has no problem whatsoever.

**Comment by feross** [comment]
@mikhaelkh Sounds good, thanks for following up
