### ISSUE TITLE
Window not proper theme (dark instead of light)

### ISSUE THREAD

**Issue by Zalckos** [feross/webtorrent-desktop#1128]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.18.0

**What operating system and version?**
Linux Debian 8.7
Gnome 3.14.1

**What did you do?**
I opened the application

**What did you expect to happen?**
A light Window.

**What actually happened?**
A dark Window.

As you can see in the screenshot I'm using a light theme but WebTorrent uses a dark one.

![screenshot from 2017-02-09 16 19 56](https://cloud.githubusercontent.com/assets/7502489/22789623/ce6e8a00-eee3-11e6-8507-87e62e957ad6.png)

**Comment by feross** [comment]
WebTorrent only has a dark theme for the moment. To keep things simple, we want to have one UI theme across OS platforms. In a future version, we may consider a UI that takes into account the OS theme settings, but it's not a priority at the moment.

Also, when Chromium updates to GTK3, then we can probably match the menu bar to the rest of the UI (i.e. make it dark). 

See: https://github.com/electron/electron/issues/2927
See: https://chromium.googlesource.com/chromium/src/+/acc4214c4dece4e70fb53355d557bd45f35965d6/docs/linux_gtk_theme_integration.md#GTK3
