### ISSUE TITLE
Move "About WebTorrent" from [Transfers] to [Help] for UI consistancy ... 

### ISSUE THREAD

**Issue by aspadistra** [feross/webtorrent-desktop#1131]
Move "About WebTorrent" from [Transfers] to [Help] for UI consistency ... 

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**Version 0.18.0 (0.98.5) (64-bit)**

-- Mod this part of the UI so that the Version Text can be more easily copied. 
-- What is the browser announcement string? This is a browser after all... 

**What operating system and version?**
Win10 current version as of posting. 

**What did you do?**
Nothing, these are UI design issues.

**Comment by feross** [comment]
Thanks, this is already fixed on `master` and will be part of the next release.
