### ISSUE TITLE
Add User Tasks (Windows)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#114]
Similar to the OS X Dock issue #113, let's add a User Task menu for Windows:

![ic420539](https://cloud.githubusercontent.com/assets/121766/13633175/3d9a1166-e5a2-11e5-99a1-b3e5461eacf2.png)

API docs: http://electron.atom.io/docs/v0.36.8/tutorial/desktop-environment-integration/#user-tasks-windows

**Comment by demoneaux** [comment]
This doesn't seem easy to implement, as it requires calling an executable, instead of just running code.
