### ISSUE TITLE
Add Thumbnail Toolbar (Windows)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#115]
On Windows you can add a thumbnail toolbar with specified buttons in a taskbar layout of an application window. It provides users a way to access to a particular window’s command without restoring or activating the window.

Built-in Windows programs like Windows Media Player do this, so we should too to blend into the OS as best we can.

![ic420540](https://cloud.githubusercontent.com/assets/121766/13633206/7348852c-e5a2-11e5-85ea-7ee4f76a8410.png)

API docs: http://electron.atom.io/docs/v0.36.8/tutorial/desktop-environment-integration/#thumbnail-toolbars

**Comment by iadj** [comment]
I also believe the app should stay running by default after closing the window and display inside an application icon (bottom right for Windows, top right for OSX & Linux), so torrents can be managed (uploading/downloading) consistently while running the app on the background.

**Comment by feross** [comment]
@iadj That's another issue. Can you open a new issue for that?

**Comment by iadj** [comment]
@feross Done: https://github.com/feross/webtorrent-app/issues/150

**Comment by gediminaspetrikas** [comment]
I'm on it

**Comment by feross** [comment]
@gediminaspetrikas You're going to work on the buttons that show up in the taskbar?

**Comment by gediminaspetrikas** [comment]
Yes. I'll add play/pause buttons which switch depending on the state, so it will be only a single button, as there isn't play next/previous funcionality

**Comment by feross** [comment]
This is done now, thanks to @gediminaspetrikas!
