### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by donjajo** [feross/webtorrent-desktop#1152]
I can't open it, I can't find the version. But its the current version

> Linux jajo-pc 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux (Debian 9)

After installing, I tried executing the package.

I expected the package to launch

But i got this error 

> webtorrent-desktop: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

I have `libgconf-2-4` installed already

**Comment by feross** [comment]
Please use the issue template. We need answers to all those questions in order to help. If you want to re-open this issue with the needed information, happy to take a look.
