### ISSUE TITLE
Error after Airplay to Apple TV 4

### ISSUE THREAD

**Issue by CybermanBG** [feross/webtorrent-desktop#1157]
Error after Airplay to Apple TV 4

<img width="1280" alt="screen shot 2017-04-04 at 9 31 31 pm" src="https://cloud.githubusercontent.com/assets/26907458/24672603/0666ce26-197e-11e7-8c3c-ec1d2a87ab50.png">

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
