### ISSUE TITLE
Turn torrent into 'playlist': automatically start playing next item

### ISSUE THREAD

**Issue by iadj** [feross/webtorrent-desktop#123]
There should be a playlist & shuffle option in `webtorrent-app` so you can automatically play the next videos in the list after the current video has finished playing. Also the option to start downloads while items are playing, and a previous/next option.

**Comment by Goldob** [comment]
I've started work on the feature and will make a pull request once I have some results. The current idea is to have separate tabs for torrents and playlists in the home screen (also, all playlists are to be stored in `state.saved.playlists`).

The player would need `playlistId` and `trackId` for reference.

Files could be added individually or in mass, by torrent (e.g. Right click > Add all to playlist).

Any further thoughts/suggestions would be much appreciated.

**Comment by dcposch** [comment]
dunno about shuffle, but i agree we should at least have the ability to play thru all the files in a single torrent without stopping.

lots of audiobook torrents are a collection of sound files, one per chapter. currently, webtorrent desktop doesn't handle them well: you have to click on each chapter one at a time

the reason i'm reluctant to add shuffle support or autoplay across multiple torrents, is that i don't want to go down the road of becoming a media library. once we do that, people will want a way to reorder the torrent list, group torrents with labels or folders or playlists, etc.

i want to keep the app minimalist

**Comment by dcposch** [comment]
i like the idea in #642 : autoplay, but only within torrents, not between them

**Comment by dcposch** [comment]
@feross thoughts?

**Comment by feross** [comment]
@dcposch Agree with what you said. Autoplaying the next file in the torrent is sufficient.

**Comment by dcposch** [comment]
So to recap:
* Play in order only, no shuffle
* Play within a torrent only, not across torrents
* Play files in the order they appear in the torrent

**Comment by Goldob** [comment]
I can get back to work on #642, now that I'm back. There will probably be quite a lot refractoring, but still - most of the work is done. I will let you know about the progress soon.

**Comment by dcposch** [comment]
Done in #871, released in v0.14

Thanks @Goldob !
