### ISSUE TITLE
Audio player

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#149]
Would be great to have a way to play audio files inline, for public domain audiobooks from places like [LibriVox](https://librivox.org/).

Showing a minimalist audio waveform would be a classy touch. This library might work: http://wavesurfer-js.org/

<img width="1035" alt="screen shot 2016-03-16 at 12 03 31 am" src="https://cloud.githubusercontent.com/assets/121766/13804486/973ac3c4-eb0a-11e5-803b-96abf1e12b2e.png">

**Comment by ChrisMorrisOrg** [comment]
Very spiffy! I like it!

**Comment by iadj** [comment]
That looks fantastic! Better audio support would be amazing. This would go great in combination with playlists: https://github.com/feross/webtorrent-app/issues/123

**Comment by dcposch** [comment]
@feross is this done, or do you still want the waveforrm?

**Comment by Flet** [comment]
This is slightly different, but I was having some fun with the web audio API.

https://youtu.be/-iMlycCs0aM

https://youtu.be/g1B-ZDO0HgA

These are using the web audio AnalyserNode to render a waveform/frequency graph on a `<canvas>` in real time as the audio plays.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API

**Comment by feross** [comment]
@Flet, that's really cool! Can you send a PR so I can play around with that?

**Comment by grunjol** [comment]
it would be nice to display waveform (time) or spectrum (frequency)

**Comment by feross** [comment]
Closing this now since we've support playing audio for a while!
