### ISSUE TITLE
'Run in background' mode

### ISSUE THREAD

**Issue by iadj** [feross/webtorrent-desktop#150]
The app should stay running by default after closing the window and display inside an application icon (bottom right for Windows, top right for OSX & Linux), so torrents can consistently download & upload while running the app on the background.

**Comment by feross** [comment]
Agreed. This is standard for torrent clients.

One note: A menu bar item is not necessary on OS X. WebTorrent.app already continues running when the window is closed. You can reactivate the app by clicking on the dock icon.

**Comment by iadj** [comment]
Makes sense. Definitely not necessary for OSX regarding the dock.

**Comment by dcposch** [comment]
Looks like we can use this: https://github.com/atom/electron/blob/master/docs/api/tray.md
