### ISSUE TITLE
Uncaught error "torrent is destroyed"

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#160]
<img width="553" alt="screen shot 2016-03-19 at 3 52 05 pm" src="https://cloud.githubusercontent.com/assets/121766/13901747/980f1b8c-edea-11e5-8e9c-58b9bb575995.png">

**Comment by dcposch** [comment]
We thought we fixed this back in March, and we thought we fixed it again in version 0.15 released two days ago, but according to telemetry it's still happening sadly

@feross

**Comment by feross** [comment]
@dcposch Lol, I just made a new issue for the recent occurrences: https://github.com/feross/webtorrent/issues/922
