### ISSUE TITLE
"possible EventEmitter memory leak" warning on adding 11th torrent

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#161]
<img width="542" alt="screen shot 2016-03-19 at 3 55 31 pm" src="https://cloud.githubusercontent.com/assets/121766/13901756/1214f8de-edeb-11e5-8b79-e988bb9742e8.png">

Let's silence this nonsense.

**Comment by rom1504** [comment]
I guess it's about adding `this.setMaxListeners(0)` at https://github.com/feross/torrent-discovery/blob/master/index.js#L18 but not 100% sure without the uncut stacktrace.

**Comment by feross** [comment]
This was actually caused by the way we reuse a single DHT instance for all torrents. The fix is actually to
dht.setMaxListeners(0) inside of `webtorrent/index.js` which I will do now.
