### ISSUE TITLE
Add DLNA/UPnP support

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#186]
* Discovery 
 - https://www.npmjs.com/package/ssdp-js
 - https://www.npmjs.com/package/node-upnp-client
* Renderer client 
 - https://www.npmjs.com/package/upnp-mediarenderer-client

**Comment by feross** [comment]
What are DLNA and UPnP actually used for? I've never seen any device that supports these.

**Comment by grunjol** [comment]
UPnP is a set of protocols that allow different devices to discover each other and use the services that they can offer.

DLNA is derived from UPnP specifically for the purpose of media interoperability that includes media formats (transcoding) and system management.

I think the main difference between them is DLNA is an open specification, AirPlay is proprietary (the unofficial spec was reverse engineered) and limited to Apple ecosystem.

The model is also different, in Airplay/Chromecast you *push* the content from the source to the renderer, in DLNA case you have  Media Server | Controller | Renderer. In our case, the controller and media server are in the program and the renderer is the TV, but you can have a big storage (like a NAS) a DLNA ready  TV (most of today's SmartTVs) and a controller (ie a tablet/phone), with the controller you can browse the content of the available sources and instruct the renderer to *pull* the files from it.

About the support, I think all the big TV brands with 'smart' capabilities are DLNA certified and I am talking about [Philips/Samsung/Sony/Panasonic](http://www.dlna.org/products/)
Also Android and linux based media players do DLNA

**Comment by grunjol** [comment]
I am working on a `dlnacasts` project to support DLNA with a mafintosh/chromecats compatible API.

**Comment by grunjol** [comment]
@feross, @dcposch : I already implemented [dlnacasts](https://www.npmjs.com/package/dlnacasts) a mafintosh/chromecasts API compatible module for DLNA.

Just waiting PR #248 to be merged to make another PR to fix this issue. Already tested with 3 DLNA devices (2 TVs and one android media player).

**Comment by feross** [comment]
Fixed in #287
