### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#190]
- [x] OS X
- [x] Windows
- [x] ~~Linux~~

**Comment by feross** [comment]
I'm working on this right now.

**Comment by feross** [comment]
Got OS X working – will push tomorrow. Time for sleep.

**Comment by feross** [comment]
Electron does have a built in auto-update solution for Linux, so I'm going to scratch it from the list.

More info: http://electron.atom.io/docs/all/#linux

**Comment by feross** [comment]
For Linux, I think we can just release .deb files for now investigate creating a PPA, or submitting to the Ubuntu Software Center, perhaps.

**Comment by feross** [comment]
For Windows, I've applied for an Authenticode cert. Once that's issued, I'll be able to sign the Windows releases and the auto-updater should work. I'll push the work-in-progress version (without signing support) to a branch.

**Comment by feross** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Signing_an_executable_with_Authenticode

**Comment by c0b41** [comment]
@feross any progress for linux?

**Comment by grunjol** [comment]
I am working on a deb package generator (PR coming soon)

Regarding auto-update, i see 2 options

* check version and provide download link (current implementation)
* system update 
 * create a deb/rpm repository in webtorrent infrastructure
 * use an external repository (launchpad, bintray)

I use [bintray](https://bintray.com) in some private projects and its very versatile (offers deb, rpm, maven, docker and others), and its free for open source projects

**Comment by c0b41** [comment]
@grunjol hey launchpad or bintray any progress? now linux update useless.

also travis bintray deployment cool [checkout](https://docs.travis-ci.com/user/deployment/bintray)

**Comment by gtomas41** [comment]
Please publish a RPM
