### ISSUE TITLE
UI responsiveness

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#208]
- [x] Disabling download of a torrent doesn't update UI immediately
- [x] Dropping a large file to seed takes *seconds* to show up in the UI.
  - We should show it right away, and not wait for the `'torrent'` event which only happens *after* the whole file has been hashed.
- [ ] Mouseover events take up to 1 second to kick in because they're not handled right away but only on `update()`. The right way to handle them is immediately, but [throttled](https://npmjs.com/package/throttleit).

**Comment by dcposch** [comment]
I can fix the second one.

For the third one, what do you mean by "Mouseover events take up to 1 second to kick in"?

**Comment by dcposch** [comment]
Re: mousovers being slow, I see what you mean now -- I assume you're talking about the buttons showing up in the torrent list when you mouse over a torrent. I've seen that take >1 second, too.

Unfortunately that's not done in update(), the buttons show up using a CSS `:hover`. It's lagging on startup when I have lots of torrents and WebTorrent is verifying ~20GB worth of files.

* Caching file verification results with the file modtime will make startup a smoother & less laggy
* I think the Real Fix is moving WebTorrent to a different process

**Comment by feross** [comment]
@dcposch Re: that third point, I'm actually talking about how the player UI currently shows/hides itself. It can take up to one second for a `mediaMouseMoved` event to cause the UI to show up.

I'll re-open this for now and take a stab at fixing it later.
