### ISSUE TITLE
Sign Windows .exe file

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#219]
Sign binary for safer auto-updates and fewer install warnings upon first install.

I'm currently in the process of getting a cert. Bought one for $90. They want me to get an in person notary to prove that I'm who I say I am before they will issue the cert.

Will continue update this issue with the progress.

**Comment by feross** [comment]
Getting the notary tomorrow morning at 10am.

**Comment by feross** [comment]
Sent to notary forms to Comodo today. Hopefully I'll get the cert by Friday, but we'll see.

**Comment by ungoldman** [comment]
You should write a blog about all the trouble you're going through for these auto-update certs!

**Comment by feross** [comment]
@ungoldman Hah, good idea.

**Comment by feross** [comment]
I finally got the cert earlier this week, but had trouble figuring out where the private key was stored. It was the weirdest process I've ever seen! 

The CA required the order to be placed from Firefox. The private key and CSR (certificate signing request) were generated in the browser. I think it wasn't possible (or easy) to copy the private key out, so I assumed that they were just going to keep a copy of it, which seemed really sketchy.

It turned out that they stored the private key in Firefox's local storage. They just got the CSR. After the weeks of verification, I got an email saying that the cert was ready. If you click the link in any browser but the original one where the order was placed, the certificate will be downloaded, without the private key.

But if you go back to the original Firefox browser, then an alert shows up saying that a certificate was installed in Firefox -- WITHOUT a user prompt! It just installed itself automatically. What?

At this point, you can export the combined cert and private key file (.p12 /.pfx) to use for signing.

What a ridiculous process.
