### ISSUE TITLE
npm install webtorrent-app -g

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#251]
- [x] Make bin script (https://github.com/feross/webtorrent-app/issues/247)
- [x] Publish to npm
- [ ] Package the app in postinstall script
  - Just launching Electron is not sufficient. Arguments are handled differently in dev vs. production mode. And on OS X, the app will show up as "Electron" in the menu bar, not "WebTorrent" because there's no Info.plist.

**Comment by ungoldman** [comment]
You may want to look at https://github.com/brave/electron-prebuilt/commit/80392709b5a3221b22d63006041245602e1545be regarding naming the application binary without building for production.

**Comment by dcposch** [comment]
Works fine on Linux as is

**Comment by dcposch** [comment]
Mac and Windows have working auto updaters & should be installed the standard way
