### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by arestov** [feross/webtorrent-desktop#252]
1. Start some torrent.
2. Ensure torrent is started
3. Remove torrent completely
4. Take a snapshot and filter `torrent` in list

![memory-leak](https://cloud.githubusercontent.com/assets/69734/14072820/8d322388-f4cc-11e5-8def-44f7325d2a09.png)

https://github.com/feross/webtorrent/issues/207

**Comment by feross** [comment]
Thanks for the report.

**Comment by dcposch** [comment]
@feross was this the one you fixed a while ago?

**Comment by feross** [comment]
No, I fixed part of the leaks. In some situations, torrents are still leaked somehow.

**Comment by feross** [comment]
Looking into this again.

**Comment by feross** [comment]
As of `webtorrent` v0.91.0, I believe all the memory leaks are fixed. See the changelog here: https://github.com/feross/webtorrent/blob/master/CHANGELOG.md#v0910---2016-04-21

These fixes will go out in WebTorrent Desktop v0.4.0.
