### ISSUE TITLE
Torrent Performance

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#256]
- [x] Fix _drain() / ut_pex() creating tons of peers which are immediately destroyed
- [x] ut_pex leaks an interval
  - https://github.com/feross/webtorrent/pull/706
- [x] Replace all hot code where splice() is used with [unordered-array-remove](https://github.com/mafintosh/unordered-array-remove), which doesn't create a new array.
  - https://github.com/feross/webtorrent/pull/707
- [x] Replace all instances where we set an object value to `null` with `delete obj[key]`, to make for-in iterations have way less keys to iterate over.
  - https://github.com/feross/webtorrent/pull/708
- [x] Torrents that we are seeders on should not keep trying to connect to new peers
  - https://github.com/feross/webtorrent/pull/709
- [x] Remove `Function.prototype.bind` in tight loops
- [ ] Report WebRTC cpu leak to Chromium
- [ ] ~~Ensure crypto.subtle is being used~~ See https://github.com/feross/webtorrent/issues/716#issuecomment-204668449

### waiting on

- [x] https://github.com/fisch0920/ut_pex/pull/6
- [x] https://github.com/mafintosh/unordered-array-remove/pull/1
- [x] https://github.com/michaelrhodes/simple-sha1/pull/11

**Comment by dcposch** [comment]
Just noticed this when starting WebTorrent with ten active torrents, totaling a few tens of GB:

- [ ] File verification on startup can take a long time, ie over a minute

**Comment by arestov** [comment]
> File verification on startup can take a long time, over a minute

Why can't be used some sort of cache based on "last modified" file time?

**Comment by dcposch** [comment]
@arestov yeah that sounds like a good idea

**Comment by dcposch** [comment]
https://github.com/feross/webtorrent-desktop/pull/279

**Comment by feross** [comment]
Done

**Comment by decim** [comment]
I just updated existing issue for WebRTC CPU leak. I am not sure that they will notice it. So if someone has connections with those guys please tell them about this bug. 

https://bugs.chromium.org/p/chromium/issues/detail?id=392651

**Comment by feross** [comment]
@decim Thanks for sharing the link.

**Comment by feross** [comment]
I opened an issue on the WebRTC tracker about the CPU leak: https://bugs.chromium.org/p/webrtc/issues/detail?id=5733
