### ISSUE TITLE
Wrong background image for audio file

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#260]
![screen shot 2016-03-28 at 3 12 44 pm](https://cloud.githubusercontent.com/assets/121766/14091861/885fd816-f4f7-11e5-8941-4b8854371561.png)

For reference, this is what my downloads list looks like:

![screen shot 2016-03-28 at 3 13 03 pm](https://cloud.githubusercontent.com/assets/121766/14091877/9a7bbad8-f4f7-11e5-8d82-5ac4e41b9cc0.png)

cc @dcposch

**Comment by feross** [comment]
Pretty hilarious to see "Laying Plans, Waging War" overlayed on top of the Big Buck Bunny screenshot ;)

**Comment by dcposch** [comment]
sorry this is some extreme derpage. my bad. fix coming soon.
