### ISSUE TITLE
Leave WebTorrent running overnight -> blank window

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#272]
![image](https://cloud.githubusercontent.com/assets/169280/14161452/d08c8c36-f698-11e5-94ee-b4f6f4a2d672.png)

**Comment by dcposch** [comment]
Also, the console doesn't respond. V weird. It's as if the JS interpreter died or something--I can open dev tools and I can type in an expression, but after hitting enter it just disappears.

**Comment by rom1504** [comment]
sounds like https://github.com/feross/webtorrent/issues/551

**Comment by dcposch** [comment]
Ran webtorrrent overnight again and memory usage is reasonable, UI is still snappy. Good sign.

Webtorrent Desktop 78b90296c, Webtorrent 0.88.3

**Comment by feross** [comment]
Just fixed a leak of the Torrent object in `torrent-discovery`. Testing now to see if that has improved things.

**Comment by feross** [comment]
I just noticed this happening reliably with the Sintel torrent when it's opened via a magnet link. Causes the whole client to get a blank screen.

Going to try to get to the bottom of this, since I can reliably reproduce it now.

**Comment by feross** [comment]
We have crash reporting now: #298 so in the future we can take a look at the core dumps if/when we see this type of failure again.

It might be gone now that we're not leaking so much memory :)
