### ISSUE TITLE
Subtitles / Closed Captions support

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#281]
Basic implementation

- [x] adding subtitle files manually
  - [x] via drag-drop
 - [x] via [CC] icon (Ctrl+Click)
  - [x] via menu (since drag-drop is not very discoverable) (#521)
- [x] detect subtitle files in the same folder (in our case, that's in the torrent) (#520)
- [x] allow selecting among multiple subtitle files
- [x] allow disabling subtitles
- [x] multiple charset encoding

**Comment by grunjol** [comment]
Support for

* Internal: subtitles files inside torrent
* External: locally and remote subtitles files

**Comment by MoOx** [comment]
If that can help, peerflix handle this.

**Comment by feross** [comment]
So does Playback.

**Comment by MoOx** [comment]
I can't find a way in Playback to add external subtitles, peerflix supports this.

**Comment by feross** [comment]
@MoOx I think you have to drop them on the video player while it's playing.

**Comment by luismanuelmansilla** [comment]
Other think is the "track synchronization" of the subtitles.. sometime is very helpfull when the subtitles don't match with the audio.

**Comment by andreapaiola** [comment]
If we want to support only basic (no 3D or special effects support) .srt format the implementation is straightforward...
but there are also other formats for subtitles.

Can we declare the goal here, please?

We can load and handle zipped(?) .srt(s) local files, if you want also remote files the interface will be different with a dialog for the URL or something like that.

**Comment by feross** [comment]
I think `.srt` and `.vtt` support is fine for now. These should be straightforward to support, with the help of the html5 video tag.

We don't need to support zipped files or a remote interface. I think the goal here should be to support the basic set of features that VLC supports:

- [ ] adding subtitle files manually
  - [ ] via drag-drop
  - [ ] via menu (since drag-drop is not very discoverable)
- [ ] detect subtitle files in the same folder (in our case, that's in the torrent)
- [ ] allow selecting among multiple subtitle files
- [ ] allow disabling subtitles

That's probably enough.

**Comment by feross** [comment]
PR sent for basic subtitle support via drag-n-drop: https://github.com/feross/webtorrent-desktop/pull/361

**Comment by danielhf** [comment]
Using only webtorrent in browser. Is there a way to add subtitles to the video without download anything? I mean, only using <script src="webtorrent.min.js"></script>

**Comment by rom1504** [comment]
@danielhf try https://andreapaiola.name/niagara/

**Comment by danielhf** [comment]
It doesn't Work, I add a subtitle and with the default magnet include and nothing happens.

Does webtorrent work with MKV too?

**Comment by andreapaiola** [comment]
just changed the default magnet, now it works

**Comment by danielhf** [comment]
is there a way to change charset to subtitles? to windows-1252 for example? The code to add the subtitles it's available on github?

**Comment by andreapaiola** [comment]
danielhf we're OT here (sorry guys)

the code is in page, no charset handled

End of OT, I hope.

**Comment by ricardomspires** [comment]
Current subtitles via CC don't support special characters.

**Comment by grunjol** [comment]
There is a problem in srt-to-vtt  handling non-UTF8 charsets. I am working in a solution to that.

**Comment by grunjol** [comment]
moved features list to first comment

**Comment by filipeaguiar** [comment]
Is it fetching subtitles on services like opensubtitles planned?

**Comment by feross** [comment]
@filipeaguiar No, integration with external services is not planned. WebTorrent is an un-opinionated torrent client that does not favor any specific services.

**Comment by feross** [comment]
I'm going to start preparing the v0.4 release. 

I think the subtitles support we have now is already pretty good and don't want to delay the release anymore for the remaining task items. Let's keep this issue open to track the remaining items. But I'll change the milestone to v0.5.

(I want to start doing a release whenever there's a new significant feature. So, like when the rest of this issue is fixed, that should be a new release. If we always keep `master` shippable, we can do regular releases!)

**Comment by grunjol** [comment]
Sounds good to me.
Lets implement remaining items in v0.5.

**Comment by dcposch** [comment]
Sounds good. What I'm working on isn't urgent.
*I w ant to automatically detect SRT and VTT files next to a video file.
* I don't know if we need a menu item. I think the CC button is easy to discover.
* Ideally we'd support embedded subtitles in MP4 and OGV videos, but that looks like a lot more work, and I think we can leave it for later.

Thoughts?

**Comment by feross** [comment]
> I want to automatically detect SRT and VTT files next to a video file.

👍 

> I don't know if we need a menu item. I think the CC button is easy to discover.

I think you're right but we still need it for accessibility reasons. The menu items are really easy for screen reader users to interact with. Also, on OS X, you can search for functionality via the Help menu (there's a search box) and it only searches menu items, so it's worth adding for that reason.

I don't think it's the most urgent thing, or that we need it to be really fancy (i.e. showing all the language choices for now). An "Add Subtitles File..." menu would be sufficient.

> Ideally we'd support embedded subtitles in MP4 and OGV videos, but that looks like a lot more work, and I think we can leave it for later.

👍

**Comment by dcposch** [comment]
💯

**Comment by feross** [comment]
👍 👍 👍
