### ISSUE TITLE
Put WebTorrent in its own process

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#282]
We can do that by spawning a second window in addition to the main window, which only runs WebTorrent and stays hidden.

That should keep the UI snappy. Currently it lags if there's enough load.

**Comment by feross** [comment]
Related issues on the Playback project:

https://github.com/mafintosh/playback/issues/58
https://github.com/mafintosh/playback/pull/86

**Comment by dcposch** [comment]
done

**Comment by feross** [comment]
This definitely makes things snappier!
