### ISSUE TITLE
Allow dragging magnet links

### ISSUE THREAD

**Issue by raeesiqbal** [feross/webtorrent-desktop#284]
It would be handy to have the app accept dragging of torrent links instead of doing a manual copy-paste.

**Comment by raeesiqbal** [comment]
Maybe need to make some changes [here in the drag-drop package](https://github.com/feross/drag-drop/blob/master/index.js#L37).

**Comment by dcposch** [comment]
Looked into it. This would require making `drag-drop` a lot fancier / more complicated or writing our own drag drop handler. Don't know if it's worth it. You can always click + and paste in a magnet link.

**Comment by holmesworcester** [comment]
It might be worth changing the text to say "Drop a torrent here or paste a magnet link (sorry, dragging magnet links won't work)"

Right now the language is technically clear, but I assumed it was possible to drag a magnet link.

**Comment by codealchemist** [comment]
I've added a PR on **drag-drop** which adds support to drop magnet links.
https://github.com/feross/drag-drop/pull/25

**Comment by feross** [comment]
Thanks for the PRs to `drag-drop`, @mathiasvr and @codealchemist ! I think this should be straightforward to implement in WebTorrent Desktop now 👍

**Comment by feross** [comment]
Sent a PR that implements this: https://github.com/feross/webtorrent-desktop/pull/758

Review and testing welcome! https://github.com/feross/webtorrent-desktop/pull/758

**Comment by codealchemist** [comment]
Awesome! Thanks @feross!
Already added comments on the PR :)
