### ISSUE TITLE
Cast: support more than one device of the same type

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#301]
I have more than one device supporting DLNA. While testing the feature, I found that webtorrent-desktop was using any of them randomly. This is because it depends on how fast the device answer the broadcast signalling (discovery), and the one that will play is the latest to answer.

This should happen (didn't test it but the logic is the same) with airplay and chromecast too.

I am thinking about college dorms, or shared connections with the same broadcast domain.

You should be able to select which device you will cast to.

**Comment by feross** [comment]
:100:

**Comment by dcposch** [comment]
@grunjol still doing this? Otherwise I can probably implement it today or tomorrow

**Comment by grunjol** [comment]
No problem.

**Comment by dcposch** [comment]
done
