### ISSUE TITLE
Copy magnet link to clipboard doesn't work sometimes

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#304]
Can't reproduce reliably. Started happening after webtorrent was moved to it's own process

**Comment by leodutra** [comment]
Happens with Arch Linux common XDG configuration, even adding the following lines to `mimeapps.list`:
``` 
x-scheme-handler/magnet=webtorrent-desktop
application/x-bittorrent=webtorrent-desktop;
```

**Comment by leodutra** [comment]
All data is ok and sent to IPC "wt-start-torrenting"... digging deeper.

**Comment by leodutra** [comment]
Format sent by Popcorn-Time:
`magnet:?xt=urn:btih:9FB6CE0A7282EB8CA1443A2E41C87AB725133A38&amp;tr=udp://glotorrents.pw:6969/announce&amp;tr=udp://tracker.opentrackr.org:1337/announce&amp;tr=udp://torrent.gresille.org:80/announce&amp;tr=udp://tracker.openbittorrent.com:80&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://p4p.arenabg.ch:1337&amp;tr=udp://tracker.internetwarriors.net:1337`

Format received on Webtorrent main.js onOpen():
`magnet:///?xt=urn:btih:9FB6CE0A7282EB8CA1443A2E41C87AB725133A38&amp;tr=udp://glotorrents.pw:6969/announce&amp;tr=udp://tracker.opentrackr.org:1337/announce&amp;tr=udp://torrent.gresille.org:80/announce&amp;tr=udp://tracker.openbittorrent.com:80&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://p4p.arenabg.ch:1337&amp;tr=udp://tracker.internetwarriors.net:1337`

File API added a 3 slashes before query mark `?`

Fixing.
