### ISSUE TITLE
Progress should get sent to main window more frequently while fetching torrent metadata

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#306]
It's currently less than once per second

**Comment by dcposch** [comment]
?

The main window gets an update as soon as the torrent fires an `infohash` event, then again on `ready`, then it gets a `progress` message once a second while the torrent is downloading or seeding.

**Comment by feross** [comment]
When adding a magnet link, on a bad network, it can sometimes take 10-30 seconds before `ready` fires. We want to keep showing updates, like the number of peers, etc. during that time,

**Comment by dcposch** [comment]
@feross I think we do get `wt-progress` events before `ready`. Is this still broken for you?

**Comment by feross** [comment]
This is working the way I expect now. Closing.
