### ISSUE TITLE
downloadSpeed is off

### ISSUE THREAD

**Issue by astro** [feross/webtorrent-desktop#332]
The displayed throughput rate is not reflecting what other bandwidth monitors say. It seems to increase the more often I seek to missing positions in playback.

**Comment by dcposch** [comment]
This might be fixed already. We had a bug with Web Seeds earlier where WebTorrent would send wayyy too many HTTP requests concurrently -- so you could seek to a different spot in a torrent or even remove the torrent entirely, and there would still be tons of requests out that take minutes to finish.

**Comment by dcposch** [comment]
Let us know if it happens again on the latest version of WebTorrent!

**Comment by dcposch** [comment]
Also, plz double check that:
* There aren't other programs running taking significant bandwidth
* The bandwidth monitor isn't counting loopback traffic.

When you're watching a video in WebTorrent Desktop, it's actually running a local HTTP server, with a `<video>` tag pointing at it.
