### ISSUE TITLE
"Open Torrent Address" should focus the input field

### ISSUE THREAD

**Issue by astro** [feross/webtorrent-desktop#333]
I went there to paste a link to a torrent file.

1. Ctrl-V
2. Apparently nothing happens
3. not noticing: a new torrent got added in the main view 
4. I click to focus the input field in the dialog that is still open
5. Ctrl-V to paste
6. OK
7. Now it seems I've got two similar torrents? What are these?

**Comment by astro** [comment]
Seems to have been fixed. Thanks!

**Comment by feross** [comment]
We can scroll to the bottom to ensure the user sees that it's been added after Ctrl+V!

Also, it appears that autofocus only works the first time the dialog is opened. PR incoming to fix that.
