### ISSUE TITLE
Ability to tweak audio volume

### ISSUE THREAD

**Issue by MoOx** [feross/webtorrent-desktop#337]
VLC and MplayerX have options to adjust audio volume from 0 to 200%, and that's handy to adjust separately to OS volume (eg iTunes can do that too).
That would be nice to have such an option.
Btw, i like the scroll on the view to adjust volume (vlc and mplayerx behave this way).

**Comment by gdelavald** [comment]
#330

**Comment by dcposch** [comment]
done
