### ISSUE TITLE
Issue when loading/playing (with a slow connection)?

### ISSUE THREAD

**Issue by MoOx** [feross/webtorrent-desktop#339]
Here was my scenario:
I loaded a torrent and I have a not so fast connection (2Mb/s, so around I download around 200kb/s).
The download started, a few second later video started too, but paused after a second. Download continued, and I have like 20% of the video but the playback does not continued... I tried to click on play/pause, no effect. I tried to change the position in the red bar, no effect. I had to go to home (top left previous button) so I can play again the video.

**Comment by MoOx** [comment]
If that can help peerflix handle pauses correctly, and continue after there is "enough" data to continue.

**Comment by dcposch** [comment]
Similar to #346, I think this might be because something threw a JS exception.

Once we add exception logging, it will be easier to find out about & fix these kinds of things. In the meantime, if it happens again, open Developers Tools (Under View > Developer) and let us know what you see!

**Comment by dcposch** [comment]
Thx for the bug report

**Comment by feross** [comment]
Closing because this is old and there's no more information to go on.
