### ISSUE TITLE
Read download directory location from the OS

### ISSUE THREAD

**Issue by marek-saji** [feross/webtorrent-desktop#349]
WebTorrent uses ~/Download as a download directory, as decided in https://github.com/feross/webtorrent-desktop/issues/53#issuecomment-193098170, but location may change depending on user's locale or be edited by hand.

On Linux there's XDG spec for specifying how to get directories’ locations ([xdg package](https://www.npmjs.com/package/xdg) looks promising (I haven't used it nor looked at the code)). Don’t know how to do that on other platforms.

**Comment by feross** [comment]
Fixed on `master`
