### ISSUE TITLE
show playback time (current/total)

### ISSUE THREAD

**Issue by ungoldman** [feross/webtorrent-desktop#351]
Example from youtube:

![screen shot 2016-04-07 at 10 43 54 am](https://cloud.githubusercontent.com/assets/427322/14360982/aaae5164-fcad-11e5-8c96-e509e22d2a64.png)

**Comment by sguergachi** [comment]
How hard would it be to do this? Are there any endpoints from which to get this info from?

**Comment by rom1504** [comment]
have a look at https://github.com/feross/webtorrent-desktop/blob/f70d360194316ac3e8ac73cee13d17e7d2f1fb78/renderer/webtorrent.js#L216
