### ISSUE TITLE
High CPU utilization 

### ISSUE THREAD

**Issue by izdi** [feross/webtorrent-desktop#353]
**Version 0.3.3 (0-a5366c3) OS X El Capitan**

Whats up with so high CPU utilization. Threads spawning during some period even after torrent's already downloaded.

![cpuwebtorrent](https://cloud.githubusercontent.com/assets/6037501/14365771/1afac802-fd18-11e5-8f1f-c7f2b896ca5f.png)

After 5 minutes
 
![after5 minutes](https://cloud.githubusercontent.com/assets/6037501/14365785/2812b3ce-fd18-11e5-8c0c-10bae8d108cb.png)

**Comment by feross** [comment]
@izdi This is a known Chromium bug that will be fixed in 6-12 weeks.

See this issue: Creating then destroying connections causes 100% CPU https://bugs.chromium.org/p/webrtc/issues/detail?id=5733

**Comment by feross** [comment]
I made a build **without** WebTorrent trackers (so no WebRTC connections) and will try running it overnight and see how well it fares.

**Comment by feross** [comment]
The build that doesn't create WebRTC connections was still working fine for me come morning time. Hmm...

**Comment by feross** [comment]
Chrome just released version 50. The fix we need is in version 51. Chrome waits 6 weeks between releases, and Electron updates the Chrome version [after 2 weeks](https://github.com/electron/electron/blob/master/docs/faq/electron-faq.md).

So we're looking at 8 weeks before this is fixed.

**Comment by feross** [comment]
As a stopgap solution **for OS X only**, we are going to disable WebRTC peers in the next version of WebTorrent (v0.4.0) since the 100% CPU issue is makes the app look broken, when it's not even our fault.

Once Chrome 51 is included in Electron, we'll undo this change and re-enable WebRTC peers on OS X.

PR here: https://github.com/feross/webtorrent-desktop/pull/511

**Comment by feross** [comment]
Electron 1.2.0 was just released, which includes Chrome 51. PR here: https://github.com/feross/webtorrent-desktop/pull/594
