### ISSUE TITLE
Provide non-exe install for Windows

### ISSUE THREAD

**Issue by gqmrtgma** [feross/webtorrent-desktop#358]
https://github.com/feross/webtorrent/issues/733

**Comment by feross** [comment]
@gqmrtgma What is that useful for?

**Comment by grunjol** [comment]
In windows, non-administrator (or without install privileges) users can not install software on ProgramFiles forlder.

So its very common to have an _standalone_ or _portable_ version that can be dropped (unzipped) on user's folders or a thumb drive and simply execute it there.

In the case of portable apps, config and download directories should be in the same folder the application lives.

http://portableapps.com/about/what_is_a_portable_app

**Comment by feross** [comment]
The WebTorrent installer installs the app into `AppData` though. So it should work for non-admin users.

Someone should test this.

**Comment by nkittsteiner** [comment]
I tested the installer on Windows 10 Pro (x64), with one account without privileges, and was installed without problems. The only situation detected, was a Windows Firewall popup appears, asking for privileges for unblocking WTD

**Comment by feross** [comment]
Yeah, the Windows Firewall prompt is normal for any application that talks to the network. All torrent clients will have this prompt.

**Comment by feross** [comment]
Just asked about getting WebTorrent Deskop added to the Portable App Platform, which would expose it to lots of new users.

**Comment by feross** [comment]
Looks like this might be pretty easy to do. Here's how Audacity did it: http://wiki.audacityteam.org/wiki/Portable_Audacity

**Comment by feross** [comment]
I just sent a PR to add a Windows portable app! If all looks good and it gets merged, there will be a Windows portable app for the next release (v0.4.0).
