### ISSUE TITLE
Error message on start up?

### ISSUE THREAD

**Issue by nickdoonan** [feross/webtorrent-desktop#363]
i0.3.3

Windows 10

Ran normally and with admin privildges

**What did you expect to happen?**load a magnet link
error in console saying "Not allowed to load local resource: file:///C:/Users/BLANK\AppData\Local\WebTorrent\app-0.3.3\resources\app.asar\renderer\main.html

**Comment by feross** [comment]
Sorry that this didn't work for you. Can you share how you added the magnet link? Did you just paste it in with Ctrl+V? Or did you click "File > Open Torrent Address..."?

Can you try it again with a different magnet link and see if it happens again?

Any more information that you can provide would be super helpful. Thanks a lot!

**Comment by dcposch** [comment]
`file:///C:/Users/BLANK/...`

@nickdoonan is your windows username "BLANK"? If not we've got a bug, lol

**Comment by dcposch** [comment]
(If you edited it to avoid revealing your real username that's totally fine, just let us know.)

**Comment by feross** [comment]
I don't understand this error. If the main window is already loaded, why would there be an error message about loading `main.html`? Also, why the mixed forward and backslashes in the path?

**Comment by nickdoonan** [comment]
i changed the username to blank myself for c+p purposes. it loads up and when i try to add a file i go to the console debug which says error.

**Comment by feross** [comment]
Closing due to lack of new information. We'll keep our eyes out for this particular bug in case we get any new leads on how to potentially solve it.
