### ISSUE TITLE
[Windows tested] App icon on volume mixer is too big

### ISSUE THREAD

**Issue by ouel92** [feross/webtorrent-desktop#365]
**What version of WebTorrent Desktop?**

0.3.3

**What operating system and version?**

Windows 10 64 bits 
v0.3.3

**What did you do?**

Open the windows volume mixer

**What did you expect to happen?**

Be able to control WT Desktop's volume

**What actually happened?**

The icon is too big which hides the volume control

Screenshot attached
![image](https://cloud.githubusercontent.com/assets/11077257/14392216/2e97db5c-fdb8-11e5-9264-7bd8803cf6dd.png)

**Comment by karloluis** [comment]
The problem here is that the tray icon is related to the volume mixer. I made a the icon smaller to fit the volume mixer but the tray-bar icon gets distorted. Still looking for more solutions in code, some other repo might also have the solution.

**Comment by karloluis** [comment]
Please test the merge on different platforms so that we can close this issue.

**Comment by feross** [comment]
Tested on Windows 10, looks good.
