### ISSUE TITLE
External players like VLC

### ISSUE THREAD

**Issue by diimdeep** [feross/webtorrent-desktop#368]
Until media playback will be feature rich, with subtitles, audio track selection etc., might be good to support external players. 
Although manual open file in VLC works just fine.

**Comment by dcposch** [comment]
#424

**Comment by lewisl9029** [comment]
I would personally prefer using the "Open With" dialog to allow users to choose their own video player, rather than hard coding VLC detection and support. Thoughts?

**Comment by dcposch** [comment]
@lewisl9029 sounds reasonable, might implement that in a future version

The great thing about VLC is that it can play all common media formats. If WebTorrent Desktop can't play a file, that means it probably uses the AC3 or DTS codecs or the AVI container format. Either way, most other video players that aren't VLC won't play it either.

**Comment by rom1504** [comment]
mpv and mplayer are pretty good at reading every format too (https://github.com/feross/webtorrent-cli/blob/master/bin/cmd.js#L191)

**Comment by feross** [comment]
Yep, we'll add this in a future version.

**Comment by feross** [comment]
This is done now, thanks to @dcposch

**Comment by JaKXz** [comment]
Is being able to specify `mpv` as the default player going to be an option soon? I'm using v0.7.2 and I don't have VLC installed at all.

**Comment by feross** [comment]
@JaKXz See #682
