### ISSUE TITLE
Choose device (DLNA, chromecast, or Airplay) to stream

### ISSUE THREAD

**Issue by orbitingful** [feross/webtorrent-desktop#370]
**What version of WebTorrent Desktop?**
0.3.3
**What operating system and version?**
Windows 8.1
**What did you do?**
Click on the television button to the bottom-right.
**What did you expect to happen?**
Be greeted with a choice of devices to stream
**What actually happened?**
Connected to DLNA

**Comment by grunjol** [comment]
Duplicated #301

**Comment by feross** [comment]
@orbitingful Thanks for opening this issue. As @grunjol said, it's a duplicate, so you can follow along with the progress at #301.
