### ISSUE TITLE
Losing audio

### ISSUE THREAD

**Issue by chinabala** [feross/webtorrent-desktop#372]
**What version of WebTorrent Desktop?**
0.3.3 (0-a5366c3)
**What operating system and version?**
OS X Yosemite 10.10.5
**What did you do?**
drag a torrent  on it and play
**What did you expect to happen?**
play normally with audio
**What actually happened?**
there's no audio at all, even with any other torrents.

**Comment by amurillofuentes** [comment]
Same problem in my Macbook Air, with OSX El Capitan 10.11.4, 8GB RAM, 1,8 CPU with Webtorrent Desktop 0.3.3 (0-a5366c3)

**Comment by rom1504** [comment]
is this a different problem than https://github.com/feross/webtorrent-desktop/issues/350 ?

**Comment by amurillofuentes** [comment]
In my case, I only have safari, not chrome/chromium. I ve tried with other torrents (.avi, .mkv...) and still th esame problem. There is not audio

**Comment by feross** [comment]
I believe this is the same issue as #350. We need to support DTS since it's quite a pervasive audio codec.

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
