### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by montogeek** [feross/webtorrent-desktop#373]
**What version of WebTorrent Desktop?** 0.3.3

**What operating system and version?** OSX 10.10.5

**What did you do?** Hit CMD+Q while the app was downloading 3 torrents

**What did you expect to happen?** Quit the app without errors

**What actually happened?** This error:
![screen shot 2016-04-09 at 23 01 03](https://cloud.githubusercontent.com/assets/1002461/14408019/66aea4ae-fea7-11e5-9261-cb8102b6f073.png)

**Comment by feross** [comment]
Confirmed. I quit the app repeatedly and managed to trigger this error.

**Comment by feross** [comment]
Fixed

**Comment by montogeek** [comment]
Thank you @feross ! :)

**Comment by feross** [comment]
This will be released in the next version of WebTorrent. The app will automatically update when the new version is released.

Cheers!
