### ISSUE TITLE
Offline errors

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#375]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.3.3

**What operating system and version?**

OS X

**What did you do?**

Run WebTorrent while offline.

**What did you expect to happen?**

No errors in the JS console.

**What actually happened?**

dgram.js:487 Uncaught Error: addMembership EADDRNOTAVAIL

Caused by these packages:

- [x] chromecasts
- [x] dlnacasts

**Comment by feross** [comment]
PR sent to node-ssdp (used by `chromecasts`): https://github.com/diversario/node-ssdp/pull/56

**Comment by feross** [comment]
Looks like `chromecasts` uses `node-ssdp` and `dlnacasts` uses `ssdp-js`. @grunjol Any reason you chose the second one? We can lighten the amount of code we rely on if you switch that over to `node-ssdp`.

**Comment by grunjol** [comment]
i think it was because it has no dependencies and it has a DLNA oriented interface. After the fact i realize the other one was more mature.

I can check if i can make the switch tomorrow for the sake of simplicity.

**Comment by grunjol** [comment]
Oh, i remember now, node-ssdp has client and server SSDP implementation and ssdp-js is only client (and the only it needs).

**Comment by feross** [comment]
@grunjol Yeah, I just noticed that `ssdp-js` is more lightweight. I was just looking at handling the EADDRNOTAVAIL error inside of `ssdp-js` but it seems less straightforward. `node-ssdp` handles automatically reconnecting while `ssdp-js` doesn't.

**Comment by feross** [comment]
If it's not too hard, what do you think about switching to `node-ssdp` since it's already being included in WebTorrent via `chromecasts` and it's super solid and mature?/

**Comment by grunjol** [comment]
sure, i will do it

**Comment by feross** [comment]
Going to close this issue now since there are PRs and more specific issues already open elsewhere.

PR to node-ssdp: https://github.com/diversario/node-ssdp/pull/56
Issue on dlnacasts: https://github.com/grunjol/dlnacasts/issues/2
