### ISSUE TITLE
"Help wanted" are a bit out of my league.

### ISSUE THREAD

**Issue by karloluis** [feross/webtorrent-desktop#380]
I've been diving into electron recently and found this repository.

I see there are quite a few _"Help Wanted"_ tags, and found myself wanting to contribute, but I'm inexperienced on most of them. 

Any suggestions of materials to look at so for me to get up to speed. Leave links to docs, tutorials, references, other repos that I might get a look at.

PS I'm still going through the electron docs.

**Comment by feross** [comment]
Awesome, glad you want to help!

In addition to "help wanted", there's also a label for ["good first contribution"](https://github.com/feross/webtorrent-desktop/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+contribution%22). Do any of those look easier?

If you're looking to get better at JavaScript and learn the Node.js APIs, I recommend [Node School](http://nodeschool.io/). In particular, these are the most useful:

```
npm install -g javascripting
npm install -g learnyounode
npm install -g elementary-electron
npm install -g scope-chains-closures
npm install -g stream-adventure
```

I'll also go through all the new issues from the past few days and add more "good first contribution" labels.

**Comment by marcosfede** [comment]
I'm on the same situation, thanks for the material, I'll definitely check that out, and the "good first contribution" tag is an excellent idea, I'll see if I can contribute with some of those issues

**Comment by karloluis** [comment]
Thanks. I'm only missing the last two of those. It's so frustrating only to find beginner tutorials when and miss out on the action. XD
