### ISSUE TITLE
Sound doesn't buffer with the video

### ISSUE THREAD

**Issue by Tx707** [feross/webtorrent-desktop#388]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.3.3

**What operating system and version?**
Windows 8.1 PRO x64 
**What did you do?**
Just clicked the button to play the video. Tried increasing the sound volume and still didn't work.

**What did you expect to happen?**
For the video to start playing with the sound.

**What actually happened?**
The video started playing without the sound.

I also attached a screenshot of my volume mixer. Is it supposed to be like that? I can't even see if the bar is fully loaded or not.

![screenshot_100](https://cloud.githubusercontent.com/assets/1708374/14434526/87c92e1c-0013-11e6-8099-c5994116863e.png)

**Comment by karloluis** [comment]
Fix inbound. #387

**Comment by dcposch** [comment]
This is probably because the `<video>` tag doesn't support AC3 (Dolby Digital).

https://github.com/feross/webtorrent-desktop/issues/350

**Comment by feross** [comment]
@Tx707 You can expect the audio issue to be fixed in a future version of WebTorrent Desktop.

**Comment by feross** [comment]
**If you want to see AC3 support in WebTorrent Desktop, then star this issue:** https://bugs.chromium.org/p/chromium/issues/detail?id=611517

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
