### ISSUE TITLE
Create Torrent options

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent-desktop#389]
This is the only thing I have issue with as far as this client goes. It is very well made for a 0.3 beta and functions in all the right ways. It's a little disappointing that for a torrent to work it NEEDS to have DHT or PEX on. But that's not the point it still seeds on regular BitTorrent and the new WebTorrent sides of the spectrum which is amazing.

But when I go to create a torrent it only allows me to use the directory when creating a torrent but that's a beta disadvantage I'm sure the choice was one or the other and directories are better in that case. But I would love to see tracker editing and webseed adding options. Because at this point in time I'm fine with having to make the torrents in a regular client but I can't find one that will support wss:// links. It errors out. Of course I can make a magnet link and add all that. But then there is no torrent I can use for it. Which is a major downside.

I want to setup my website around Web/BitTorrent and thanks to this client it's been made a LOT easier so thanks and kudos to you Feross in that regard. But there's no way to even change the default list of trackers added to torrents. Or webseeds so there's that too.

**Comment by feross** [comment]
This is done now, thanks to @dcposch
