### ISSUE TITLE
Copy hash to clipboard ?

### ISSUE THREAD

**Issue by Lunik** [feross/webtorrent-desktop#391]
Request to only copy the hash of the torrent when right click on it

**Comment by feross** [comment]
Lunik, what do you use that for?

**Comment by Lunik** [comment]
I use a personnal app based on webtorrent to share content whith my friends. On this platform we only use infoHash. And few days ago I have discovered your desktop app. Which is very usefull by the way. And I only want to copy the hash to share my files.

**Comment by karloluis** [comment]
This intrigues me. any chance you might want to share the name of such project?

**Comment by Lunik** [comment]
Yes of cours ! It's not very advanced, but it works :) https://github.com/Lunik/Instante-Share-Web

**Comment by karloluis** [comment]
Who knows, open as issue ticket over there and maybe he'd be willing to make a pull request. It sounds like a great feature but there are others that seem more pressing.

**Comment by rom1504** [comment]
@Lunik I think it would be interesting to add https://github.com/Lunik/Instante-Share-Web to https://github.com/feross/webtorrent/blob/master/docs/faq.md#who-is-using-webtorrent-today , http://fs.lunik.xyz/ is definitely more intuitive than instant.io

**Comment by Lunik** [comment]
@rom1504 It's still in beta :) But when I'm done, I will definitely do it !

**Comment by feross** [comment]
@Lunik Nice site!

I want to keep the right click options in the Desktop app minimalist. An info hash really isn't enough to download a torrent, especially in the browser where we don't have a working DHT. Without a tracker server, you don't know where to find peers.

So, while it might make sense for a site like Instant.io or your site to let folks just use the info hash, it makes less sense for a full torrent client like WebTorrent Desktop. You can always just get it from the magnet link.

@dcposch Do you agree?
