### ISSUE TITLE
UX refinements

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#396]
- [x] Subtitles
- [x] ~~`README.txt` support (decided not to do this)~~
- [ ] `poster.jpg` support
- [x] Support AC3 and DTS.
  - VLC video player ( https://github.com/RSATom/WebChimera.js ) ?
  - Custom Electron build, as described here ( https://github.com/electron/electron/issues/3259 ) ?
- [x] Better default torrents
- [x] Settings page
- [x] Create torrent settings
- [x] Nicer looking modals (#414)

**Comment by simonrosted** [comment]
Could this be of any help, in regards to supporting external video players?: https://github.com/jaruba/PowderPlayer/issues/60
https://github.com/jaruba/PowderPlayer/commit/7522f1452a30ee5eee1f305db0515f6dfb29ce22
https://github.com/jaruba/PowderPlayer/commit/109b1e371e225af42db5c8c54d61932d4c20789f

**Comment by rom1504** [comment]
There's some code there to start vlc https://github.com/feross/webtorrent-cli/blob/master/bin/cmd.js#L361 (and some other players)

**Comment by grunjol** [comment]
@dcposch i am working on subtitles right now (selection/enablement)

**Comment by dcposch** [comment]
@rom1504 i meant embedding libvlc directly using WebChimera, not opening an external VLC window.

it would look and feel just like it does now --- except it could play a whole lot more formats than the <video> tag supports

**Comment by rom1504** [comment]
Ah yeah that might be an interesting option too. Although I'm sure some people would like the video to open in an external player to use that player.

**Comment by grunjol** [comment]
I am tackling setting page now

**Comment by feross** [comment]
Let's ship the settings page in v0.5.0 so we can get v0.4.0 out tonight.

I'll make a new issue for `poster.jpg` support since it's harder to track individual things in these large meta-issues.
