### ISSUE TITLE
Stop my MacBook from going to sleep

### ISSUE THREAD

**Issue by andrewbrereton** [feross/webtorrent-desktop#397]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.3.3 (0-a5366c3)

**What operating system and version?**
OS X El Capitan

**What did you do?**
I didn't move my mouse for about 5 minutes.

**What did you expect to happen?**
I expected WebTorrent to prevent my computer from going to sleep.

**What actually happened?**
Went to sleep. Chromecast cut out. Had to start it all again and find where I was up to.

**Comment by reminyborg** [comment]
The project is using the powerSaveBlocker functionality in electron to solve this problem.

To debug this further you could open `view -> Developer Tools` and click on the `console` to see that the log line `blockPowerSave` is printed when you start playing a torrent

**Comment by grunjol** [comment]
Did you start playing a torrent? blockPowerSave is only dispatched on media play

**Comment by andrewbrereton** [comment]
I see this line in developer console:

```
blockPowerSave 0
```

Yes, I was streaming a torrent at the time. I was a few minutes into the torrent when the computer went into power saving mode. Once I resumed the laptop and reconnected the Chromecast, I periodically touched the trackpad for the rest of the torrent to prevent it from happening again.

WebTorrent app may have not had window focus at the time, could that have something to do with it?

I just want to explicitly say that the laptop charger was unplugged at the time.

**Comment by reminyborg** [comment]
Ive been digging through this for quite a while and the functionality comes from the chromium project.

I cannot se any reported issues with the functionality but it is used in chrome when you play html5 video.
You could try it as it might be a problem with the base functionality.

Also try to make sure that you don't get the `unblockPowerSave 0` event.

**Comment by reminyborg** [comment]
While you are having this problem you could try using `caffeinate` to prevent the mac from sleeping.

Prevent sleep for 3600 seconds (1 hour)
    caffeinate -t 3600

**Comment by dcposch** [comment]
@andrewbrereton thanks for the bug report.

I think I've found out why this happens and I'm working on a fix!

(In short, WebTorrent blocks your computer from going to sleep when a video is playing, but not when the video is paused, and when you're on Chromecast / Airplay it thinks it's paused. Fix coming soon.)
