### ISSUE TITLE
Webtorrent Client only remove file only from client but not delete that same file from PC. Files still stays in PC directory after removed from Webtorrent client

### ISSUE THREAD

**Issue by Draxler** [feross/webtorrent-desktop#398]
0.3.3 WebTorrent / Win-64Bit 

_________________________

After torrent (movie) is downloaded with Webtorrent client (desktop Win 7) and user delete that same file-movie from/with Webtorrent client, Client removes file only from Webtorrent client, but NOT from PC it self. User need to go to PC directory where that downloaded file is stored and then delete that same file again. Files were not completley removed from PC when downloaded with Webtorrent client and if user try to delete that files with Webtorrent client. It only remove file from client (Webtorrent) but file it self is not deleted from directory where file was downloaded. User need to delete that file again from there, within directory where that file was stored... (I'm sorry if i maybe overlooked and this issue was already menched someplace else, i didn't see it. )
Regards

**Comment by grunjol** [comment]
That's the expected behavior. When you remove the torrent from the program, the downloaded content is not deleted.
Maybe we can implement a 'force content delete' option with a CtrlOrCmd pressed on torrent deletion X)
