### ISSUE TITLE
Torrents created with WebTorrent have invalid created date (year)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#400]
Noticed that Transmission shows the .torrent files created with WebTorrent as from the year 47,893.

![screen shot 2016-04-12 at 18 26 58](https://cloud.githubusercontent.com/assets/121766/14480285/2fadde20-00dc-11e6-9565-8c030e33d112.png)

There's no doubt that WebTorrent is super cool, and definitely feels like it's from the future. But let's fix this.

**Comment by feross** [comment]
Fixed in `create-torrent` v3.24.5.

**Comment by rom1504** [comment]
I didn't know you had to possess a time machine to fix bugs in webtorrent :D

**Comment by feross** [comment]
:)
