### ISSUE TITLE
First startup: Need to copy torrents and posters to app config directory

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#402]
Right now, it's impossible to remove an existing default .torrent file or poster image from the app bundle without breaking users with a config that came from an old version, because the posterURL and torrentPath literally reference a file inside the app bundle. Let's fix this.

**Comment by karloluis** [comment]
What do you mean by 

> "breaking users with a config ..."

**Comment by feross** [comment]
@karloluis I mean that users who install an older version of the app will get a default config file that contains certain default torrents. And if the config references files that are contained within the app bundle itself, we can't remove said torrents without making their config file point to invalid files -- which will make the app look broken.
