### ISSUE TITLE
Pressing play on downloaded torrent resets Window position.

### ISSUE THREAD

**Issue by sguergachi** [feross/webtorrent-desktop#404]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.3.3
**What operating system and version?**
Windows 10 latest.
**What did you do?**
Press play on downloaded video
**What did you expect to happen?**
Plays video in window, with the window not moving
**What actually happened?**
Plays video correctly, but resets window screen position.

**Comment by dcposch** [comment]
it also resizes the window to fit the video, right? that's by design

**Comment by sguergachi** [comment]
So dragging the window to my second screen and having it *always* move to the first screen is by design? Why?

**Comment by dcposch** [comment]
Yeah, it shouldn't move screens, that's a bug --- it should just resize in place
