### ISSUE TITLE
AC-3 audio not working???

### ISSUE THREAD

**Issue by leopoloco** [feross/webtorrent-desktop#407]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.3.3

**What operating system and version?**
Korora 23
**What did you do?**
Tried to reproduce a mkv video with 
Audio
Format                                   : AC-3
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Stream size                              : 121 MiB (9%)
Language                                 : English

**What did you expect to happen?**
To actually listen the audio.
**What actually happened?**
Only the video reproduced without audio.

**Comment by feross** [comment]
Thanks for reporting this. It's a known issue and we're working on fixing this in a future version.

You can follow along here: #350

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
