### ISSUE TITLE
Downloads directory internationalization

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent-desktop#420]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.3.3

**What operating system and version?**

Ubuntu 14.04 LTS

I'm italian and with italian settings the default directory to downloads files is "Scaricati" and not "Downloads".

If you want to start download in a default directory I think that you have to support internationalization...

**Comment by grunjol** [comment]
This issue was fixed in #382, will be included in the next release.
