### ISSUE TITLE
Icon in volume mixer is too big

### ISSUE THREAD

**Issue by gediminaspetrikas** [feross/webtorrent-desktop#422]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.3.3
**What operating system and version?**
Windows 8, 64bit

The issue can be clearly seen in [Volume mixer](http://i.imgur.com/UGm2d24.png "bug"), when any video is playing. Seems that the icon is way too big/doesn't scale correctly

![](http://i.imgur.com/UGm2d24.png)

**Comment by c0b41** [comment]
dups #365 also #387

**Comment by c0b41** [comment]
@gediminaspetrikas so wait for next relase, already fixed bugs

**Comment by feross** [comment]
Going to try to cut a release today or tomorrow, since there's lots of bug fixes we need to get out.

**Comment by gediminaspetrikas** [comment]
Awesome, sorry for not digging deep enough, skimmed through but did not notice those
