### ISSUE TITLE
Where are torrent files kept after webtorrent downloads them?

### ISSUE THREAD

**Issue by NIXOYE** [feross/webtorrent-desktop#430]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.3.3
**What operating system and version?**
ubuntu gnome

**Comment by NIXOYE** [comment]
after clicking at the download multiple time a menu appeared that said open folder. not really sure how i made it appear. Apparently it downloads to your reguelar /home/user/download folder.

**Comment by bofinbabu** [comment]
So far I've seen no save-to option you are talking about and in windows it's downloading to the default 'Downloads' directory.

**Comment by feross** [comment]
@NIXOYE That's correct. Files go in the Downloads folder at the moment.
