### ISSUE TITLE
.MVK file (in CAPS) not recognized

### ISSUE THREAD

**Issue by MoOx** [feross/webtorrent-desktop#433]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.3.3 (0-a5366c3)

**What operating system and version?**

OS X 10.11

**What did you do?**

I downloaded a torrent which contains a folder with a file extension with CAPSLOCK (eg: .PNG, .MKV etc)

**What did you expect to happen?**

To be able to have (and so press) the red Play button.

**What actually happened?**

I didn't have a red button to play the MKV file.

**Comment by ungoldman** [comment]
Thanks for the bug report! We should coerce file type strings to lowercase if we're not already doing that.

**Comment by ungoldman** [comment]
@MoOx guessing you mean `.MKV` in the title?

**Comment by MoOx** [comment]
.MKV ine the filename (no ext in the torrent folder name)

**Comment by grunjol** [comment]
fixed in #434
