### ISSUE TITLE
Test migration code

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#448]
Getting fs.read errors on Windows because of buggy migration code. The `torrentPath` is `..\\static\\bigBuckBunny.torrent` on Windows, not `bigBuckBunny.torrent` as expected. 

Before shipping v0.4, we need to thoroughly test upgrading from v0.3.3.

**Comment by dcposch** [comment]
Found out why this happened. We actually changed the format *four times*:

* In the beginning, we were using absolute paths for the default torrentPaths, eg '/Users/dc/.config/WebTorrent/static/bigBuckBunny.torrent'
* Then, [I changed it](https://github.com/feross/webtorrent-desktop/commit/5a2c76c7dbacdbc06eaf11fe5ef212440fbe9f4a#diff-bf2069ebc9be5c7b89ea54645653839f) to use janky relative paths, eg '../static/bigBuckBunny.torrent'
* Then, [you changed it](https://github.com/feross/webtorrent-desktop/commit/a6688980225f3a20489860989ba06d02f4eae23d#diff-bf2069ebc9be5c7b89ea54645653839f) to compute those janky paths at runtime. New configuration files after that change would say torrentPath is eg 'bigBuckBunny.torrent'
* Finally, now we're getting rid of `torrentPath` altogether.

...so the migration has a lot of cases to handle
