### ISSUE TITLE
Add a volume gui and mouse functionality

### ISSUE THREAD

**Issue by mika76** [feross/webtorrent-desktop#456]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
3.3

**What operating system and version?**
OSX 10.11.4

**What did you do?**
Watched a movie

**What did you expect to happen?**
I expected to be able to change the volume and see the volume change like VLC

**What actually happened?**
Nothing. I can see volumn can be changed via keyboard shortcuts, but it would be much nicer to see at what level it is and allow for mouse and swipe functionality

**Comment by grunjol** [comment]
Already implemented in #330 should be available in next release.
Regarding level, you mean like a VLC's OSD o just the slider like in the mentioned PR?

**Comment by mika76** [comment]
The VLC comment was just an example, the way it's done in #330 seems great, thanks.
