### ISSUE TITLE
Not seeding in place (content duplication)

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#457]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
master tree
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
* Open application
* Drag and drop single media file from some path ie `/home/user/Videos/test/file.mp4`
* Accept Torrent creation on `/home/user/Videos/test`

**What did you expect to happen?**
`file.mp4` should start seeding in place 
**What actually happened?**
A new `file.mp4` is created in parent directory, in the example: `/home/user/Videos/file.mp4`

**Comment by feross** [comment]
Yes, I noticed this too. I think the cause is all the code duplication when a torrent is created. We should just use `createTorrent.parseInput` instead of reimplementing all that here.
