### ISSUE TITLE
Airplay button not appearing

### ISSUE THREAD

**Issue by johndbritton** [feross/webtorrent-desktop#458]
#**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

`0.3.3 (0-a5366c3)`

**What operating system and version?**

`OSX 10.11.4`

**What did you do?**

Stream any video

**What did you expect to happen?**

See a button to play with Airplay

**What actually happened?**

The Airplay button is missing, but I am able to connect to my Apple TV via Airplay with screen sharing in OSX.

**Comment by feross** [comment]
We're in the process of replacing the current Apple TV npm package with a new one by @watson, so I'm going to close this issue since it's related to the old npm package.
