### ISSUE TITLE
Casting to ChromeCast not possible, feature missing.

### ISSUE THREAD

**Issue by digisign76** [feross/webtorrent-desktop#459]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.3.3 (0-a5366c3)
**What operating system and version?**
OS X El Capitan 10.11.4 (15E65)
**What did you do?**
Play an item while it was finished/still downloading 
**What did you expect to happen?**
The ChromeCast button to appear
**What actually happened?**
No ChromeCast button, not able to stream it to my device.

![screenshot](https://cloud.githubusercontent.com/assets/19207894/15045446/1af49cce-130d-11e6-8e6e-5d0712b45534.PNG)

**Comment by feross** [comment]
Chromecast devices are supported. This must be a temporary fluke on your network. Try restarting your Chromecast and/or the WebTorrent app.

Does casting to the Chromecast from another device work?

**Comment by digisign76** [comment]
It's working on the very same device: same Mac, same connection, same router, same chrome cast device (NexusTV) not rebooting anything, it works like a charm. Worked before with WebTorrent Desktop (same version), is not working now.

**Comment by feross** [comment]
Can you restart WebTorrent Desktop and see if it works?

**Comment by digisign76** [comment]
Just did. Nothing happened, no way to stream it, feature is still missing, as you can see from the screenshot. Also tried with Chrome on my Mac and iPhone, both working perfectly. 
![01](https://cloud.githubusercontent.com/assets/19207894/15047688/94cb4376-1318-11e6-8ad3-ae2981994e9e.jpg)

**Comment by feross** [comment]
@digisign76 The chromecast icon only shows up when a Chromecast is detected on your network. So this means that detection is failing.

What kind of Chromecast do you have? Can you share the software/firmware version information?

Instructions for where to find the version info can be found [here](https://support.google.com/chromecast/answer/3210071?hl=en) under "How do I know my firmware version?"

**Comment by digisign76** [comment]
Thanks for your reply. Point is the ChromeCast device was active, working and discoverable by all the others devices, but not by web torrent Desktop client. The ChromeCast in my case is the Google Nexus TV (Asus made, but Google specs), and works pretty well, better than the ChromeCast dongle I had before. Anyway, later yesterday, with no reason at all, web torrent started to work again properly and I was able to stream on my ChromeCast. My guess is that, while downloading few items, especially if the bandwidth get seriously high, Webtorrent client stops showing you the Cast Button. You can still play your download in progress but not cast them, not even if they are completed.

I might be wrong but everything was back to normal not after many restart, but only when all the downloads were completed.

**Comment by feross** [comment]
@digisign76 Thanks for sharing your theory about the cause of the missing Chromecast icon. I think you might be right. See https://github.com/feross/webtorrent-desktop/issues/362

@mafintosh -- does that seem reasonable to you? Could having a saturated network connection cause Chromecasts on the local network to not be detected?

**Comment by digisign76** [comment]
@feross By the way, the network was not saturated the I had that issue: I have tried with other devices and Chromecast was totally discoverable and available... it actually worked.

**Comment by delgotit** [comment]
I had similar issue so I switched chromecast and my computer from 5Ghz to 2.4Ghz restarted webtorrent and saw the icon.
