### ISSUE TITLE
Cannot create torrent from file

### ISSUE THREAD

**Issue by furstenheim** [feross/webtorrent-desktop#464]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.3.3
**What operating system and version?**
Linux, Ubuntu 14.04
**What did you do?**
In the menu I selected "Create New Torrent..."
**What did you expect to happen?**
To be able to add either a file or a folder
**What actually happened?**
I could only add a folder.

This is an issue with [electron](https://github.com/electron/electron/blob/master/docs/api/dialog.md) (or maybe Linux), a dialog cannot be both "openFile" and "openDirectory": 

> Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be shown.

**Comment by feross** [comment]
Looks like Atom solved this by offering two menu options on Linux and Windows.

https://github.com/atom/atom/pull/1856

**Comment by feross** [comment]
Fixed in #465 by @furstenheim
