### ISSUE TITLE
In video playback mode, full screen button asks for subtitles

### ISSUE THREAD

**Issue by watson** [feross/webtorrent-desktop#467]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
master (b39566f)

**What operating system and version?**
OSX 10.10.5

**What did you do?**
Clicked play on a video torrent, then after playback started I clicked the full screen icon in the lower right corner of the window

**What did you expect to happen?**
I expected the video to play in full screen

**What actually happened?**
App asked where to find subtitles

**Comment by feross** [comment]
Yes, I noticed this recently too.

**Comment by feross** [comment]
Figured out the cause of this. The captions icon is actually really wide for some reason. Here's what it looks like when no explicit width is set.

<img width="181" alt="screen shot 2016-05-12 at 17 42 56" src="https://cloud.githubusercontent.com/assets/121766/15234685/0e9c1aa4-1869-11e6-9709-7a94ceab8d72.png">

So the icon character overflows out of the `<i>` tag and over the other nearby icons.

I wonder why this particular icon is different. I'll open an issue on the Google Material icons repo and send a PR with a solution in a moment.

**Comment by feross** [comment]
Issue filed with Google: https://github.com/google/material-design-icons/issues/390

**Comment by feross** [comment]
PR: https://github.com/feross/webtorrent-desktop/pull/499

**Comment by feross** [comment]
The icon name is "closed_caption", not "closed_captions"
http://jsbin.com/fenejob/1/edit?html,output

The extra space we're seeing is the icon font rendering the 's', which renders as nothing.
