### ISSUE TITLE
No audio while streaming torrent in webtorrent

### ISSUE THREAD

**Issue by anonymousguyx** [feross/webtorrent-desktop#468]
**What version of WebTorrent Desktop?**
Version is not defined, I am using webtorrent in Linux and downloaded today.
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
I have added a movie and try to watch it while downloading using webtorrent but there is no audio, when I open it in VLC, the audio is perfectly comes.

**Comment by feross** [comment]
Duplicate of https://github.com/feross/webtorrent-desktop/issues/350 Will be fixed in next release.

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
