### ISSUE TITLE
error when building in windows 7, what am I doing wrong?

### ISSUE THREAD

**Issue by visorq** [feross/webtorrent-desktop#477]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'package',
> 1 verbose cli   '--win32' ]
> 2 info using npm@1.4.28
> 3 info using node@v0.10.36
> 4 verbose node symlink C:\Program Files\nodejs\\node.exe
> 5 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
> 6 info prepackage webtorrent-desktop@0.3.3
> 7 info package webtorrent-desktop@0.3.3
> 8 verbose unsafe-perm in lifecycle true
> 9 info webtorrent-desktop@0.3.3 Failed to exec package script
> 10 error webtorrent-desktop@0.3.3 package: `npm install && npm prune && npm dedupe && node ./bin/package.js`
> 10 error Exit status 8
> 11 error Failed at the webtorrent-desktop@0.3.3 package script.
> 11 error This is most likely a problem with the webtorrent-desktop package,
> 11 error not with npm itself.
> 11 error Tell the author that this fails on your system:
> 11 error     npm install && npm prune && npm dedupe && node ./bin/package.js
> 11 error You can get their info via:
> 11 error     npm owner ls webtorrent-desktop
> 11 error There is likely additional logging output above.
> 12 error System Windows_NT 6.1.7601
> 13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package" "--win32"
> 14 error cwd C:\!JS\webtorrent-desktop-0.3.3
> 15 error node -v v0.10.36
> 16 error npm -v 1.4.28
> 17 error code ELIFECYCLE
> 18 verbose exit [ 1, true ]

**Comment by feross** [comment]
The `&&` unix-ism is not supported on Windows. I use Git Bash for Windows (https://git-scm.com/download/win) and it works fine there. Give that a try.

**Comment by visorq** [comment]
I get a lot of warnings. Maybe version of NPM is not suitable? Here is the complete build log http://pastebin.com/raw/jfwupM5S

**Comment by feross** [comment]
Yeah, your node version is really old. I recommend downloading Node v4 from here: https://nodejs.org/en/

**Comment by visorq** [comment]
Again the error

My actions
1. Remove the old version of nodeys
2. Install 4.4.4
3. Start your Git
4. Went to the directory webtorrent-desktop-0.3.3
5. npm install
6. npm run package --win32
7. received a warning
8. got an error

LOG: http://pastebin.com/raw/txE4C1hT

**Comment by feross** [comment]
Nice -- you got further than last time.

All the warnings that you see are harmless and expected -- don't worry about those! ;)

The last error is real, however. It's caused by the webtorrent-desktop directory that you're inside of not being a git repo. That command `git rev-parse --short HEAD` is used by the build script to generate a hash to use in the version part of the app's "About WebTorrent" window. However, I have a PR that will remove -- will send it today.
