### ISSUE TITLE
VLC Play Support

### ISSUE THREAD

**Issue by saru95** [feross/webtorrent-desktop#483]
Navigating through the OSX app I couldnt find an option to play the media through VLC . This comes in handy when the audio is too low or video is in some weird format .
Is this being worked upon ? Would it be fine if I work on this ?

**Comment by karimdag** [comment]
+1

**Comment by rom1504** [comment]
see #368 and https://github.com/feross/webtorrent-desktop/pull/424

**Comment by feross** [comment]
Yep, implemented. Will be released very soon.

**Comment by aurimus** [comment]
The menu in VLC does not appear except the context menu.
