### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by karimdag** [feross/webtorrent-desktop#484]
**What version of WebTorrent Desktop?**
Version 0.3.3

**What operating system and version?**
Windows 10

**What did you do?**
Dragged and dropped a magnet link

**What did you expect to happen?**
The torrent would start to download.

**What actually happened?**
Nothing. Didn't work, Had to manually to File -> Open torrent address and past the magnet link.

**Comment by feross** [comment]
Ah, dragging and dropping magnet links is not supported yet. See #284. Just use paste instead. `Command+V` on OS X and `Control+V` on Windows/Linux.

**Comment by codealchemist** [comment]
Hey @karimdag, we have some good news in #284.
:)
