### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by karimdag** [feross/webtorrent-desktop#485]
**What version of WebTorrent Desktop?**
0.3.3

**What operating system and version?**
Windows 10

**What did you do?**
started streaming a 720p torrent.

**What did you expect to happen?**
It would work normally.

**What actually happened?**
Sound didn't work.

**Comment by feross** [comment]
This means your file likely uses the AC3 (Dolby) audio codec -- which isn't playable by Chromium (which is what WebTorrent Desktop uses under the hood).

The next version of WebTorrent Desktop (will be released in a few days) will detect these types of files and offer to open them in VLC for you.

See #350 for more background.

**Comment by feross** [comment]
**If you want to see AC3 support in WebTorrent Desktop, then star this issue:** https://bugs.chromium.org/p/chromium/issues/detail?id=611517

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**

**Comment by Flet** [comment]
@feross can you add a "chromium issue" label? it might be nice to mark these
