### ISSUE TITLE
Please add Subtitle support with subtitle options.

### ISSUE THREAD

**Issue by monway** [feross/webtorrent-desktop#496]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
any
**What operating system and version?**
OSX 10.11.4
**What did you do?**
opened the application didn't see any subtitle option on the streaming service. that's extremely important feature.
**What did you expect to happen?**
I kinda expected subtitles option since it's pretty much standard now.
**What actually happened?**
just a player without subtitle support. please add that feature Thank you.

**Comment by feross** [comment]
This has already been implemented! It will be released later tonight as WebTorrent v0.4.0.

**Comment by monway** [comment]
Thank you so very much. It is very appreciated.
