### ISSUE TITLE
Fail to open magnet link

### ISSUE THREAD

**Issue by ianjennings** [feross/webtorrent-desktop#497]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.3.3

**What operating system and version?**

Windows 10 32 x64
node v5.11.1

**What did you do?**

Failed to install from prebuilt package (#491)

* download 0.3.3 release from GitHub releases
* npm install && npm start
* click on magnet link (magnet:?xt=urn:btih:02767050e0be2fd4db9a2ad6c12416ac806ed6ed&dn=tears_of_steel_1080p.webm&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io)
* windows asks to open electron
* screenshot below displayed as error

**What did you expect to happen?**

Torrent file loaded and streamed

**What actually happened?**

![screenshot 6](https://cloud.githubusercontent.com/assets/318295/15234794/3026d12c-186a-11e6-971b-0d3a889f7a2b.png)

**Comment by ianjennings** [comment]
Pasting the magnet link works correctly

**Comment by feross** [comment]
I figured out what was causing this. If you `git pull && npm install` and try again it should work now. If you're curious, the PR that fixes it is here: https://github.com/feross/webtorrent-desktop/issues/508
