### ISSUE TITLE
Release WebTorrent Desktop v0.4.0

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#500]
Hey WebTorrent Desktop collaborators and GitHub watchers!

I want to release WebTorrent v0.4.0 tonight. I could use your help to test the code that's on `master` right now.

```js
git clone https://github.com/feross/webtorrent-desktop.git
cd webtorrent-desktop
npm install
npm start
```

Please report any bugs you find! If all looks good, this release is going out in ~6 hours.

(This one took a while! In the future, we need to a do better job of keeping `master` in a shippable state at all times.)

**Comment by grunjol** [comment]
In linux app is not starting using master
```
Uncaught Exception:
TypeError: template[0].unshift is not a function
    at getAppMenuTemplate (/home/grunjol/workspaces/wt/webtorrent-desktop/main/menu.js:391:17)
    at Object.init (/home/grunjol/workspaces/wt/webtorrent-desktop/main/menu.js:27:45)
    at EventEmitter.<anonymous> (/home/grunjol/workspaces/wt/webtorrent-desktop/main/index.js:62:10)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
```
I think unshift should be applied to submenu, not template

**Comment by iShift** [comment]
On OS X app have name Electron with Electron logo

**Comment by feross** [comment]
@iShift Thanks for checking out the app. That is normal if you're running the version on `master`. OS X gets the app name from the `Info.plist` file which is modified when the app is packaged.

**Comment by feross** [comment]
Okay, for real this time. Last call! Lots more PRs were merged this morning. Going to wait another ~1 hour to allow some more testing, then will release.

@dcposch @grunjol @ungoldman @Flet @jhiesey @mafintosh If you guys have some free time, please give the code on `master` a try and make sure it works for you!

**Comment by grunjol** [comment]
Just sent a PR to fix multiple subtitles label for the same language #512

**Comment by ungoldman** [comment]
taking a look 👀

**Comment by ungoldman** [comment]
Looking really good! I was unable to break it.

✌️😁👍 💬 💯

**Comment by grunjol** [comment]
Tested in Ubuntu 16.04 and Debian 7.  :+1:
The only visible issue i found, i sent PR #512 to fix it

**Comment by feross** [comment]
Thanks for testing @ungoldman and @grunjol!

**Comment by yciabaud** [comment]
The linux package is not available on the website: https://github.com/feross/webtorrent-desktop/releases/download/v0.4.0/WebTorrent-v0.4.0-linux.zip

**Comment by yciabaud** [comment]
OK this is a website issue, I guess you will update the website with all the new platforms :)

**Comment by feross** [comment]
@yciabaud Thanks for letting me know -- saw your IRC message yesterday and fixed it already ;)

**Comment by feross** [comment]
WebTorrent v0.4 is released!

**Comment by feross** [comment]
You all should take a look at the changelog for this version: https://github.com/feross/webtorrent-desktop/releases/tag/v0.4.0

It's insane how much progress we've made! Such a featureful release!
