### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by anazhd** [feross/webtorrent-desktop#516]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.4.0

**What operating system and version?**
Windows 10

**What did you do?**
Trying to use webtorrent-desktop as usual

**What did you expect to happen?**
Video plays like usual, in this case, most of it is .mkv video and some .avi video

**What actually happened?**
Playback Error, sometimes it says audio unsupported, sometimes video unsupported. It will ask me to install VLC for the codec, and VLC is already installed long before webtorrent-desktop. On previous version 0.3.3, it will play the video directly. 

I did tried the same torrent using different version of webtorrent-desktop ( 0.3.3 and 0.4.0 respectively ). On 0.3.3, it works just fine but not on 0.4.0.

**Comment by dcposch** [comment]
Sorry, this sounds like a regression I caused.

> most of it is .mkv video and some .avi video
> On 0.3.3, it works just fine but not on 0.4.0.

Really? I'm pretty sure 0.3.3 doesn't support the AVI container.

* Do you have an example of a mkv file where you run into this problem? Copyright unencumbered files only, please!
* There may also be a bug in https://github.com/feross/vlc-command if VLC is already installed, but you're still being prompted to install it.

**Comment by feross** [comment]
Hey @anazhd, you said on version 0.3.3 that the video played directly. Did the audio work?

**Comment by anazhd** [comment]
@dcposch @feross sorry for late reply, yes the audio did work. There's no problem with any video I tried to play.

for the .avi, I did not tried it on 0.3.3, but on 0.4.0. I did not know it's unsupported. Yet, .mkv still, some are working and some are not. 

Too bad, I can't share the example as it's copyrighted material.
