### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by anazhd** [feross/webtorrent-desktop#517]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.4.0

**What operating system and version?**
Windows 10

**What did you do?**
Play video like usual

**What did you expect to happen?**
Video appears like usual

**What actually happened?**
Only audio can be heard. Video goes blank.

**Comment by dcposch** [comment]
Do you have an example of a video file where you run into this problem?

Copyright unencumbered files only, please

**Comment by anazhd** [comment]
@dcposch too bad, example video is copyrighted material. I will try to find other video to replicate this problem.
