### ISSUE TITLE
Clicking magnet link / opening .torrent file does nothing if player is open

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#523]
Introduced in v0.4.0.

**Comment by dcposch** [comment]
What is it supposed to do? If we added it to the torrent list, it would still look like it's doing nothing, sincd the torrent list isn't visible when you're in the player.

**Comment by feross** [comment]
I think we should call `backToList()`. We should always do what the user expects, and if they click a magnet link or open a .torrent file, they will expect to see WebTorrent add it.

We already plan on remembering the video position -- there's another issue for that -- so this will make it less disruptive if they end up wanting to resume what was playing before.
