### ISSUE TITLE
Opensubtitle integration [feature request]

### ISSUE THREAD

**Issue by postadelmaga** [feross/webtorrent-desktop#525]
Sorry I'm not sure how to 'tag' this as a request ...

It will be nice to have an integration with opensubtitle and if possible search by hash/title as this vlc extension do : https://github.com/exebetche/vlsub

**Comment by dcposch** [comment]
For now, we want to stay neutral and not integrate with any third party centralized services.

See https://github.com/feross/webtorrent-desktop/issues/281#issuecomment-219152938

**Comment by rom1504** [comment]
Having webtorrent desktop optional plugins might be interesting though. If it doesn't bring too much complexity anyway.
