### ISSUE TITLE
Option to use a third-party media player

### ISSUE THREAD

**Issue by chinabala** [feross/webtorrent-desktop#531]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.4.0
**What operating system and version?**
Mac OS 10.10
**What did you do?**
Audio not supported, switch to VLC
**What did you expect to happen?**
Using VLC with .ass subtitle file
**What actually happened?**
Some reason my VLC don't work on some Chinese .ass file. Wondering if webstorrent-desktop could allow users to change default VLC to other preferred media player?

**Comment by feross** [comment]
Which other media player do you use?

**Comment by chinabala** [comment]
I'm using MPlayerX on Mac. And I guess other users may using different player on their own preference. That'd be really nice if user can go to WebTorrent's Setting page and port stream to supported media player.

**Comment by feross** [comment]
This is implemented in #682

**Comment by feross** [comment]
Fixed by #682, will be released in WebTorrent Desktop v0.12.

Note @chinabala, you're using v0.4 which has a broken auto-updater, so you will need to update manually.
