### ISSUE TITLE
Subtitle auto-selection bug

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#534]
*Moved from @grunjol's comment here: https://github.com/feross/webtorrent-desktop/pull/520#issuecomment-219461241. I haven't verified this behavior myself.*

---

My machine is in English.

I added the subs manually in this order, each one individually

First test

Start playing video
Add Portuguese => PT plays
Add French => FR plays
Add German => FR keeps playing
Second test

Start playing video
Add French => FR plays
Add German => DE plays
Add Portuguese => DE keeps playing
I dont know why the second is added and displayed buy not the third, and no matter the order the second is picked if no matching languages.

I agree with you, If you add a lot of subtitles you need to select which one to show, and its fine to try to select the OS-matching one. But if you add a new one, I expect that one to be selected regardless the OS language you are running.

**Comment by dcposch** [comment]
Fixed in #534

**Comment by grunjol** [comment]
Works great! thanks @dcposch
