### ISSUE TITLE
Occasional packager error

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#536]
I get this error occasionally when packaging the Linux build.

```
ENOTEMPTY: directory not empty, rmdir '/Users/feross/code/webtorrent-desktop/dist/nbd4302'
```

@grunjol Ideas?

**Comment by c0b41** [comment]
@feross before rm -rf ./dist

**Comment by feross** [comment]
@c0b41 That's already part of the build script. First thing that we do.

**Comment by grunjol** [comment]
I will check it today

**Comment by grunjol** [comment]
fixed in nobin-debian-installer 0.0.10

**Comment by grunjol** [comment]
is greenkeeper working? I mean, i won't send PR if GK does it.

**Comment by feross** [comment]
@grunjol I removed Greenkeeper from all the repos I have access to because it was too noisy and many contributors complained. I opened an issue asking them to support email notifications (like Travis) instead of opening PRs, as an option. Once they add that, I'll re-enable it.

**Comment by feross** [comment]
Nice fix, btw! I'll send the PR!
