### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#539]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.5.1

**What operating system and version?**

OS X 10.11.5

**What did you do?**

Open the app, look at developer console

**What did you expect to happen?**

No errors.

**What actually happened?**

"Uncaught TypeError: Cannot read property 'update' of undefined"

**Comment by furstenheim** [comment]
It seems that 'leave-full-screen' (window.js:118) is triggered by electron before the application has init and this tries to update vdom before it is defined
