### ISSUE TITLE
Torrents change position in the list

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#546]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

`master`

**What did you do?**

Create a torrent, it gets added to the top of the list. Restart the app.

**What did you expect to happen?**

The torrent should remain at the top of the list.

**What actually happened?**

The torrent is now at the bottom of the list.

**Comment by feross** [comment]
cc @dcposch

**Comment by dcposch** [comment]
I can't reproduce this. Whenever I add a torrent, then quit and restart WebTorrent, the new torrent stays at the top of the list.

**Comment by feross** [comment]
I can't reproduce this either anymore.
