### ISSUE TITLE
Torrents losing data; Downloaded 350MB then it goes down to 347MB

### ISSUE THREAD

**Issue by AmbrociousXP** [feross/webtorrent-desktop#550]
**What version of WebTorrent Desktop?** 0.5.1 (0.93.4)

**What operating system and version?** Windows 7 x64

**What did you do?** Tried to download a torrent.

**What did you expect to happen?** The torrent to download.

**What actually happened?** I noticed that when downloading some torrents, I will have downloaded a certain amount in MB but then it will actually REVERSE in how many MB that I have downloaded and go back up, and then back down again. The torrent which is downloading at nearly 1.7 MB per second is reversing in the amount in which I have downloaded, the torrent never finishes.

**Comment by AmbrociousXP** [comment]
**UPDATE:** Stopping the torrent and then restarting it seems to have fixed this weird loop of data.

**Comment by AmbrociousXP** [comment]
OK so I was wrong. It's still doing this. It seemed to fix after I restarted it but it kept looping back, going from a higher amount of megabytes downloaded down to a lower amount of megabytes downloaded. It won't keep downloading even though my download speed is very good. It's like a data loop. Help?

**Comment by MarshallOfSound** [comment]
@AmbrociousXP This happens sometimes in other clients when you keep downloading a bad chunk from other peers.  Does it only do this on a single torrent?

**Comment by feross** [comment]
@AmbrociousXP Can you try downloading the torrent in another client and see if you experience the same issue?

Also, can you try updating WebTorrent to the latest version v0.7.2 and see if it still occurs for you?

**Comment by feross** [comment]
Closing due to lack of response.
