### ISSUE TITLE
Remove torrent with all data

### ISSUE THREAD

**Issue by chinabala** [feross/webtorrent-desktop#560]
**What did you expect to happen?**
remove torrent and all stream data from HDD
 
**What actually happened?**
it only remove the torrent but not the stream file(s). When torrent stream list is building up on WebTorrent, it getting really hard when HDD storage is not enough and difficult to find what stream has been watched and or to locate where they are.

Can anyone bring up a function that can remove all data of a torrent/stream in once?

**Comment by demoneaux** [comment]
I think this is a good idea. Maybe a modal when people click the delete torrent button, with delete files or just delete torrent only option?

**Comment by kimo59660** [comment]
I think this is a very nice good idea.

**Comment by feross** [comment]
I think we should solve this similar to how Transmission does. Here's a proposal.

Add a right-click menu with two new items "Remove From List..." and "Remove Data File...":

![screen shot 2016-06-05 at 7 08 03 pm](https://cloud.githubusercontent.com/assets/121766/15810228/6349238a-2b51-11e6-8920-bf11c8b78e7c.png)

Clicking the "X" icon or selecting "Remove from List..." from the right-click menu should show a confirmation like this:

![screen shot 2016-06-05 at 7 07 48 pm](https://cloud.githubusercontent.com/assets/121766/15810251/77135a7a-2b51-11e6-9e8e-6cdd285507b7.png)

Selecting "Remove Data File..." from the right-click menu should show a confirmation like this:

![screen shot 2016-06-05 at 7 08 07 pm](https://cloud.githubusercontent.com/assets/121766/15810258/88a8b960-2b51-11e6-8518-cd41ee512734.png)

This way, the default is safe -- we don't delete files unless the user explicitly selects that option.

Thoughts?

**Comment by dcposch** [comment]
We only need the "transfer is active" warning when a file hasn't finished downloading yet. (I don't think it would be that bad to just delete right away, with no modal dialog.)

**Comment by dcposch** [comment]
Done, w/out dialogs for now: #641
