### ISSUE TITLE
H.265 video playback

### ISSUE THREAD

**Issue by soofuzz** [feross/webtorrent-desktop#561]
Hey was just testing this out on x265 (HEVC) video torrent but i get a black screen on playback. Does the player not support x265? Unless there's a way to stream out onto an external player like mpv.

**Comment by feross** [comment]
This is fixed now, thanks to https://github.com/feross/webtorrent-desktop/issues/564. You'll now see a message about using VLC when a HEVC video is detected.

This will go out in the next release of WebTorrent (v0.6).

**Comment by jakop345** [comment]
Looks like there is x265 codec support in chromium dev builds.
https://github.com/henrypp/chromium/releases

**Comment by feross** [comment]
@jakop345 If that's true, then I guess we should get support for it automatically when we update Electron?

**Comment by demoneaux** [comment]
I think that's a custom build of Chromium specifically enabling support for additional codecs. The default Chromium build used by Electron probably won't have it enabled.

**Comment by feross** [comment]
Makes sense. I don't think Chrome wants to support H.265, and I don't blame them.
