### ISSUE TITLE
Remember volume level

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#574]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.5.1 (0.94.0)
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
* Play any torrent
* Adjust volume to 0.5 (50%)
* Go back to torrent list
* Go forward (or select a new torrent)

**What did you expect to happen?**

* Volume should be 0.5 (50%)

**What actually happened?**
* Volume is 1.0 (100%)

**Comment by grunjol** [comment]
IMHO, volume level be a global value

**Comment by feross** [comment]
Fixed by @furstenheim's PR #600
