### ISSUE TITLE
Big radio buttons in subtitle selector

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#576]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.0
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
* Download package from releases
* Update existing production version
* Run a video
* Add a subtitle
* Subtitle is loaded
* Click on subtitle menu

**What did you expect to happen?**

Classic menu with radio buttons

**What actually happened?**
![image](https://cloud.githubusercontent.com/assets/6145761/15504593/13657518-2196-11e6-9f62-7dd28dca3081.png)

**Comment by feross** [comment]
Confirmed.
