### ISSUE TITLE
Torrent file / Magnet links dont load after update to 0.6.0

### ISSUE THREAD

**Issue by djgenesis** [feross/webtorrent-desktop#579]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.0
**What operating system and version?**
Windows 10 (64)
**What did you do?**
Changed save directory and then clicked magnet link / opened torrent file from chrome
**What did you expect to happen?**
Load/Start the torrent
**What actually happened?**
Doesn't start/load any magnet/torrent file (webtorrent desktop remains empty)

**Comment by djgenesis** [comment]
Tried same torrent with 0.6.0 on another laptop (windows 10 as well)... opens torrent and downloading torrent info forever...
Downgraded to 0.5.1... everything works fine again.

**Comment by feross** [comment]
@djgenesis Were you seeding files from WebTorrent in the browser? For example, using a site like https://instant.io or https://btorrent.xyz ?

We disabled support for WebRTC web peers in v0.6.1 on Windows as a temporary hack. It will be added back in v0.7.0.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

Being able to see that output would help us out very much. Thanks.
