### ISSUE TITLE
"Autoplay last added after downloading X%" option in preferences

### ISSUE THREAD

**Issue by djgenesis** [feross/webtorrent-desktop#580]
Suggestion... I believe a great option would be to be able to choose to automatically start playing the "last added" (if it contains a playable file) after downloaing X% of total. I suggest percentage and not MBs as (for example) 5 MBs could be 1 second or 10 minutes depending on compression. It could  be deactivated by default with a specific value (ex. 1% - ie. "immediately" or 5% etc) and be able to activate it and change the percentage through drop down. No more than 2-3 options. Would suggest 1,5 and 10% for fast,medium and slow connections respectively. For example I sync at 48MBPs and 1% is enough to start watching. This would make it more of a "player" than a torrent "client". Food for thought...

**Comment by feross** [comment]
WebTorrent Desktop already lets you click Play and start the download with just a few percent downloaded.

If you're on a really fast connection, it is possible that the torrent engine process is using 100% CPU to download and hash the content it's receiving from the network, so it's too busy to stream at the same time. Could be that's what's happening.
