### ISSUE TITLE
Duplicate torrent/magnet can be added if torrent is stopped

### ISSUE THREAD

**Issue by mathiasvr** [feross/webtorrent-desktop#581]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.0
**What operating system and version?**
OS X 10.11.5
**What did you do?**
Add the same torrent or magnet after stopping the download
**What did you expect to happen?**
Get duplicate error message (as is the case when torrent is downloading)
**What actually happened?**
The torrent was added again (twice in list)

**Comment by feross** [comment]
Thanks, I was just going to post this issue.

**Comment by feross** [comment]
Fixed by @mathiasvr's PR #593!
