### ISSUE TITLE
web-torrent not functional on mac OSX 

### ISSUE THREAD

**Issue by dearfrankg** [feross/webtorrent-desktop#583]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.0 
**What operating system and version?**
OSX latest
**What did you do?**
Clicked on magnet link
**What did you expect to happen?**
Usually opens it in web-torrent
**What actually happened?**
web-torrent app screen is a solid grey color with nothing on it
no buttons except the min, max, close

**Comment by feross** [comment]
Can you try to reproduce the error again. But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text there into a comment here.

Being able to see that output would help us out very much. Thanks.

**Comment by tleunen** [comment]
Same thing on my side. Grey screen, but the torrents get downloaded.
<img width="583" alt="screen shot 2016-05-25 at 7 10 27 pm" src="https://cloud.githubusercontent.com/assets/1972567/15558965/5dbfac7a-22ac-11e6-8d2b-badf07a41452.png">

**Comment by tleunen** [comment]
The first error is actually this one:
<img width="578" alt="screen shot 2016-05-25 at 7 11 45 pm" src="https://cloud.githubusercontent.com/assets/1972567/15558985/9054f5dc-22ac-11e6-9329-f45dde78d892.png">
<img width="825" alt="screen shot 2016-05-25 at 7 12 26 pm" src="https://cloud.githubusercontent.com/assets/1972567/15558995/a5768e3a-22ac-11e6-948a-358959834c45.png">

**Comment by feross** [comment]
@tleunen Thank you -- this was very helpful. I'm working on a fix.

**Comment by tleunen** [comment]
Looks like an entry was corrupted in my config file. Removing it solved the issue ;)

**Comment by feross** [comment]
That works. But that entry was actually expected. We need to handle it in the migration code.
