### ISSUE TITLE
Keyboard capture of Space and ESC is super aggressive

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#585]
g**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.6.0

**What operating system and version?**

OS X 10.11.5

**What did you do?**

Try to use of an OS shortcut with `ESC` or `Space` while WebTorrent Desktop is running.

**What did you expect to happen?**

OS shortcuts should work.

**What actually happened?**

Any system-wide OS shortcut that makes use of `ESC` or `Space` does not work if WebTorrent Desktop is the active window, because it is captured by the app and the `electron-localshortcut` package.

**Comment by dcposch** [comment]
I assume the fix is to capture those keys only when we're in the player view and it's the active window

**Comment by feross** [comment]
Nah, that's not the solution. The solution is to get make `ESC` and `Space` into menu item accelerators (shortcuts).

For Play, let's get rid of `CMD+P` and just have `Space`.

For `ESC` let's just add an item called "Go Back" to the View menu.

**Comment by dcposch** [comment]
Sure, but the Play one should still be disabled unless you're in the player. The Go Back will be enabled/disabled the same as the back button

**Comment by feross** [comment]
The Play/Pause menu item that's already there already gets enabled/disabled as the user enters/leaves the player.

For the back button, up to you. But I think it's fine to just leave it always enabled and it can just no-op. Otherwise we need to add events to let the main process know about the state of LocationHistory which IMO is more trouble than it's worth.

**Comment by dcposch** [comment]
While I'm at it, do you want to get rid of this as well?

    localShortcut.register('CmdOrCtrl+Shift+F', menu.toggleFullScreen)

**Comment by feross** [comment]
@dcposch Sure. It was a shortcut I was familiar with from Chrome, but I just checked and it does something different now.

I say we remove it. The standard OS fullscreen shortcut should be sufficient! Now we can axe that dependency!

**Comment by dcposch** [comment]
Done
