### ISSUE TITLE
Chromecast + Subtitles not working

### ISSUE THREAD

**Issue by brai4u** [feross/webtorrent-desktop#602]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.6.1 (0.94.0)
**What operating system and version?**
Windows 10
**What did you do?**
Playing a torrent
**What did you expect to happen?**
Views subtitles on chromecast
**What actually happened?**
I can't see any subtitle

**Comment by demoneaux** [comment]
Duplicate of #530.

**Comment by feross** [comment]
Yep, planned feature.
