### ISSUE TITLE
When webtorrent starts as a magnet-link handler, torrent is downloaded into /tmp/webtorrent/

### ISSUE THREAD

**Issue by J08nY** [feross/webtorrent-desktop#606]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.5.1 (0.93.4)

**What operating system and version?**
Linux Armitage 4.5.0-kali1-amd64 #1 SMP Debian 4.5.3-2kali1 (2016-05-09) x86_64 GNU/Linux
kali-rolling

**What did you do?**
Added a torrent from a magnet link opened in firefox.

**What did you expect to happen?**
The torrent to be downloaded to /home/$user/Downloads/ as usual.

**What actually happened?**
The torrent started downloading into /tmp/webtorrent/?info-hash?/

This only happens to the first torrent(the one from the magnet link that started webtorrent). I think this is undefined behavior. Other torrents added after webtorrent starts/after manually starting webtorrent, are correctly downloaded into /home/$user/Downloads.

Is there any config/a way to set the default torrent directory in webtorrent-desktop on linux? It would be really great to have some preferences to change in webtorrent-desktop. (Default download directory, up/down speed limits, ...)

**Comment by feross** [comment]
If you update to the latest version of WebTorrent Desktop (0.6.1) you'll get a preferences menu that let's you set the download folder.

As for the bug you're reporting, I've seen that happen occasionally. Looking into it now.

**Comment by feross** [comment]
PR https://github.com/feross/webtorrent-desktop/pull/613
