### ISSUE TITLE
Uncaught exception throw while trying to use function under Menu-View 

### ISSUE THREAD

**Issue by tautcony** [feross/webtorrent-desktop#608]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.1 master branch

**What operating system and version?**
 Windows 10 - 10586

**What did you do?**
Click F11 key / Menu-View-Full Screen / Menu-View-Float on Top.

**What did you expect to happen?**
In the main view, it should become fullscreen or can be set the form on top.

**What actually happened?**
show a error dialog as bellow.
![Error](https://cloud.githubusercontent.com/assets/8295052/15669379/b0679032-2752-11e6-84ac-95e8f288a4c6.png)

**Comment by feross** [comment]
Sorry about that. This was fixed in #609.
