### ISSUE TITLE
WebTorrent Desktop fails to detect VLC 64-bit

### ISSUE THREAD

**Issue by terryhau** [feross/webtorrent-desktop#616]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.1
**What operating system and version?**
Windows 10
**What did you do?**
Play video with unsupported codec.
**What did you expect to happen?**
Video to open in VLC.
**What actually happened?**
WebTorrent Desktop fails to detect VLC 64-bit, says it's not installed.

Also, could an option be added to always use VLC?

**Comment by terryhau** [comment]
I had a look at https://github.com/feross/vlc-command/blob/master/index.js.
Perhaps you need to add '.exe' to the path for Windows.

**Comment by feross** [comment]
Works on my machine with 32-bit and 64-bit VLC. Also, tested on a friend's machine and it works there too.

- What version of VLC do you have installed?
- Can you update to the latest version of WebTorrent Desktop and try again? The [latest version](https://github.com/feross/webtorrent-desktop/releases/download/v0.7.1/WebTorrentSetup-v0.7.1.exe) is v0.7.1.

**Comment by avamsi** [comment]
I have this issue too.
Using WebTorrent Desktop v0.7.2, VLC 2.2.3 64-bit on Windows 10. I even have VLC in my PATH.

**Comment by terryhau** [comment]
Just tested with 0.7.2 and still same problem.
I have VLC 2.2.3 x64 installed and have the correct registry keys.

http://i.imgur.com/CoDK9Ki.png

**Comment by feross** [comment]
@avamsi @terryhau Is your Windows account an Administrator or Standard user?

**Comment by feross** [comment]
@terryhau Let's try your suggestion of adding `.exe` to the path.

Can you help me confirm that this works for you by doing the following:

1. [Install Node.js](https://nodejs.org/en/), if you don't have it already.
2. Open the Node.js terminal and run `node --version` to confirm you're using at least version 4.0.0.
3. Install `vlc-command` by running `npm install -g vlc-command`.
4. Run `vlc-command --path` and copy-paste the path into a comment here.
5. Run `vlc-command --open` and see if VLC opens up.

Thanks! This will help a lot.

**Comment by terryhau** [comment]
That seems to work
```
C:\Users\terry>node --version
v4.4.5

C:\Users\terry>npm install -g vlc-command
C:\Users\terry\AppData\Roaming\npm\vlc-command -> C:\Users\terry\AppData\Roaming\npm\node_modules\vlc-command\cmd.js
vlc-command@1.1.1 C:\Users\terry\AppData\Roaming\npm\node_modules\vlc-command
├── winreg@1.2.1
└── run-parallel@1.1.6

C:\Users\terry>vlc-command --path
C:\Program Files\VideoLAN\VLC\vlc.exe

C:\Users\terry>vlc-command --open

[0000000000fe7bc0] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
```

**Comment by feross** [comment]
Okay, excellent news. Then the issue should be fixed for you in the next version of WebTorrent Desktop, since the fix is already in `vlc-command`!

**Comment by dcposch** [comment]
@feross this is fixed, right?

**Comment by feross** [comment]
Yes

**Comment by terryhau** [comment]
I just tested 0.8.0 and still get 'can't run VLC' error.
