### ISSUE TITLE
Custom key bindings?

### ISSUE THREAD

**Issue by avamsi** [feross/webtorrent-desktop#618]
Hey,

Great application! I use it on Windows and ctrl + alt + arrow keys are native key bindings for changing display orientation. Can you provide an option to change key bindings?

Thanks,
avamsi

**Comment by feross** [comment]
What do you mean by changing display orientation? Can you elaborate further?

**Comment by mathiasvr** [comment]
I know some Intel graphics card drivers adds this shortcut. It is used to rotate the display image, for instance if you have your monitor flipped sideways (rotated 90 degrees).

**Comment by feross** [comment]
@mathiasvr Hm, that's odd. Why would specific apps need to implement support for that shortcut? Sounds like OS-level functionality that should rotate the entire desktop display, not a single app.

**Comment by mathiasvr** [comment]
@feross I think op means that he wants to be able to change the default keybindings for stepping ('Ctrl+Alt+Left' and 'Ctrl+Alt+Right') in WebTorrent Desktop, because they don't work since the graphics card driver overrides them.

**Comment by feross** [comment]
Oh, I see. 👍 Okay, I'll change the shortcuts to `Alt+Left` and `Alt+Right` on Windows and Linux only, to match what VLC does.

That will at least help out @avamsi. In the future, I don't think we'll always be able to accommodate all user's particular setups.

**Comment by feross** [comment]
PR https://github.com/feross/webtorrent-desktop/pull/620

**Comment by avamsi** [comment]
That was quick! Thank you.

**Comment by feross** [comment]
No problem! This was released in v0.7.1.

**Comment by avamsi** [comment]
@feross What are your thoughts on having more VLC shortcuts?
For example, `f` for fullscreen; 3 sec jumps, 1 min jumps..

**Comment by feross** [comment]
@avamsi Happy to consider them on a case-by-case basis. Right now, we can't add multiple shortcuts for a single command easily until Electron adds support for that in https://github.com/electron/electron/issues/1334
