### ISSUE TITLE
Inaccurate download speed

### ISSUE THREAD

**Issue by avamsi** [feross/webtorrent-desktop#619]
I am using v0.6.1 on Windows 10.

I got curious when webtorrent-desktop reported my download speed as ~ 3 MBps
My internet connection is capped at 1 MBps and my download speed atm indeed was ~ 1 MBps as confirmed by Task Manager.

**Comment by feross** [comment]
I've seen this happen occasionally when the torrent process is using 100% CPU, or when I'm on a slow computer. I think that this condition messes up the speed calculation somehow. Not sure what the best way to fix it is.

**Comment by avamsi** [comment]
Not using 100% CPU and definitely not a slow computer.

**Comment by feross** [comment]
@avamsi Do you know if the torrent you're using contains a web seed? (Let me know if you need help determining this.)

**Comment by avamsi** [comment]
Does webtorrent-desktop show number of web seeds in download info?
As in 'Downloading from X peers and Y web seeds' -- if it does, then no.

If it doesn't, I'll get back to you in a few hours.

**Comment by feross** [comment]
We treat web seeds as normal peers at the moment. Looking forward to hearing what you find.

**Comment by avamsi** [comment]
@feross It doesn't contain a web seed. FWIW, download speed seems to be accurate now.

**Comment by feross** [comment]
@avamsi Hm, well the hunt for the source of this occasional bug continues...

**Comment by feross** [comment]
Closing it because it's not critical.
