### ISSUE TITLE
Preferences Window

### ISSUE THREAD

**Issue by ChrisMorrisOrg** [feross/webtorrent-desktop#62]
After these issues have been opened: #5, #50, #53. Maybe we should consider putting these features into preferences pane?

**Comment by feross** [comment]
Agree that we'll need preferences at some point, but we want to be judicious about what we add and not spew too much complexity too quickly.

I think a preference for #53 make the most sense to do first.

**Comment by ChrisMorrisOrg** [comment]
100% agree. Maybe we should discuss here what the primary customisation points will be, when the project matures enough.

**Comment by feross** [comment]
@ChrisMorrisOrg Want to work on an initial preferences window?

I don't think there should be any UI in the window, but just a preferences menu item like most apps have.

**Comment by ngoldman** [comment]
@feross you mean like a `File > Preferences >` type thing?

**Comment by feross** [comment]
Like this:

<img width="229" alt="screen shot 2016-03-07 at 2 30 30 pm" src="https://cloud.githubusercontent.com/assets/121766/13585548/2ea29214-e471-11e5-8774-fb257ab90830.png">

**Comment by ChrisMorrisOrg** [comment]
Sure thing! I'll work on it tonight unless someone else has already started work on it.

**Comment by ngoldman** [comment]
Not me! I say go for it @ChrisMorrisOrg

**Comment by ChrisMorrisOrg** [comment]
If nobody has started working on this. I will claim it now (sorry for the delay).

**Comment by karloluis** [comment]
Can we get a list of things we know for sure should be on the settings page. All the suggestions seem to be scattered out different tickets.

**Comment by grunjol** [comment]
Now the subtitle part is almost done I think this should be number 1 priority to do.
I will start with the basic structure based on #144 and will go from there to get a modular but simple solution

PS: assigned the issue to myself, will create a branch and periodically will ask for suggestions/reviews

**Comment by grunjol** [comment]
Questions to @feross @dcposch all:
* Should this preference be inside its own window or a 'dialog like' window?
* hardcoded preference items (big file with code and definition items) or files based( modular/pluggable config?) defined items?

**Comment by feross** [comment]
@grunjol I want to move away from the modal approach we have been using. We should use the navigation buttons (back/forward) for this kind of thing. So, I would implement this as a view in the renderer. This actually simplifies things a lot because we can avoid IPC through the main process -- the `state` object already lives in the renderer. We can also avoid managing yet another window in `windows.js`.

When `state.url` is set to `'preferences'`, that view should show up. To start, let's just have one option:

- View/edit the download path

**Comment by grunjol** [comment]
Great! I will go that way.

**Comment by grunjol** [comment]
Going with the view in the renderer navigation style, and inspired by atom's settings page this is the first iteration:
![image](https://cloud.githubusercontent.com/assets/6145761/14591167/5210d576-04e2-11e6-8cea-9c242399a966.png)

Let me know what you think about it. PR, coming soon.

**Comment by karloluis** [comment]
Looks good to me.

**Comment by feross** [comment]
This is done now in v0.6.0.
