### ISSUE TITLE
Ubuntu software center publication

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#629]
You must file this there, maybe theyll make it default.

**Comment by feross** [comment]
Are you familiar with the submission process? Last time I looked I could only find information about how to submit to their mobile software center.

I'm happy to submit it if you have a link that explains the process.

**Comment by janat08** [comment]
https://developer.ubuntu.com/en/publish/
"Ubuntu app, webapp or scope for mobile devices, sign up for free to get a MyApps account." They're doing a convergence thing from mobile to servers, where supposedly one publication fits all.

**Comment by feross** [comment]
It doesn't look it's possible to publish a .deb file to their store. I have no idea what they were thinking when making that decision... You have to use their proprietary .snap or .click format and go through a bunch of hoops including sandboxing.

I would rather focus on publishing a PPA, which would offer users an easy auto-update mechanism.

**Comment by janat08** [comment]
Sorry to have wasted your time.

**Comment by feross** [comment]
@janat08 It's all good. Thanks for the suggestion!
