### ISSUE TITLE
 Watch a video without download

### ISSUE THREAD

**Issue by kimo59660** [feross/webtorrent-desktop#630]
Hi, 
I like to know the function that I can use to play a video  (.torrent) directly without downloading.

Actually i use  : 
1 ) function addTorrent (torrentId) --> to add the file 
2) function playFile (infoHash, index) -->  index=0 to play directly the video    

and when i use addTorrent  it download the file and  no way to just watch the video

**Comment by feross** [comment]
You can't play a video without downloading the data that you need to play it. WebTorrent Desktop stores this data on the filesystem

 If you want to just keep file data in-memory, consider using the `webtorrent` package directly, which offers that option through the use of an in-memory chunk store. See the `store` option to [`client.add()`](https://github.com/feross/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-).
