### ISSUE TITLE
Select file to play

### ISSUE THREAD

**Issue by bertofer** [feross/webtorrent-desktop#635]
Hi, I think it would be nice to be able to select which file to play of the ones playable inside the torrent. I have seen in the code it now selects the larger file inside. What about some kind of modal/dropdown as the list of files to choose within?

As far I've seen, the line 846 of main renderer
```
torrentSummary.defaultPlayFileIndex = pickFileToPlay(torrentInfo.files)
```
should be removed and leave all responsibility of choosing the file to play to this modal/dropdown.

If you are ok with it, I could make a PR, as I am interested on starting to collaborate in this nice project.

PS: Glad to see some spanish-speakers around :)

**Comment by mathiasvr** [comment]
If you click on an active torrent a list of all files is shown. You can click them to play them in WebTorrent or open them in a supported viewer.

**Comment by bertofer** [comment]
Oh thanks @mathiasvr! Didn't even tried to click on the torrent, shame on me! I close this then, although seems a bit odd to open the largest file in some scenarios, I think it's a very small detail. I close this issue for now.

Cheers

**Comment by mathiasvr** [comment]
No problem, maybe the UI should display this feature more clearly?
Also you could take a look at the other issues if you are still interested in doing some work! 👍

**Comment by bertofer** [comment]
Sure, i will do that!
