### ISSUE TITLE
Downloaded installer won't launch as it's being used.

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#639]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.7.2 (0.94.3)
**What operating system and version?**
windows 8.1
**What did you do?**
Try to start .exe installer while torrenting was active
**What did you expect to happen?**
expected for istaller to work
**What actually happened?**
error message (that wasn't necesserily windows, but rather installer based) about how exe is already being used

**Comment by janat08** [comment]
In hindsight I belief I was referring to non-webTorrent installer, and blaming webtorrent for conflicting with some other app.

**Comment by feross** [comment]
Okay, thanks for letting us know that this isn't an issue with WebTorrent. Cheers!
