### ISSUE TITLE
Torrent dropdown indication icon

### ISSUE THREAD

**Issue by mathiasvr** [feross/webtorrent-desktop#645]
#635 got me thinking that it maybe should be indicated that a torrent can be dropped down. My idea is to add an arrow that is visible when hovering the torrent (like the buttons). Something like this:

![stuff2](https://cloud.githubusercontent.com/assets/8664776/16102340/ab335e7a-336e-11e6-9797-b25d8f127226.png)
![stuff1](https://cloud.githubusercontent.com/assets/8664776/16102339/a8429438-336e-11e6-97a6-6e69c85368c7.png)

Other suggestions? 😃

**Comment by dcposch** [comment]
Yeah, the UX in the torrent list needs some work.

Maybe we can start a newly added torrent expanded. That way, people will find out this feature exists when they add their first torrent.
