### ISSUE TITLE
File Path Warnings Needed

### ISSUE THREAD

**Issue by MarkIvanowich** [feross/webtorrent-desktop#646]
**What version of WebTorrent Desktop?** Version 0.7.2 (0.94.3)

**What operating system and version?** elementary OS 0.3.2 Freya (64-bit) Built on Ubuntu 14.04

**What did you do?** Start WebTorrent without mounted drive, where Download Path resides

**What did you expect to happen?** Error, Download Path does not exist, confirmation to create path or choose alternative.

**What actually happened?** Folder created in /media/user/, where files were downloaded off away from desired location

**Details** 
Obviously I am saving all my torrents to a separate drive on my PC, where the drive has to be mounted before using. Silly me, I start WebTorrent before this happens. WebTorrent happily chugs along, downloads the files, returns no warnings. I realize after the download that my drive is not mounted, and the downloaded files are in /media/mark/External_Drive1/Torrent_Downloads/ when External_Drive is not mounted. _(Please note that the incremented number may be from mounting the drive after Ubuntu sees the original path as not empty.)_

I safely moved the files to the drive, however WebTorrent still thinks the torrents reside in _Drive1. Closing the application, modifying the .config file, and reopening did not resolve the issue. I had to edit the config file, kill WebTorrent process, and then reopen for changes to make effect. 

**Possible Solutions** 
Upon opening the application, the download path should be tested to see if it exists. If it does not exist, a warning should appear to remap, or create the directory. Verbosely, the warning should also detect if the /media path is being used, to suggest remounting & retrying.

Additionally, right clicking each torrent in the list should provide options to change the Download Path of each torrent, moving the files. This could save someone from having files dumped where they don't want, and modifying the .config as I did.

**Comment by dcposch** [comment]
> Error, Download Path does not exist, confirmation to create path or choose alternative.

Sounds good. I'll add that check

**Comment by feross** [comment]
I believe that Transmission checks for this condition and warns the user. We should see what that UX looks like and ensure that we do just as good of a job, if not better.

**Comment by dcposch** [comment]
![screen shot 2016-08-13 at 9 22 17 pm](https://cloud.githubusercontent.com/assets/169280/17647245/f7bd5b3a-619d-11e6-828d-f64a5064b06a.png)
![screen shot 2016-08-13 at 8 55 43 pm](https://cloud.githubusercontent.com/assets/169280/17647246/f7bd753e-619d-11e6-8a79-263bd1cb0f32.png)

**Comment by feross** [comment]
Fixed by #776!
