### ISSUE TITLE
Playback continues after minimize (close button)

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#649]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
latest
**What operating system and version?**
windows 8.1
**What did you do?**
press close button during playback
**What did you expect to happen?**
webtorrent to minimize and playback to pause
**What actually happened?**
playback continues

**Comment by Goldob** [comment]
I think the player was rather supposed to close entirely, judging by #348.

**Comment by feross** [comment]
Confirmed -- this is a real bug. It's my fault. @Goldob, thanks for finding the offending line here: https://github.com/feross/webtorrent-desktop/commit/62cb304971cb867e5923044df9b7afa2c5f35e78#commitcomment-17922917

**Comment by janat08** [comment]
Closing webtorrent during playback within VLC will close VLC.

**Comment by feross** [comment]
@janat08 That is different from the original issue reported here.
