### ISSUE TITLE
Adding a speed increase/decrease button to the playback toolbar

### ISSUE THREAD

**Issue by rhnvrm** [feross/webtorrent-desktop#659]
**What did you do?**
I had to find the speed increase/decrease button inside the playback menu.

**What did you expect to happen?**
Button(s) on the playback bar below the video (similar to those provided in VLC) have a button to be able to increase/decrease speed or a cog similar to the one used by youtube. 

**Use cases**
It is very useful for lectures to be able to increase decrease by clicking the button using your mouse when you are away from your keyboard taking notes using a pen. Also, for people using touch screens.

I personally would prefer a cog similar to youtube since it is generally more extendable.

*If it is an acceptable change to the community and users, I would gladly help with working on it.*

**Comment by feross** [comment]
Thanks for the suggestion, @rhnvrm.

However, I think that we shouldn't add a cog menu with a grab bag of options. It's true that this is commonly seen on video players on the web, but it makes less sense in a desktop app where we have an OS-provided menu bar for options like this.

There's also a keyboard shortcut, as you mentioned. I think that's sufficient visibility for a feature that is likely used by less than 10% of users.
