### ISSUE TITLE
Downloading gets stopped after adding torrent to the list

### ISSUE THREAD

**Issue by rittamdebnath** [feross/webtorrent-desktop#661]
WebTorrent Version: 0.7.2 
OS: Win 8.1

Problem:
After I add a torrent it runs fine for 5 min and then stops downloading (automatically). The Stream Doesn't work.

What I did to overcome it(Temporary)
The Download starts after removing the torrent from the list and restarting the webtorrent app again and adding it.Again the Problem occurs after 5 min(It stops downloading).

**Comment by dcposch** [comment]
Wow, that sounds obnoxious. Thanks for the bug report.

Next time it happens, could you click on View > Developer > Developer Tools and also View > Developer > Show WebTorrent Process? Both times, there should be a window that pops up with a Console tab. Paste what's in there (and especially any errors -- red text) here.

**Comment by feross** [comment]
Closing due to lack of new information. @rittamdebnath If you run into an error, please open a new issue.
