### ISSUE TITLE
Don't allow Create Torrent window to open from Prefs window

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#665]
Currently, you can alternate clicking Create New Torrent and Preferences to create a stack of prefs and new torrent windows as deep as you want, and move between them using the back and forward buttons.

**Comment by mathiasvr** [comment]
You don't even have to alternate, I just kept clicking preferences or spammed `cmd+,`, but maybe this is what you meant. Anyway good catch 👍
