### ISSUE TITLE
npm run package error

### ISSUE THREAD

**Issue by gabrieldesouza** [feross/webtorrent-desktop#675]
Webtorrent 0.8.0
 Win 8.1

I'm try to `npm run package win32` but then i have alot of error

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'package',
> 1 verbose cli   'win32' ]
> 2 info using npm@1.4.28
> 3 info using node@v0.10.35
> 4 verbose node symlink C:\Program Files\nodejs\\node.exe
> 5 error Error: ENOENT, open 'C:\Users\Gabriel\teste\webtorrent-desktop\node_modules\package\package.json'
> 6 error If you need help, you may report this *entire* log,
> 6 error including the npm and node versions, at:
> 6 error     <http://github.com/npm/npm/issues>
> 7 error System Windows_NT 6.2.9200
> 8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package" "win32"
> 9 error cwd C:\Users\Gabriel\teste\webtorrent-desktop
> 10 error node -v v0.10.35
> 11 error npm -v 1.4.28
> 12 error path C:\Users\Gabriel\teste\webtorrent-desktop\node_modules\package\package.json
> 13 error code ENOENT
> 14 error errno 34
> 15 verbose exit [ 34, true ]

**Comment by anonymlol** [comment]
> 3 info using node@v0.10.35
This could be the reason. Try again with a newer version.

**Comment by mathiasvr** [comment]
@feross Is a specific version of node required by WebTorrent Desktop?

We could add `engines` to `package.json` to specify this dependency:
```json
{ "engines": {"node": ">=4.0.0"} }
```

**Comment by feross** [comment]
I wouldn't expect WebTorrent Desktop to work on anything older than Node v4 (maybe Node v0.12?)

The actual version of Node used in the app itself will be whatever ships with that Electron version, but Node v4 is required for the packaging script.

@mathiasvr Good idea about "engines". PR here: https://github.com/feross/webtorrent-desktop/pull/744
