### ISSUE TITLE
Android mobile app

### ISSUE THREAD

**Issue by lucafaggianelli** [feross/webtorrent-desktop#679]
Is there any official/side project for porting WebTorrent Desktop to Android? @feross did you plan something?

Is someone interested? I actually am and I could work on it

**Comment by gabrieldesouza** [comment]
i'm working  to make an app, using webtorrent.js and magnet links stored (json) in a database to stream films It is quite simple really :P

**Comment by lucafaggianelli** [comment]
oh yes, sure it is simple! though just wondering if an official android app will ever exist

**Comment by rahulan** [comment]
@gabrieldesouza Are you using cordova or react-native?

**Comment by gabrieldesouza** [comment]
@rahulan I'm using cordova

**Comment by Flet** [comment]
`webtorrent-desktop` is based off electron, which does not support mobile operating systems currently.

If this were to happen it would probably need to be a separate effort.

I think @gabrieldesouza has the right idea though :)
