### ISSUE TITLE
Shows wrong downloading and uploading speed

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#680]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by Shankymahajan** [comment]
I'm using webtorrent on 2 platform linux and windows and in both I'm getting the same issue from the date i started using webtorrent which is the app shows me wrong downloading speed and uploading speed . As you can see in the screenshot downloading  at 8.1MBPS but my actual bandwidth is on 5MBPS even the upload speed is facing the same issue . 
![screenshot from 2016-06-27 15-10-42](https://cloud.githubusercontent.com/assets/13821954/16368296/8038ab6c-3c4c-11e6-91ba-340a7dcb5141.png)

**Comment by dcposch** [comment]
> my actual bandwidth is only 5MBPS

What did you use to measure that?

**Comment by Shankymahajan** [comment]
My bandwidth is 5MBPS and what webtorrent is showing me is more than 5MBPS .

**Comment by feross** [comment]
It looks like you're downloading copyrighted content, based on the screenshot you posted. Do not use WebTorrent for copyright infringement. We cannot assist you.
