### ISSUE TITLE
Ubuntu show in folder utter fail

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#683]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.7.2 (0.94.3)
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
Show in folder
**What did you expect to happen?**
File manager to fire up as a separate instance
**What actually happened?**
Another "state" of file manager opened (on the unity bar there were 2 file managers), with address bar like in browser thing with no find and view mode buttons on side, and the actual folder neither highlighted or opened (torrent folder wasnt opened, instead directory above).

**Comment by mathiasvr** [comment]
WebTorrent Desktop uses Electron's [showItemInFolder](http://electron.atom.io/docs/api/shell/#shellshowiteminfolderfullpath), so this might be a bug in Electron.
Can someone confirm?

**Comment by janat08** [comment]
Also the sorting wouldn't work; should be by created, and that's not an option (modified is redicilous).

**Comment by feross** [comment]
@janat08 I cannot reproduce this on a fresh Ubuntu 16.04 installation. There's a good chance that this is caused by your specific system configuration. Since I cannot reproduce it, I can't fix it.

If you have more useful information, feel free to leave another comment here and we can look into it again.

**Comment by janat08** [comment]
If some1 happens to come by this thread, here're logs.

dispatch: openTorrentContextMenu ["eeaa3396ad3e1cf325a46d541647a412d338e621"]0: "eeaa3396ad3e1cf325a46d541647a412d338e621"length: 1__proto__: Array[0]
main.js:272 showItemInFolder: /home/jk/Downloads/etc.

**Comment by janat08** [comment]
I don't think i modified this.
