### ISSUE TITLE
Support zipped subtitles (.srt.zip, .vtt.zip)

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#684]
What version of WebTorrent Desktop? (See the 'About WebTorrent' menu)
Version 0.7.2 (0.94.3)
What operating system and version?
Ubuntu 16.04
What did you do?
Dragged a subtitle during playback on webtorrent
What did you expect to happen?
For player to accept the subtitle
What actually happened?
It ignored subtitle drag and drop (they come in zips if u DL them, etc.etc.)

**Comment by mathiasvr** [comment]
WebTorrent Desktop only supports `.srt` and  `.vtt` subtitles. If they are in a zip archive you must first unzip it.
Reading zip archives could be feature request. Do people want this?

**Comment by janat08** [comment]
I implied that getting subs is a trashy process, DnD shortcut is liberating

On Tue, Jun 28, 2016 at 4:54 AM, Mathias Rasmussen <notifications@github.com

**Comment by mathiasvr** [comment]
Dragging a `.srt` or `.vtt` file to the player should add the subtitle correctly, did this not work for you?

**Comment by janat08** [comment]
.srt hasnt

**Comment by janat08** [comment]
May be unzipper bug, doesn't quite rigester when doing same thing for VLC.

**Comment by feross** [comment]
@janat08 We don't automatically unzip subtitle files. Is that a common format for subtitles? I've never seen that before.

If we see lots more requests for this handling `.srt.zip` and `.vtt.zip` files, we can consider implementing it. But I'm going to close this issue for now.

**Comment by feross** [comment]
I think this isn't too hard to support, let's just do it.

**Comment by mathiasvr** [comment]
Is this about dragging a .zip file, or dragging a .srt from a zip viewer?

**Comment by feross** [comment]
Dragging a .zip file.

**Comment by janat08** [comment]
It's actually about dragging srt from zip file.

**Comment by feross** [comment]
That sounds like it could be a quirk of the particular program you used to unzip your subtitles. What program did you use?

**Comment by janat08** [comment]
winrar, and ubuntu unzipper that's default.

**Comment by feross** [comment]
I just checked and confirmed that Archive Manager on Ubuntu just doesn't seem to support dragging and dropping files into other apps. You can even try it with VLC -- dragging subtitles from Archive Manager onto VLC does not add them.

Very sorry, @janat08. I would try filing a bug with Canonical about this.
