### ISSUE TITLE
Whenever I open Webtorrent it automatically takes torrent File association

### ISSUE THREAD

**Issue by Droyk** [feross/webtorrent-desktop#686]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.
So as the title says Whenever I open  Webtorrent it automatically takes my .torrent association & magnet association making itself a default program.

- **What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Ans. I am using Version 0.8.1 (0.95.2)

- **What operating system and version?**
Ans. I am using Windows 10 x64

- **What did you do?**
Ans. Nothing. 

- **What did you expect to happen?**
Ans. Well I expected Webtorrent to don't become a default program everytime itself   

- **What actually happened?**
Ans. it becomes a default program everytime I open it.

- **What do I actually want?**
Ans. **I want 2 options in preferences page** 
**One** make only default when I start the program and When I close it my previous default program becomes default program.
**2nd option**  don't make default whenever user start the program.

**Comment by mathiasvr** [comment]
Related to #367.

**Comment by Droyk** [comment]
> Related to #367.

Yup looks like it is related to #367  but on my case it is even changing my .torrent handler association too.
And what I want actually is **2 options in preferences page** 
**One** make only default when I start the program and When I close it my previous default program becomes default program.
**2nd option**  don't make default whenever user start the program. 
& 
@feross  said 
> We can add an option once we have a prefs window (#62).

So now we have an actual Prefs. window so I think it's time to add an option to control this thing.

**Comment by dcposch** [comment]
> make only default when I start the program and When I close it my previous default program becomes default program.

I've never heard of any program that does that.

I think we'll keep it simple: you can choose whether WebTorrent is your default app. You can choose separately for torrent files, magnet links, and stream-magnet links.

Also, we'll make sure that WebTorrent asks you the first time you run it, instead of just doing it automatically. That's kind of spammy behavior--sorry it gave you trouble.

Fix coming soon, probably in WTD 0.9

**Comment by Droyk** [comment]
@dcposch I have 2 applications in my system that does this Actually I modified them a little to make it a default and non default when the program closes.

> I've never heard of any program that does that.

That doesn't mean you can't do it & it's really simple feature to add.

**Comment by mathiasvr** [comment]
@Droyk I think a program becoming the default handler only while running will be confusing and undesirable for most users. If you want to have another client as your default, you can still drag/paste torrents and magnet links into the running WebTorrent app. I hope this is okay with you.
