### ISSUE TITLE
Telemetry results

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#689]
Telemetry is looking super useful so far.

## First, some stats

I've extracted these from the past two days worth of telemetry logs.

### OS
```
$ cat *.log | jq .system.osPlatform | sort | uniq -c | sort -n
 397 "linux"
1671 "darwin"
1957 "win32"
```

### Timezone
People are using WebTorrent all over the world!

```
$ cat *.log | jq '.localTime' | sed 's/^[^ ]* //' | sort -n | uniq -c
   1 GMT+0000 (Coordinated Universal Time)"
...
 154 GMT+0530 (India Standard Time)"
   1 GMT+0530 (Sri Lanka Standard Time)"
  13 GMT+0545 (NPT)"
  19 GMT+0545 (Nepal Standard Time)"
   2 GMT+0600 (+06)"
   3 GMT+0600 (Azores Standard Time)"
...
   2 GMT+0700 (เวลามาตรฐานเอเชียอาคเนย์)"
  64 GMT+0800 (CST)"
  14 GMT+0800 (China Standard Time)"
   7 GMT+0800 (HKT)"
   4 GMT+0800 (MYT)"
  18 GMT+0800 (Malay Peninsula Standard Time)"
   8 GMT+0800 (PHT)"
  13 GMT+0800 (SGT)"
   1 GMT+0800 (Taipei Standard Time)"
  18 GMT+0800 (中国标准时间)"
   1 GMT+0800 (中國標準時間)"
   2 GMT+0800 (台北标准时间)"
   4 GMT+0800 (台北標準時間)"
  13 GMT+0900 (JST)"
 112 GMT+0900 (KST)"
...
   2 GMT-1000 (Hawaiian Standard Time)"
   1 GMT-1000 (TAHT)"
```

### The good news

Not a single person so far is using WebTorrent Desktop on Windows XP. The earliest is Windows 7. Almost everyone has at least 2GB of ram (8 and 16 are most common) and a screen that's at least 1366x768 (1080p is most common).

That means we don't have to worry too much about supporting potatoes :)

## Exceptions

WebTorrent Desktop does not have the kind of stability we want, yet. There are tons of uncaught errors. Here are the most common ones:

```
$ cat *.log | jq '.uncaughtErrors[].message' | sort | uniq -c | sort -nr
1557 "torrent is destroyed"
 682 "Cannot read property 'message' of undefined"
 173 "Cannot read property 'removeListener' of null"
 162 "Array buffer allocation failed"
 137 "Cannot read property 'ownerDocument' of null"
  49 "val is not defined"
...
```

We have stack traces, too. I'll start filing bugs for these individually.

The play button is also not working as well as we'd like. Looks like that's mostly due to missing codec support.

```
$ cat *.log |  jq '.playAttempts' -c | grep -v 'total..0' | sort -n
...
{"total":27,"success":23,"timeout":0,"error":1,"abandoned":3}
{"total":29,"success":3,"timeout":2,"error":17,"abandoned":7}
...
```

One person got 17 "Play in VLC" codec errors in a single session...

## Metrics

Here are some things I want to start measuring.

The goal is to have as few as possible **single numbers** that we can track weekly, and try to make them better with each release.

- [ ] Fraction of Play button clicks that succeed
- [ ] Fraction of sessions that have zero uncaught errors

**Comment by Goldob** [comment]
Funny thing, my screen resolution is exactly 1366x768.

**Comment by feross** [comment]
I think we can close this issue now.

We have lots of nice ways to see the data since @dcposch built out a really fancy dashboard. See PRs https://github.com/feross/webtorrent-www/pull/76 https://github.com/feross/webtorrent-www/pull/77 https://github.com/feross/webtorrent-www/pull/78 https://github.com/feross/webtorrent-www/pull/79 https://github.com/feross/webtorrent-www/pull/80 https://github.com/feross/webtorrent-www/pull/82

If you're a collaborator on this repo, send me an email at feross@feross.org and I'll give you access to the dashboard so you can see the app usage 📊 📈 🔢

**Comment by feross** [comment]
cc @ungoldman @Flet @grunjol @demoneaux @mathiasvr @watson
