### ISSUE TITLE
Cannot resume torrent files.

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#690]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by Shankymahajan** [comment]
torrent files which i start from another bittorent client and after stoping them from bittorrent and using the magnet data in webtorrent to resume and stream files is not available .It cannot read those files which I downloaded from other clients like qbittorent .

**Comment by mathiasvr** [comment]
I believe this issue is related https://github.com/feross/webtorrent/issues/320.

**Comment by feross** [comment]
@Shankymahajan Are you sure the files from the other torrent client were in the place that WebTorrent expected them to be? The files must be in `~/Downloads` or whatever you set your download folder to be.

I think this issue can be closed. @Shankymahajan If you have more info, please comment and we can re-open this.

**Comment by Shankymahajan** [comment]
Yes after updating webtorrent it's working for me now . Thanks for the amazing app :D @feross
