### ISSUE TITLE
Play stops on one torrent when a second torrent is added

### ISSUE THREAD

**Issue by genev** [feross/webtorrent-desktop#694]
**What version of WebTorrent Desktop?** 
Version 0.8.1 (0.95.2)

**What operating system and version?**
OSX El Capitan

**What did you do?**

1. Add a torrent.
2. Start playing it.
3. Add a second torrent.

**What did you expect to happen?**
Second torrent is added and the first one continues playing.

**What actually happened?**
Second torrent is added but the first stops playing.

**Comment by mathiasvr** [comment]
Closing as duplicate, please see response to #643. Feel free to discuss this.
