### ISSUE TITLE
Cinnamon on linux keeps on crashing by webtorrent

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#696]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.8.0

**What operating system and version?**
linux (linux mint 18 beta)

**What actually happened?**

Whenever I start webtorrent . Cinnamon keeps on crashing and force me to restart it.

**Comment by demoneaux** [comment]
This seems like a duplicate of #532. Closing this instead.
