### ISSUE TITLE
Not downloading.

### ISSUE THREAD

**Issue by Samizdata** [feross/webtorrent-desktop#699]
.81 (0.95.2)

Windows 10 Pro x64

I added a magnet link to stream.

To see network activity.

Nothing.

Please see attached screenshots.

[Imgur](http://i.imgur.com/ICbQ5rC.png)
[Imgur](http://i.imgur.com/LlcmcKn.png)

**Comment by janat08** [comment]
Same issue on windows, but I have somewhat shoddy internet.

**Comment by Samizdata** [comment]
My connection's not the fastest, but it does tend to be pretty doggone stable.

**Comment by mathiasvr** [comment]
If this happens again you may try `View -> Developer -> Show WebTorrent Process` and post any errors from the console.

**Comment by janat08** [comment]
If there's a limit on how many active torrents there may be, than its possible that newer torrents don't get activated as old ones are "active" as if they weren't finished.

C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119 uncaught error webtorrent Objectmessage: "Array buffer allocation failed"stack: "RangeError: Array buffer allocation failed↵    at new Uint8Array (native)↵    at createBuffer (buffer.js:68:17)↵    at allocate (buffer.js:216:12)↵    at Function.Buffer.allocUnsafe (buffer.js:176:10)↵    at Buffer (buffer.js:110:19)↵    at RandomAccessFile.read (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\random-access-file\index.js:70:13)↵    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:193:16↵    at apply (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:16:28)↵    at Object.open (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:27:3)↵    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:191:21"__proto__: ObjectlogUncaughtError @ C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119
main.js:268 webtorrent: got wt-uncaught-error
C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119 uncaught error webtorrent Objectmessage: "Array buffer allocation failed"stack: "RangeError: Array buffer allocation failed↵    at new Uint8Array (native)↵    at createBuffer (buffer.js:68:17)↵    at allocate (buffer.js:216:12)↵    at Function.Buffer.allocUnsafe (buffer.js:176:10)↵    at Buffer (buffer.js:110:19)↵    at RandomAccessFile.read (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\random-access-file\index.js:70:13)↵    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:193:16↵    at apply (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:16:28)↵    at Object.open (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:27:3)↵    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:191:21"__proto__: ObjectlogUncaughtError @ C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119
main.js:268 webtorrent: got wt-uncaught-error

**Comment by dcposch** [comment]
We've def seen these in telemetry as well. Adding some newlines:



C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119 uncaught error webtorrent Objectmessage: "Array buffer allocation failed"stack: "RangeError: Array buffer allocation failed
    at new Uint8Array (native)
    at createBuffer (buffer.js:68:17)
    at allocate (buffer.js:216:12)
    at Function.Buffer.allocUnsafe (buffer.js:176:10)
    at Buffer (buffer.js:110:19)
    at RandomAccessFile.read (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\random-access-file\index.js:70:13)
    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:193:16
    at apply (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:16:28)
    at Object.open (C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\thunky\index.js:27:3)
    at C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\node_modules\fs-chunk-store\index.js:191:21"__proto__: ObjectlogUncaughtError @ C:\Users\ALERATOR\AppData\Local\WebTorrent\app-0.9.0\resources\app.asar\renderer\lib\telemetry.js:119
```

**Comment by dcposch** [comment]
@feross and I just investigated and we think we know why this might be happening.

`random-access-file` is probably trying to create a huge Buffer: https://github.com/mafintosh/random-access-file/blob/master/index.js#L70

**Comment by dcposch** [comment]
@Samizdata curious, how big is the torrent you're downloading?

**Comment by dcposch** [comment]
@Samizdata also, how much RAM do you have? Are you often out of RAM or closet to that?

**Comment by janat08** [comment]
I got 16GB, but a bunch of files may be considered to be not downloading although they have been. The size of 1GB won't download.

**Comment by feross** [comment]
@janat08 Can email your .torrent file to the email (listed on my github profile) so we can take a closer look. I suspect that it has something to do with the specific file.

**Comment by janat08** [comment]
I would actually mostly use magnet links. This magnet for example would download, than tell me that it can't play although I was watching it, and now it's stuck.
```
magnet:?xt=urn:btih:a2139c74cedebaca76681a6dcaa441ee4891561c&dn=Stranger.Things.S01E01.WEBRip.x264-TURBO%5Bettv%5D&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io
```

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
