### ISSUE TITLE
Subtitles have been disabled after "Back" and "Start streaming"

### ISSUE THREAD

**Issue by xnakos** [feross/webtorrent-desktop#701]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.8.1
**What operating system and version?**
Ubuntu Desktop 16.04
**What did you do?**
I pasted a magnet link and after a few seconds I clicked "Start streaming". I clicked on "CC" and double-clicked on the subtitle file (the video file and the subtitle file did not have the same name). The video file played fine with subtitles. After a few minutes I clicked "Back" to go back to the main screen. Then I finally clicked "Start streaming" again. The video file resumed playing from the point I had left it.
**What did you expect to happen?**
I expected that the subtitles I had previously selected would be showing, since resuming from the last played position suggests that a state is saved for a specific magnet link.
**What actually happened?**
No subtitles were selected and I had to re-select them by clicking on "CC".

Great project by the way! ;)

**Comment by feross** [comment]
@xnakos This is fixed and released in WebTorrent Desktop 0.9.0, by the way!

**Comment by xnakos** [comment]
@feross Thanks for the update! Rock on!
