### ISSUE TITLE
Poster and torrent is not deleted upon torrent deletion

### ISSUE THREAD

**Issue by pwnsdx** [feross/webtorrent-desktop#709]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.8.1 (0.95.2)

**What operating system and version?**

OS X 10.11

**What did you do?**

![screenshot](https://cloud.githubusercontent.com/assets/2057765/16710840/ab759762-463e-11e6-9b49-8da12c06b64d.png)

![screen shot 2016-07-10 at 01 44 33](https://cloud.githubusercontent.com/assets/2057765/16710868/e28dd056-463f-11e6-8b5c-5d5af542f100.png)

**What did you expect to happen?**

Nothing in these directories

**What actually happened?**

All thumbnails of all my downloaded torrents along with torrents files are kept.

It can lead to:
- Privacy issues on shared computers
- Eating hard drive space slowly over time (80mb here)

**Comment by feross** [comment]
@pwnsdx Thanks for the issue, this is fixed and released now.

**Comment by pwnsdx** [comment]
Thanks you 😉
