### ISSUE TITLE
"Error: Attempt to write outside the buffer" sometimes

### ISSUE THREAD

**Issue by raeesiqbal** [feross/webtorrent-desktop#714]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
`Version 0.4.0 (0.93.3)`
**What operating system and version?**
`OS X El Capitan 10.11.5 (15F34)`
**What did you do?**
Dragged a `.torrent` file on the WebTorrent window.
**What did you expect to happen?**
It should have added the torrent to download list.
**What actually happened?**
It showed a warning, "Error: Attempt to write outside the buffer"

Weird thing is that the error went away after a few restarts of WebTorrent and retries. There are some magnet URI that don't work with error "Invalid Identifier". I think these issues are related because the magnet link for the issue had this error.

**Comment by mathiasvr** [comment]
Can you update to the newest version and see if this solves the problem?

**Comment by feross** [comment]
I'm 99% sure this issue will go away if you update WebTorrent Desktop.

We switched to using [`safe-buffer`](https://github.com/feross/safe-buffer) in webtorrent v0.94.3 which catches . You can see that in the [CHANGELOG](https://github.com/feross/webtorrent/blob/master/CHANGELOG.md#v0943---2016-05-30).

Detailed issue: https://github.com/feross/webtorrent/issues/820
