### ISSUE TITLE
Need to be able to select VLC playback instead of built-in player

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#732]
WebTorrent doesn't seem to support switch audio streams at the moment, but VLC does that job perfectly. Most of the movies can't play through webtorrent, so it shows me an option to start through VLC. But for some, I am stuck with the built-in webtorrent player. 

How about an option to let me choose which player I want to use?

**Comment by dcposch** [comment]
I agree. Let's do it

> How about an option to let me choose which player I want to use?

For that part, there's already a PR: https://github.com/feross/webtorrent-desktop/pull/682

**Comment by feross** [comment]
Related: https://github.com/feross/webtorrent-desktop/issues/531

**Comment by feross** [comment]
This is actually a duplicate: https://github.com/feross/webtorrent-desktop/issues/531
