### ISSUE TITLE
Always making itself as default program for torrents.

### ISSUE THREAD

**Issue by KashifAnwaar** [feross/webtorrent-desktop#734]
**What version of WebTorrent Desktop?** 
WebTorrent v0.9.0

**What operating system and version?**
Windows 7 64bit

**What did you do?**
Just opened

**What did you expect to happen?**
Don't set itself as default program for torrents without asking the user

**What actually happened?**
Everytime it sets itself as  default program for torrents, especially very painful when it sets also for magnet links.

**Comment by demoneaux** [comment]
Hi! This issue is a duplicate of #367. We’re working on fixing this! If you’ve got any other issues feel free to report them. Closing this for now.

**Comment by KashifAnwaar** [comment]
#367 was only for magnets, i am here reporting for all torrent associations.

**Comment by feross** [comment]
@KashifAnwaar I just updated the title to include all torrent associations. Thanks for opening an issue.

**Comment by KashifAnwaar** [comment]
@feross I am fan of yours, thanks for the reply.

**Comment by feross** [comment]
@KashifAnwaar Thanks 👍

**Comment by KashifAnwaar** [comment]
It's my pleasure
