### ISSUE TITLE
buffer.js:705 throw TypeError('value is out of bounds');

### ISSUE THREAD

**Issue by slrslr** [feross/webtorrent-desktop#735]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
DEBUG INFO: webtorrent-cli 1.2.3, webtorrent 0.95.2, node v0.10.42, linux x64, exit 1

**What operating system and version?**
CentOS release 6.8 (Final), 64bit

**What did you do?**
Tried to download file (On my CentOS Linux VPS/remote server in different country) which im trying to seed (via WebTorrent 0.8.1, 0.95.2) on my home Windows computer.

**What did you expect to happen?**
File downloaded to my Linux CentOS remote server from my home WIndows computer.

**What actually happened?**
Here is a screenshot of the error: https://s20.postimg.org/lkwmjkyx9/webtorrent_cli_dl_error.gif
buffer.js:705
    throw TypeError('value is out of bounds');

**Comment by feross** [comment]
Node v0.10 is not supported anymore. You can install the latest version of Node.js on CentOS by following the instructions here: https://github.com/nodesource/distributions#rpminstall

Give that a try and let me know if it works!

**Comment by slrslr** [comment]
Yes, it worked. This is what worked to install it on CentOS:
yum remove nodejs npm -y;yum install nodejs npm -y;npm install webtorrent-cli -g
webtorrent --help

**Comment by demoneaux** [comment]
:+1:! Also, just a note: this repo is for the WebTorrent desktop app, if you’re reporting issues for the CLI you should put them here: https://github.com/feross/webtorrent-cli or for the core WebTorrent library: https://github.com/feross/webtorrent.
