### ISSUE TITLE
Download Location Issue 

### ISSUE THREAD

**Issue by krisgopal128** [feross/webtorrent-desktop#749]
Version : 0.9.0 (0.95.2)

OS : Antergos 16.4 (Kernel 4.6.4)

Sometimes i download Torrents to Portable Devices , example if the location is set to /media/USB
If the usb is disconnect or usb is unmounted (now the /media/USB is not present)
Whennew torrent is added to Web Torrent, the file starts downloading without showing any error  & i cannot find the file in any location    

To show location error or revert back location to /home/user/Download

The torrent kept downloading

**Comment by mathiasvr** [comment]
Duplicate of #646.
