### ISSUE TITLE
WebTorrent seems to download files even though they were canceled

### ISSUE THREAD

**Issue by Runemoro** [feross/webtorrent-desktop#750]
**What version of WebTorrent Desktop?** 0.9

**What operating system and version?** Windows 8.1 Pro (64-bit)

**What did you do?** I downloaded a torrent with multiple large files and removed all but of the files using the X button. WebTorrent kept downloading at 12 MB/s even though the download progress stayed at 20 MB / 18 GB. After restarting WebTorrent, the file I had selected started downloading, but download size still showed as 18 GB.

**Comment by swift11** [comment]
almost the same problem here: torrent with 50 files, I had deselected 13 files yesterday, they are active again today...

**Comment by feross** [comment]
I can't reproduce this. 

@Runemoro @swift11 Were the files that you de-selected already fully downloaded? Or were they still in progress?

**Comment by feross** [comment]
I'm closing this issue because it's been a while without a response from the issue opener. It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
