### ISSUE TITLE
Issue with the full screen layout

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#754]
**What version of WebTorrent Desktop?**
0.9.0
**What operating system and version?**
linux mint 17.3

Whenever I'm using the webtorrent in full screen ,the layout doesn't look as good as the default view it (in a small window) . 
It's most probably because of the list-view (height and width) ,you can try to increase the height to for the full-screen window ,small screen windows is perfect . 

thankyou!

**Comment by feross** [comment]
We used to use media queries to increase the height of each torrent in the list as the window got wider, but it made the app feel too much like a webpage, so we decided to leave it up to the user to manage the window size and keep it at a reasonable size.
