### ISSUE TITLE
[feature request] Always on top player window

### ISSUE THREAD

**Issue by devster31** [feross/webtorrent-desktop#763]
I'd like to suggest a player option to keep the window always on top during playback, there could also be the option to keep the player always on top only when it's actually reproducing something and not when paused.

**Comment by mathiasvr** [comment]
There is `View -> Float on Top`. You want it to only be active during playback? This seems a bit confusing to me, do you know of any player that does this already?

**Comment by devster31** [comment]
I missed the `View -> Float on Top` option, I only searched under Window, my fault. The player I'm using is `mpv` and it has a lua script to achieve this behaviour [here](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ontop-playback.lua), there's also [SMPlayer](http://smplayer.sourceforge.net) that does this. Essentially it only keeps the window on top of everything during playback and not when player is paused.

**Comment by feross** [comment]
@devster31 This sounds potentially useful if you understand what's happening. But this feature seems hard to explain to new users, and the way it works also wouldn't be apparent immediately.

I could see this as a new option -- "Float on Top During Playback" in the menu. But this seems really niche, and maybe it's best left to be implemented as a plugin once we have support for that.
