### ISSUE TITLE
Add basic integration test

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#765]
The Electron team created Spectron to test Electron apps:

http://electron.atom.io/spectron/
https://github.com/electron/spectron

It looks like @dcposch already started integrating this on a branch: https://github.com/feross/webtorrent-desktop/tree/dc/test

I think we can keep things simple and just add a single integration test to ensure the app starts up without crashing.

**Comment by dcposch** [comment]
Done. We still have lots more integration tests to add, but we have a nice system now. We have good tests for the torrent list.

Next up: testing audio and video playback, casting, adding existing torrents, creating new torrents, and the prefs page.

**Comment by feross** [comment]
Thanks for tackling this. I think this will really us to not ship broken software.
