### ISSUE TITLE
Opt-out for telemetry

### ISSUE THREAD

**Issue by dol** [feross/webtorrent-desktop#766]
Is there any possibility to disable telemetry? Would be nice to opt-out of this option.

**Comment by feross** [comment]
Hey @dol, thanks for opening this issue.

The information that is collected is just to help us fix bugs -- it's pretty innocent. Here's an example log that was collected:

```json
{
  "approxNumTorrents": 4,
  "ip": "71.198.47.128",
  "localTime": "23:49:23 GMT-0700 (PDT)",
  "playAttempts": {
    "abandoned": 0,
    "error": 0,
    "success": 0,
    "timeout": 0,
    "total": 0
  },
  "screens": [
    {
      "height": 800,
      "scaleFactor": 2,
      "width": 1280
    }
  ],
  "system": {
    "architecture": "x64",
    "numCores": 4,
    "osPlatform": "darwin",
    "osRelease": "Darwin 15.5.0",
    "totalMemoryMB": 8192
  },
  "timestamp": "2016-06-22T06:49:23.595Z",
  "uncaughtErrors": [],
  "userID": "f77a9f09565f26bbcd771dde5c0970d5408af13e59531e08a5b36a8e698c5f14"
}
```

It's also worth nothing, as @dcposch said in [this comment](https://github.com/feross/webtorrent-desktop/pull/655#issuecomment-227583842):

- We're not collecting personally identifying information
- Lots of common software collects this kind of telemetry, with no prompts and often with no prefs setting.
- Using a torrent client inherently broadcasts much more sensitive info anyway---to peers, trackers, and the DHT, which is publicly visible. Specifically, which swarms you're part of.

Despite all this, I think a PR that added an option to the preferences to disable this would be fine.

**Comment by dol** [comment]
@feross  Thank you for your clarification.
How do you getter the IP? Not found any hint in the code.

**Comment by grunjol** [comment]
Maybe only send /16 for IP address?

**Comment by feross** [comment]
The IP isn't collected from the machine, it's added on the server-side. It's an artifact of how TCP connections work -- the server will always see your IP address if you send it an HTTP request ;)

However, the /16 suggestion is pretty good. Maybe there's no need to store the IP since we're already generating a unique ID. We just want to be able to count the total number of users of WebTorrent Desktop.

**Comment by demoneaux** [comment]
Since #832 has been closed, should we close this too?

**Comment by feross** [comment]
@demoneaux Yep, good call
