### ISSUE TITLE
Unable to modify list of trackers.

### ISSUE THREAD

**Issue by k0nsl** [feross/webtorrent-desktop#768]
**What version of WebTorrent Desktop?** 0.10.0

**What operating system and version?** Debian 8

**What did you do?** I tried to create a torrent.

**What did you expect to happen?** I expected it to allow me to modify the list of trackers.

**What actually happened?** It didn't allow me to modify the list of trackers.

I downloaded the latest release (thanks by the way!) and went ahead and tried to create a new torrent. But it's not possible to modify the trackers, either to remove them, or just to add more to the list. It appears as if the textbox is locked.
I'm not sure what good a screenshot would be as there is nothing peculiar to see. Here is one anyway:
[https://proxy.img-cdn.ru/https://k0nsl.img-cdn.ru/vcxsrv_2016-08-07_08-35-24.png](https://proxy.img-cdn.ru/https://k0nsl.img-cdn.ru/vcxsrv_2016-08-07_08-35-24.png)

Did anyone else experience this type of behaviour in 0.10.0?

[**EDIT:** this behaviour is confirmed on Windows 10 Enterprise as well.]

**Comment by feross** [comment]
I just confirmed this.

**Comment by feross** [comment]
@dcposch any ideas?
