### ISSUE TITLE
ASS/SSA support

### ISSUE THREAD

**Issue by cazador1337** [feross/webtorrent-desktop#777]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.10.0 (0.96.0)

**What operating system and version?**
Windows 8.1 Pro

**What did you do?**
Watch a anime ep with ass softsubs -> this anime http://www.nyaa.se/?page=view&tid=839383.

**What did you expect to happen?**
show anime's subs

**What actually happened?**
don't show it

*******************************
your software is really amazing, and if u add this support u can make many happy otakus.
I want to watch my anime while it is downloading.
Add support for all subtitles types.

**Comment by dcposch** [comment]
>  if u add this support u can make many happy otakus

LOL

**Comment by dcposch** [comment]
I just looked at the site you linked to. Please don't link to copyrighted content. We don't support use of WebTorrent for copyright infringement, and cannot help you.
