### ISSUE TITLE
command line option to bind to specific network interface

### ISSUE THREAD

**Issue by allefeld** [feross/webtorrent-desktop#778]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.10.0 (0.96.0)

**What operating system and version?**
Linux 3.16.0 (Debian 8.5)

This is not a bug report, but a feature request.

Please include a command line option (not just a preference, to be scriptable) to bind WebTorrent Desktop to a specific network interface. Like the `-i  --bind-address-ipv4` and `-I   --bind-address-ipv6` options of transmission-daemon.

**Comment by allefeld** [comment]
Alternatively, please support the Chrome option `--proxy-server=`, because then one can effectively bind to an interface via e.g. `tinyproxy`.

**Comment by feross** [comment]
I'm not sure I understand why this needs to be a command line option. None of the other options in WebTorrent Desktop are currently exposed via a command line option. How are you using WebTorrent Desktop in a script? Can [`webtorrent-cli`](https://github.com/feross/webtorrent-cli) work for you?

**Comment by allefeld** [comment]
@feross, the reason is that the interface is not always the same one, and reconfiguring manually is tedious. So I'd like to write a shell script wrapper that figures out the interface and then starts WebTorrent Desktop.
`webtorrent-cli`, maybe, I'll check it out. Thanks!

**Comment by feross** [comment]
Thanks for explaining. If you're interested in sending a PR for this, I'll take a look at it. But I think this kind of advanced feature probably should be added to `webtorrent-cli`.
