### ISSUE TITLE
WebTorrent Not Showing Torrents (Grey GUI)

### ISSUE THREAD

**Issue by micky2171** [feross/webtorrent-desktop#781]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.10.0 (0.96.0)

**What operating system and version?**
Windows 10 Pro

**What did you do?**
Open the program.

**What did you expect to happen?**
Show my downloading torrents

**What actually happened?**
Only a grey GUI was shown.

![image](https://cloud.githubusercontent.com/assets/7550213/17784807/d007b348-6575-11e6-81e5-b72cc58f8a3b.png)

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

Being able to see that output would help us out very much. Thanks.
