### ISSUE TITLE
WebTorrent failed to detect already downloaded files

### ISSUE THREAD

**Issue by jankeromnes** [feross/webtorrent-desktop#782]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.10.0 (0.96.0)

**What operating system and version?**

Windows 10

**What did you do?**

Start downloading a multi-file torrent. After a few files were already downloaded, my computer crashed (not WebTorrent's fault). I rebooted and launched WebTorrent again.

**What did you expect to happen?**

Some files that were already 100% downloaded earlier should have been detected on disk, and not downloaded again.

**What actually happened?**

WebTorrent indicated that these files were still 0% downloaded, and I believe it was about to download them again.

Note: There were many errors like this logged in the Console

    C:\Users\jan\AppData\Local\WebTorrent\app-0.10.0\resources\app.asar\build\renderer\main.js:266
    webtorrent: got wt-uncaught-error

When I restarted WebTorrent, it was able to succesfully detect all local files again.

**Comment by feross** [comment]
On startup WebTorrent checks the files on disk and verifies that they're correct before starting torrenting. If the app crashed, it probably didn't save the current progress and had to re-verify from scratch. That would appear as the file progress increasing from 0% to 100% but it's not actually re-downloading it.

Of course, maybe you're right and it was re-downloading it. That would indeed be a bug.

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

Being able to see that output would help us out very much. Thanks.

**Comment by jankeromnes** [comment]
Thank you @feross !

> That would appear as the file progress increasing from 0% to 100% but it's not actually re-downloading it.

The files stayed at 0% for a long time, whereas WebTorrent was already torrenting (upload and download were active).

> Can you try to reproduce this error once more?

I wasn't able to reproduce yet, sorry.

> But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

I already did that, and the following error message was displayed about 13 times. A few normal info messages, but no other errors in the Console (sorry for not having the full text).

    C:\Users\jan\AppData\Local\WebTorrent\app-0.10.0\resources\app.asar\build\renderer\main.js:266
    webtorrent: got wt-uncaught-error

I'll re-open this bug if I'm able to reproduce, and I'll paste the full Console log. Thanks again!
