### ISSUE TITLE
Fail fast when you can't play a torrent

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#816]
**What version of WebTorrent Desktop?** 0.12

**What operating system and version?** All OSs

**What did you do?**
* Create a torrent. Stop seeding (click the blue icon)
* Close WebTorrent
* Delete the data file from disk
* Reopen WebTorrent
* Click Play on that torrent

**What did you expect to happen?**

It should fail immediately with a "Path missing" error.

**What actually happened?**

It shows a "Path missing" error immediately, but still hangs for ~20 seconds until it plays the "timeout" sound and stops the loading spinner. Annoying since you can't do anything else with the app during those 20 seconds.

Suggested fix: any error that occurs during a play attempt should end the timeout counter immediately.

**Comment by mathiasvr** [comment]
We should also end the timeout if a user stops the torrent after pressing play.

**Comment by demoneaux** [comment]
Currently with the new change to head straight to the player interface, if the user deletes a single video file and tries to play it via WebTorrent Desktop, it appears to work and just re-stream the file again. However, if the whole torrent folder is deleted while the app is active, if the user tries to play a video through WebTorrent Desktop, the user will be stuck staring at a blank video screen which doesn't load. However, if they go back to the torrent list, the torrent file missing message can be seen.

**Comment by feross** [comment]
Both the original issue and the issue mentioned in @demoneaux's comment are fixed now, right?

Closing this.
