### ISSUE TITLE
Volumen

### ISSUE THREAD

**Issue by slemesp** [feross/webtorrent-desktop#819]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0
**What operating system and version?**
Ubuntu 16.04 LTS 64 
**What did you do?**
volumen not working, volumen down or up come back to previous state
**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment]
@slemesp I cannot see the error that you describe. Can you provide more details?

Were you casting to an external device like a Chromecast or Airplay when this happened? Were you using an external video player like VLC?

**Comment by Tsirhcitna** [comment]
Happened to me too, didn't notice this issue already opened, see https://github.com/feross/webtorrent-desktop/issues/862

**Comment by dcposch** [comment]
According to #862 this is fixed since 0.13

Feel free to reopen if you run into this again on the latest version, and thanks for the bug report
