### ISSUE TITLE
Torrent will not open in VLC

### ISSUE THREAD

**Issue by woodland021** [feross/webtorrent-desktop#828]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0
**What operating system and version?**
mac OS 10.12 Sierra
**What did you do?**
Added torrent to queue and pressed play (Torrent is folder and movie is an .avi)
**What did you expect to happen?**
I expected Webtorrent to open the .avi in my installed VLC player.
**What actually happened?**
The VLC logo is shown when I press play but no video gets sent and opened into VLC.

**Comment by dcposch** [comment]
Just tested and playing in VLC works for me--same app and OS version.

1. Check your dock. VLC might open, but not be in the foreground.
2. If you run into this again, could you go to View > Developer > Developer Tools, then go to to Console tab and paste any errors here?

Finally, what version of VLC do you have installed? It's in Applications, right?

Thanks for reporting!

**Comment by feross** [comment]
I'm closing this issue because it's been a while without a response from the issue opener. It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
