### ISSUE TITLE
Start the app automatically on boot

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#835]
We should add a pref, on by default, that starts WebTorrent Desktop automatically. That helps keep the swarms healthy.

**Comment by noamokman** [comment]
I'm on it, (#837)
Would love to have your input on this @dcposch

**Comment by obv-mikhail** [comment]
Not sure whether it should be on by default. Seems intrusive?

**Comment by dcposch** [comment]
@obv-mikhail will be off by default for now.

For comparison, though, uTorrent has a similar pref that's on by default (people even complained because they changed it to auto-start again with every app update!)

**Comment by iovis9** [comment]
I'd definitely NOT put it on by default ever.

**Comment by grunjol** [comment]
Reasons against set as default are already mentioned in the feature branch https://github.com/feross/webtorrent-desktop/pull/837/commits/d6920c69c9953669d9cedd1783970451fa1b3336

**Comment by demoneaux** [comment]
Closing as this was fixed in #923.
