### ISSUE TITLE
Start playing "first" video in folder

### ISSUE THREAD

**Issue by nhuber** [feross/webtorrent-desktop#839]
I.e. Be smart about finding S01E01 and stream first in a folder ... Last night I DL'd a series and WT accidentally started me with S1E6 and I didn't realize til 40 mins in :( cc @feross

**Comment by soapyslick** [comment]
Would be a helpful feature to let the user select which file they want to play from the torrent, had the same issue earlier today.

**Comment by bertofer** [comment]
@soapyslick You can select the file you want to reproduce, by clicking on the torrent and expanding it, then clicking on the play icon of the file you want to reproduce.

Thing is, which file is reproduced when clicking on the 'play' button of the entire torrent itself. As I said, I think should be the first in the folder.

**Comment by soapyslick** [comment]
@bertofer Oh sweet, didn't notice that. I've been using single torrents all this time, will start using grouped ones, thanks!

**Comment by dcposch** [comment]
Makes sense. I reopened a closely related feature request, #123.

@soapyslick I agree the torrent list view should be more clear. Right now a lot of people aren't seeing:
1. That they can expand and collapse torrents
2. That they can turn torrents on and off (eg to stop downloading/seeding) via the blue button

We'll try to improve the design there soon. See #652

**Comment by mathiasvr** [comment]
@dcposch any thoughts about this PR #751?
