### ISSUE TITLE
Cannot find module '../components/Header'

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#842]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
master
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
Open the App
**What did you expect to happen?**
Start correctly
**What actually happened?**
`module.js:442 Uncaught Error: Cannot find module '../components/Header'`

I think the problem is component name is lowercase header. Linux is case sensitive and can not find the file

**Comment by dcposch** [comment]
Fixed in #843
