### ISSUE TITLE
Local mp4 movie does not play from its torrent in the UI

### ISSUE THREAD

**Issue by johnblommers** [feross/webtorrent-desktop#846]
**Using**: webtorrent-desktop@0.12.0 built per instructions from git and npm.

**Operating system**: OS X El Capitan 10.11.6 with Node version v0.10.22

**Did this**: Created a torrent with Transmission for a local MP4 movie sized 106 MB   (without any trackers of course), dropped it on the designated area of the UI, and tried to play it in the UI.

**Should have**: The movie should have started to play

**Instead**: Nothing downloads and the circular icon spins forever and the movie does not play

**Comment by dcposch** [comment]
1. Node v0.10 is really old. If you want to help develop WebTorrent, try upgrading to the current version of Node, v6.4
2. Alternatively, if you just want to use the app, I recommend installing from the DMG. That way, you don't have to care about dependency versions and you'll also get the latest fixes and improvements thru the auto updater

If you try option 1 or 2 and this still happens, let me know!
