### ISSUE TITLE
Stream torrent on 2 computers synced at the same time?

### ISSUE THREAD

**Issue by NIXOYE** [feross/webtorrent-desktop#847]
Is there any work on getting torrents to sync on play so people could stream videos with the help of p2p distribution?

**Comment by dcposch** [comment]
you mean like Gaze? https://letsgaze.com/#/

**Comment by dcposch** [comment]
I think not. We're want to keep WebTorrent Desktop **minimalist**. You could try external screensharing software (eg, a google hangout where you share the WebTorrent window)
