### ISSUE TITLE
Addkeyboard key functions

### ISSUE THREAD

**Issue by AzizKamboh** [feross/webtorrent-desktop#848]
1.Please add keys function like forward,backward playback for 5sec by arrow keys,
2.Stop/start playback with mouse left click.

**Comment by mathiasvr** [comment]
You can step forward/backward by using the keyboard shortcuts listed in the `Playback` menu, and start/stop playback by clicking the play/pause button in the playback bar. It is the same as in VLC.

However stepping using the arrow keys alone might actually be a good idea? @feross @dcposch

**Comment by dcposch** [comment]
@mathiasvr probably not, the arrow keys are easy to hit accidentally

See https://github.com/feross/webtorrent-desktop/pull/860

**Comment by feross** [comment]
I agree with @dcposch. I like the current skip shortcuts. They're the same that VLC uses.
