### ISSUE TITLE
Bandwith settings

### ISSUE THREAD

**Issue by andresiraola** [feross/webtorrent-desktop#850]
It would be nice to be able to limit the bandwith like "I just want to allocate 5 Mbps for downloads and 1 Mbps for uploads". This would avoid hogging the user's internet connection.

Also, Free Download Manager has a very convenient mode called "Snail mode" which doesn't stop downloads but limit bandwidth to a minimum. This is a very nice feature you can add to the client.

![image](https://cloud.githubusercontent.com/assets/11182419/18034723/d4900ecc-6d1a-11e6-8d50-fa7f60eb47b6.png)

What do you think about it?

**Comment by c0b41** [comment]
dups #435
