### ISSUE TITLE
Seed ratio stats (amount or % of data sent to peers)

### ISSUE THREAD

**Issue by Myu-Unix** [feross/webtorrent-desktop#852]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.12.0 (0.96.3)

**What operating system and version?**

Gentoo Linux Base System 2.2 x86_64

**What did you do?**

It would be great for persons still on a limited internet quota/month to get info on how much a completed torrent in "seed mode" has been seeded already.

**What did you expect to happen?**

Have a way to check the amount of data seeded / torrent

**What actually happened?**

No way to do it for now.

Thank you for your great work, the overall out of the box experience is SPLENDID ! Kudos !

**Comment by dcposch** [comment]
@Myu-Unix instead of showing a per-torrent seed ratio (which I think will be too much UI clutter), how about adding an option to limit the seed ratio?

For people on metered connections, that sounds more directly useful. See #435

Do you think that would be enough?

**Comment by dcposch** [comment]
> Thank you for your great work, the overall out of the box experience is SPLENDID ! Kudos !

Glad you like it!
