### ISSUE TITLE
Memory leak detected ? 

### ISSUE THREAD

**Issue by Udgin** [feross/webtorrent-desktop#857]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.12.0 (0.96.3)
**What operating system and version?**
Windows 10 1607
**What did you do?**
Downloaded two torrents, close app, open app - look at console.
**What did you expect to happen?**
App starts without any errors.
**What actually happened?**
![image](https://cloud.githubusercontent.com/assets/1629511/18108582/2b4461a2-6f0d-11e6-8bf7-4dfaaa1aef60.png)

**Comment by feross** [comment]
This warning can safely be ignored. It's Node.js being overzealous. We could disable this type of warning, but sometimes it actually catches leaks, so we'll leave it enabled.

Thanks for the report.
