### ISSUE TITLE
Need Option to disable sound on Mac

### ISSUE THREAD

**Issue by shameer99** [feross/webtorrent-desktop#858]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0 (0.96.3)
**What operating system and version?**
macOS Sierra 
**What did you do?**
Use the app
**What did you expect to happen?**
Have an option to disable sound
**What actually happened?**
Dont see an option to disable sound

**Comment by avatsaev** [comment]
sorry for multiple commits I fucked up, forgot to git add.

**Comment by feross** [comment]
I just sent a PR to make the UI sounds subtler. See #945 I hope you give it a try by cloning master or waiting until the next release comes out. Would be great to get your feedback.
