### ISSUE TITLE
Torrent list design

### ISSUE THREAD

**Issue by bertofer** [feross/webtorrent-desktop#866]
As started to discuss [here](https://github.com/feross/webtorrent-desktop/issues/652#issuecomment-243923919), I start this thread to talk about the torrent list design issues and improvements. These are the two current tasks

- [ ] Clarify download status (see #715)
- [ ] Clarify that torrents can be expanded / collapsed

[Here ](https://github.com/bertofer/webtorrent-desktop) is a first try to improve the first one, using a pause icon on hover of torrenting button. 

@iovis9 had the idea of moving play button to the left side of the torrent title, also. Will try that and post here any result to discuss.

**Comment by bertofer** [comment]
Did some hacking to try to put the play button on the left, and also pause on hover on the download/seed buttons. Felt a bit weird that the metadata is 'displaced' to the right when hovering, so did a version also where the metadata is automatically leaving space for a possible Play button. I leave some screenshots:

**before**

<img width="500" alt="screen shot 2016-09-20 at 11 44 46" src="https://cloud.githubusercontent.com/assets/1634229/18667244/aa8f1f36-7f27-11e6-8165-f7850c0bfeed.png">

**after with hover**

<img width="498" alt="screen shot 2016-09-20 at 11 40 08" src="https://cloud.githubusercontent.com/assets/1634229/18667276/cf413814-7f27-11e6-9753-faec71215e1d.png">

**after without hover**

<img width="496" alt="screen shot 2016-09-20 at 11 40 24" src="https://cloud.githubusercontent.com/assets/1634229/18667283/d526850e-7f27-11e6-93af-290e80865f1f.png">

**After with metadata moved to the right (Best option for me)**

<img width="500" alt="screen shot 2016-09-20 at 11 44 46" src="https://cloud.githubusercontent.com/assets/1634229/18667309/f3bb3e42-7f27-11e6-8032-b7cdd9ee1e20.png">

We could cut by 60px by default on the right as well., keeping a 60px horizontal padding on both sides, and increasing on hover for the rest of the buttons.

Here's my fork with the commits to try it https://github.com/bertofer/webtorrent-desktop

**Comment by bertofer** [comment]
Also ,I came with an idea for the progress bar, just photoshoped for now, let me know what you think

**With translucid background (Best one for me)**

![progressbarwbg](https://cloud.githubusercontent.com/assets/1634229/18667859/32a5db56-7f2a-11e6-9c31-7b56415ed52e.jpg)

**Without background**

![progressbarwobg](https://cloud.githubusercontent.com/assets/1634229/18667864/35e61c04-7f2a-11e6-92fc-f2ec96383cd6.jpg)

**Comment by iovis9** [comment]
I like the one with the translucent background best :)

And I think separating the Play Video button and the Pause/Download torrent button is a good idea for easier understanding.

If I may suggest something: Does it need that many colors? I think the Pause/Download Torrent button could be more like the Delete button just next to it. I like having a big red Play button so the user is attracted to it as the primary action, but pausing the torrent sounds like something much more secondary. I don't think it qualifies for having another color. Also, lots of "screaming for attention" interfaces with vivid colors kind of defeats the purpose of guiding the user through the main usage.

I'd try maybe removing the circular background for the pause button and giving it the same color as the close button. Maybe the circular background could be used for hover, with different _lightness_ (HSL) from the foreground color?

**Comment by dcposch** [comment]
Thanks for making this!

I especially like the thin progress bar that stretches all the way across the page.

I don't know about having the blue button turn into a pause logo. I think having a play logo and a pause logo visible at the same time might confuse users --- normally you always toggle between play and pause.

**Comment by bertofer** [comment]
@dcposch I will implement the progress bar then, while we think better solutions to solve the torrenting button concerns

**Comment by dcposch** [comment]
@bertofer I wouldn't quite yet!

@feross was considering removing the progress bar entirely in a future release

**Comment by feross** [comment]
I think we should either remove the progress bar or make it really, really subtle. Torrents are all playable instantly in WebTorrent Desktop, so the progress really shouldn't matter that much.

Now, there's obviously a need to see it sometimes -- if you want to watch something later offline, for example. So we can keep it, but I think it should be like almost entirely transparent. Like really light gray.

**Comment by bertofer** [comment]
@feross I will do some image to show what you said, I think it would be enough. I just wouldn't remove it completely, as there's the case aswell when you download torrents that are not playable (Linux distro e.g.).

**Comment by feross** [comment]
@bertofer Yep, agree

**Comment by bertofer** [comment]
Something like this? (progress bar hidden on completed torrents)

![wtorrentprogressbar](https://cloud.githubusercontent.com/assets/1634229/18867456/30feff18-849c-11e6-9ee6-e024e9d97de4.jpg)

10% white opacity for background, 30% white opacity for the progress bar over the background

**Comment by feross** [comment]
I think the original two issues raised here are now resolved:

- [x] Clarify download status (see #715)
- [x] Clarify that torrents can be expanded / collapsed
