### ISSUE TITLE
WebTorrent Desktop not showing info

### ISSUE THREAD

**Issue by kusandore** [feross/webtorrent-desktop#868]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0 (0.96.3)
It happened on an older version as well, deleted and upgraded to see if problem solved.

**What operating system and version?**
OSX 10.11.6

**What did you do?**
I rebooted the system with the app opened.

**What did you expect to happen?**
For the app to keep working.

**What actually happened?**
App not showing any kind of info, not even if I select Preferences or add a new or existing torrent, no info, no error, nothing.
Also doesn't seem to download anything.

**Comment by kusandore** [comment]
I have found a similar issue reported: WebTorrent Not Showing Torrents (Grey GUI) #781

**Comment by mathiasvr** [comment]
This might be related to #854, which should be fixed in #869.

**Comment by kusandore** [comment]
Yeah, I deleted the empty entries on my config.json, as the guy in #854, and the info came back, working fine right now.
The empty entries were torrents with no info downloaded, this torrents are the only missing thing.
