### ISSUE TITLE
Timeout After I pressed Play button

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#876]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0
**What operating system and version?**
Linux mint 18
**What did you do?**
Pressed to play button
**What did you expect to happen?**
Video should start playing
**What actually happened?**
Playback timeout .

The issue is when a torrent is paused/stopped and I click on pressed on play button It start loading the files . But the problem is I take some time to load and webtorrent pops up with "Timed out, try again" .
So please increasing the timeout after pressing the play button (when the torrent is paused).

**Note: I'm not very good in js otherwise I would love to correct it push it by myself .Please if someone can help me I would really like to help (by coding) in this project .**

**Comment by mathiasvr** [comment]
Related to #816

**Comment by dcposch** [comment]
@mathiasvr I think this is different.

* #816 is about failing fast (no timeout) when there's an error
* This issue is about failing slower (longer timeout) when there's no error, but a torrent takes a while to find peers & start downloading

**Comment by mathiasvr** [comment]
@dcposch I see, I don't think the timeout should be longer since it blocks playing other torrents. Maybe a solution would be to go directly to the player view and show a loading screen. Then the user could wait as long as desired for the torrent to load, or go back to the torrent list if it takes too long.

**Comment by dcposch** [comment]
@mathiasvr I agree

**Comment by Shankymahajan** [comment]
@mathiasvr yes indeed ! The solution can be anything we just don't want it to be crashed by the user .It should show something as a loading screen (downloading speed/uploading speed on the speed before torrent starts playing) so that user can actually see the progress. @dcposch

**Comment by mathiasvr** [comment]
@dcposch fixed this in 0dd16832983ac05bc355befa0d094f8fcd07dd58.
