### ISSUE TITLE
Missing buttons style in alert

### ISSUE THREAD

**Issue by mehdi-alouane** [feross/webtorrent-desktop#879]
Version: Version 0.13.1 (0.96.4)

OS: ubuntu 14.04Lts

update to last version of webtorrent desktop 
then when i trey to remove torrent from list i notice that button style missing
![screenshot from 2016-09-02 16 21 41](https://cloud.githubusercontent.com/assets/4208162/18208916/63338066-7129-11e6-8be4-815baab9ae6a.png)

**Comment by bertofer** [comment]
Hi, this is being solved at https://github.com/feross/webtorrent-desktop/pull/874
