### ISSUE TITLE
Torrents always time out when stopping before play

### ISSUE THREAD

**Issue by mathiasvr** [feross/webtorrent-desktop#883]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.13.1
**What operating system and version?**
OS X El Capitan (10.11.5)
**What did you do?**
Press play on a stopped torrent, and stop it before it plays.
**What did you expect to happen?**
The torrent should stop (and preferably the timeout should be cleared)
**What actually happened?**
The play loader is spinning and you can't start other torrents.
After getting the time out error, torrents can be started again but always times out.
Had to restart the app to be able to play torrents again.

**Comment by mathiasvr** [comment]
This cannot happen anymore, fixed in 0dd16832983ac05bc355befa0d094f8fcd07dd58.

**Comment by feross** [comment]
It's so great that this is fixed now. This was was one of the most frustrating parts of the UX, in my humble opinion.
