### ISSUE TITLE
Delete the webtorrent-desktop npm package

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#884]
It looks like we actually have people using `npm install webtorrent-desktop`.

Version 0.13.0 was never served from webtorrent.io - we went directly from 0.12.0 to 0.13.1. The the auto updaters also skipped that version. Despite that, we got telemetry reports from quite a few users using version 0.13.0.

That means they must have either downloaded the version directly from the Github Releases page, or used `npm install`. I bet it's the latter.

* Does the auto updater actually work correctly after `npm install`? The initial install is not done thru Squirrel, so probably not...
* Either way, we already have tons of different ways to install WebTorrent. Windows exe, Windows zip, Mac dmg, Mac zip, Linux deb (64- and 32-bit), Linux zip (64- and 32-bit). I don't think we want to support even more ways than that. Complexity makes it harder to be robust.

**Comment by dcposch** [comment]
If the auto updater *doesn't* work for our npm users, then that helps explain why ~15% of our users are still on versions older than 0.12:

<img width="870" alt="screen shot 2016-09-03 at 2 19 05 pm" src="https://cloud.githubusercontent.com/assets/169280/18227673/77a3fffe-71e1-11e6-9c33-ef73374c6f65.png">

That 15% also includes:
* People who ran the app today for the first time in weeks
* People who used the Portable ZIP install option

**Comment by mathiasvr** [comment]
I agree, I don't think GUI applications fits well with `npm install`.
On Mac I think something like [Cask](https://caskroom.github.io/) would be the better option.

**Comment by dcposch** [comment]
@mathiasvr I don't want to support cask either. For Mac, we have a single supported way to install the app: using the DMG.

**Comment by mathiasvr** [comment]
@dcposch I was just mentioning it as an alternative to npm if people really wanted to install through the terminal. Regarding supporting it developers rarely have a choice, and I just checked - it's already [there](https://github.com/caskroom/homebrew-cask/blob/master/Casks/webtorrent.rb).

**Comment by demoneaux** [comment]
For now maybe you could just deprecate it first to give users time to adjust, before fully deleting it.

**Comment by dcposch** [comment]
@demoneaux sounds good

**Comment by feross** [comment]
@dcposch I don't have a strong opinion about this, so I'll defer to you.

But I don't think `webtorrent-desktop` is the main reason that people are still on pre-0.12 versions. Check out the latest stats:

<img width="600" alt="screen shot 2016-09-17 at 3 44 29 pm" src="https://cloud.githubusercontent.com/assets/121766/18611423/b10d1d90-7ced-11e6-8620-e5fcac5be217.png">

That's 8% of users on pre-0.12 versions. That lines up nicely with our Linux user count, which is ~9.5% if we go by download count. (26,980 Linux downloads / 284,930 total downloads)

We also have 100+ followers on GitHub who get emails whenever there's a release, so maybe they did download directly from GitHub?

**Comment by dcposch** [comment]
> That's 8% of users on pre-0.12 versions. That lines up nicely with our Linux user count, which is ~9.5%

Well, we can see how much overlap there actually is. From yesterday's telemetry file:

```
$ cat logs/telemetry/2016-09-17.log | jq -c '{v:.version,o:.system.osPlatform}' | grep null | sort | uniq -c 
 127 {"v":null,"o":"darwin"}
  36 {"v":null,"o":"linux"}
 155 {"v":null,"o":"win32"}
```

So we have pre-0.12 users on all OSes

**Comment by dcposch** [comment]
> We also have 100+ followers on GitHub who get emails whenever there's a release, so maybe they did download directly from GitHub?

Good point. This explains why we had quite a few people install 0.13.0, even tho that was never linked to from the site or the auto updater. (We skipped directly to 0.13.1.)

Ideas:
* Delete the npm package
* Add a sentence or two to the top of `CHANGELOG.md` explaining that your app should auto update itself on Mac and Windows, no action required, and that you should install it from the website.
* Mark all new Github releases as pre-release (non production) until it's on the website.

**Comment by feross** [comment]
> Delete the npm package

Sure, the reason we added this in the first place was to let 32-bit linux users use the app. But we have a build for them now, so this isn't an issue anymore. Let's try deleting it and see how many people it impacts. PR incoming.

> Add a sentence or two to the top of CHANGELOG.md explaining that your app should auto update itself on Mac and Windows, no action required, and that you should install it from the website.

> Mark all new Github releases as pre-release (non production) until they're on the website.

If the user is on GitHub downloading a release, I think they're a power user and can figure things out for themselves. But I think a note about how we have an auto-updater is a good idea!

**Comment by feross** [comment]
The deed is done 💀 

https://www.npmjs.com/package/webtorrent-desktop

Here's the new readme:

---

### DEPRECATED: Install WebTorrent Desktop from the official site: https://webtorrent.io/desktop

This package is deprecated. Install WebTorrent Desktop from the official site: [https://webtorrent.io/desktop](https://webtorrent.io/desktop).

### Why?

The reason we added created this package in the first place was to let 32-bit
Linux users run the app. But we have an official 32-bit Linux build now, so this
isn't an issue anymore.

Supporting multiple ways of consuming the app creates more potential ways the app
can fail and we're trying very hard to make it super reliable.

As a bonus, on Mac and Windows, the official release comes with a sweet
auto-updater.
