### ISSUE TITLE
Disable sound option

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#887]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12
**What operating system and version?**
ALL
**What did you do?**
stop / play /pause /resume
**What did you expect to happen?**
-
**What actually happened?**
-

**I actually don't like the sound of the start / stop / pause /resume / remove button . It is annoying for me .We should give this as an option to the user to disable the sound .**

**Comment by mathiasvr** [comment]
#858
