### ISSUE TITLE
Mobile ??

### ISSUE THREAD

**Issue by joeblew99** [feross/webtorrent-desktop#897]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

There maybe an easy way to get this working on android and ios by using crosswalk. Crosswalk is designed for this and includes chromium in the built package, thereby eliminating the differences in mobile support.

I am curious if the maintainer of this report is interested in this feature. 

I don't think it would be a big effort because if it is already designed for electron it's not much more work to make it work on crosswalk.

**Comment by mathiasvr** [comment]
Previous discussion #679.

**Comment by dcposch** [comment]
@joeblew99 we've thought about making WebTorrent Mobile. At a very minimum, the UI would need to be reworked to feel right on mobile. (You can't just pop up a modal, there's no Open File dialog, etc.) I think the cleanest way would be to use the same backend, and write a new frontend using React Native.

In any case, it's not something we have any concrete plans to do.

Right now our priority is making the desktop app solid and getting to version 1.0. See #652

**Comment by joeblew99** [comment]
@dcposch 
i use polymer and there are few changes between desktop and mobile, if any. It basically handles allot of the layout aspects for you.
