### ISSUE TITLE
What happen of new version? 0.13.1 ( 0.96.4 )

### ISSUE THREAD

**Issue by bluelovers** [feross/webtorrent-desktop#899]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu

0.13.1 ( 0.96.4 )

**What operating system and version?**

windows 10

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

i lost ui style or new ui change ?

and webtorrent fail of default torrent app
and  magnet uri also fail for browser

can't drop torrent file into webtorrent

![06_x_06_02-36-33](https://cloud.githubusercontent.com/assets/167966/18255349/7b86a3dc-73db-11e6-84f1-eddc32308969.png)
![06_x_06_02-34-09](https://cloud.githubusercontent.com/assets/167966/18255350/7b882608-73db-11e6-8ee7-6135c2f6fa0a.png)

**Comment by dcposch** [comment]
**@bluelovers How did you install the app?**

The screenshot you posted shows that an old version of the app (0.10.0) was set as the default torrent handler:

```
C:\Users\user\AppData\Local\WebTorrent\app-0.10.0\WebTorrent.exe
```

The default torrent handler **should** be set to something like `C:\Program Files\...\WebTorrent.exe`, which should always be the latest version.

**Comment by bluelovers** [comment]
i install it for a long time , and webtorrent always auto update

but after this time update
it not work well

i didn't change anything 

and not way can re-set default again

**Comment by dcposch** [comment]
> can't drop torrent file into webtorrent

@bluelovers did you drag and drop the torrent file onto the app window, or onto the app desktop icon?

**Comment by dcposch** [comment]
@bluelovers **I recommend installing the latest version, 0.14, here: ** https://webtorrent.io/desktop

**Comment by bluelovers** [comment]
@dcposch

i can't  drop into opened webtorrent window at last version
(it work now

----------

* default torrent app
* magnet uri

i try reinstall, still not fixed

**Comment by bluelovers** [comment]
i edit for fix this bug
but webtoeent should have option for force fix

`HKEY_CLASSES_ROOT\io.webtorrent.torrent`
