### ISSUE TITLE
Communication with web site

### ISSUE THREAD

**Issue by iWedmak** [feross/webtorrent-desktop#900]
is there a way or can it be done in future?
for example:
specifically load torrent or magnet though webtorrent?
get back from webtorrent local link to video file on user machine, so it can be playd through video player on site ?
so basically it be nice to have a way to communicate with webtorrent from site, so it can be used as service on user machine

**Comment by dcposch** [comment]
You can already paste magnet links from anywhere into WebTorrent Desktop

You can also set WebTorrent Desktop as your default magnet link and torrent file handler, after which you can just click on a magnet link and it should open in the app

**Comment by iWedmak** [comment]
I know about this, and this is not my question/suggestion.
I don't want webtorrent to be default torrent client, its not for that, at this point.

I need so a way of communicate with webtorrent from outside. Pragmatically
