### ISSUE TITLE
Torrents start downloading again after restarting the program.

### ISSUE THREAD

**Issue by kopy-kate** [feross/webtorrent-desktop#902]
**What version of WebTorrent Desktop? (See the 'About WebTorrent' menu)**
Version 0.14.0 (0.96.4)
**What operating system and version?**
Windows 10
**What did you do?**
Restarted the WebTorrent.desktop application.
**What did you expect to happen?**
Expected the torrents to load as normal and continue to seed.
**What actually happened?**
All of the torrents on the list started to download again. Some of the larger torrents also froze midway, which meant that I had to delete them and add them again.

So I restarted WebTorrent.Desktop again. This time some of the torrents did load properly without re-downloading .. however, the larger ones (150mb+) still want to be downloaded from scratch, and still freeze mid-way.

**Comment by dcposch** [comment]
Let's track this here: #901
