### ISSUE TITLE
Automatically delete old torrents

### ISSUE THREAD

**Issue by bluelovers** [feross/webtorrent-desktop#908]
should have a option clear cache
ex: can set a day, and delete N day's old file

AppData\Local\WebTorrent\Posters
AppData\Local\WebTorrent\Torrents

**Comment by dcposch** [comment]
Deleting a torrent from the app should delete the corresponding files in `.../Posters` and `.../Torrents`.

I think what you're asking for is an option to automatically delete media torrents that were last streamed more than `n` days ago. (Or, similarly, only keep the latest `m` media torrents regardless of age.)

**Comment by feross** [comment]
Not a fan of this feature request. There's an X button and it's easy to use. Especially once we solve https://github.com/feross/webtorrent-desktop/issues/970, the user can just go click, click, click and delete all their torrents just like you close Chrome tabs.
