### ISSUE TITLE
Cast Option Icon isn't avaiable

### ISSUE THREAD

**Issue by krisgopal128** [feross/webtorrent-desktop#916]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.14 (0.96.4)
**What operating system and version?**
Windows 10 (Build 10.0.14915)
**What did you do?**
Downloaded Media Contained Torrent & played it 
**What did you expect to happen?**
Cast Icon option should be available
**What actually happened?**
Option isn't available
 
![screen-shot](https://cloud.githubusercontent.com/assets/13931326/18409935/e15eb28e-7765-11e6-8e0f-289c772a0ab2.png)

**Comment by demoneaux** [comment]
The cast icon will only be displayed when cast devices (DLNA, Chromecast, ...) are detected, otherwise it will not be shown.

**Comment by feross** [comment]
What @demoneaux said.

@krisgopal128 If you actually have cast devices on your network and WebTorrent Desktop failed to recognize them, then please let us know any additional details you can provide about your network and circumstances.
