### ISSUE TITLE
[Feature] Check For Updates 

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#918]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12
**What operating system and version?**
All
**What did you do?**
I was checking the updates of webtorrent
**What did you expect to happen?**
I was searching for 'check for update tab ' in about .
**What actually happened?**
Tab was missing 

We should add 'check for update' tab in about section .

**Comment by mathiasvr** [comment]
See #895.
