### ISSUE TITLE
macOS Sierra : Enable PiP functionality

### ISSUE THREAD

**Issue by pi-mont** [feross/webtorrent-desktop#920]
Love this software, only thing I see that would make it perfect on macOS Sierra is Picture in Picture functionality.
Any plans on enabling this?

**Comment by dcposch** [comment]
you can already pretty much to this via View > Float on Top

in addition, the player controls are hidden while video is playing. looks like this:

<img width="1067" alt="screen shot 2016-09-12 at 5 51 47 pm" src="https://cloud.githubusercontent.com/assets/169280/18457934/a27443b0-7911-11e6-80b0-e5256c3496da.png">

**Comment by dcposch** [comment]
LMK if Float On Top works for you

**Comment by pi-mont** [comment]
Thanks for the response, although that works in webtorrent and vlc the great part about PiP is that it allows you to keep the display snapped to any corner on any desktop wether an app is fullscreen or not. It's been really handy for watching tutorials and podcasts while working.

Here's some more info regarding it:
http://www.macworld.com/article/3088328/macs/how-to-use-picture-in-picture-in-macos-sierra.html

**Comment by mathiasvr** [comment]
@pi-mont I don't think that would be easy to do right now. If chromium adds support for it we can take a look at it then.

**Comment by feross** [comment]
Yep, I anticipate Electron will want to add this as a feature. Once they do, I'm game.
