### ISSUE TITLE
Progress bar color should change to green after completion

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#921]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.14
**What operating system and version?**
LinuxX64
**What did you do?**
start downloading 
**What did you expect to happen?**
the progress bar should turn into the green after completion
**What actually happened?**
nothing

I don't think it's looking great(can differ from person to person )  because you made it very small progress bar. Rather than this ,we can try to  follow material design . We can try using the bottom of every image view of the torrent files by overlapping the imageview  with a very small (width ).

ThankYou!

**Comment by dcposch** [comment]
dunno man, it says the percentage right next to it, so it'll say

□ □ □ □ □  100%

□ □ □ □      80%

□                15%

□ □ □ □ □  100%

I don't think it's hard to tell which torrents are done and which are still downloading.

**Comment by dcposch** [comment]
One small UX improvement we could do: make sure that the progress stays at 99% (never rounds up to 100) until every single piece is downloaded and verified. That way, "100%" really means "done". We can do that by truncating instead of rounding when computing download %.

**Comment by dcposch** [comment]
If anyone else wants green progress bars, LMK. If there's enough interest, we can reopen the issue. 

Here's another alternative: how about we leave the percentage indicator as is, but once the torrent is fully downloaded, we change it from "100%" to "Seeding" or "Not Seeding", depending on whether the torrent is enabled.

That way it's easy to tell apart a torrent that is almost done ("99%" or "100%") with one which is completely done ("Seeding", "Not Seeding").

@feross  ?

**Comment by Shankymahajan** [comment]
That is absolutely amazing idea @dcposch  .I'm also suggesting to use more space for showing the progress bar .
