### ISSUE TITLE
Shutdown computer after download is finished 

### ISSUE THREAD

**Issue by Deenoking** [feross/webtorrent-desktop#929]
Hey everyone, I was thinking this would be a great feature for those trying to torrent big overtime and not want leave their computer on. 

Any thoughts?

**Comment by feross** [comment]
Thanks for the feature request!

Unlike other torrent apps, WebTorrent Desktop values simplicity and beautiful design. We try to implement only the most important features that a torrent app needs, and to make those features the best of any torrent app. This focus on only the most important features prevents the app from getting overload with features and options that only benefit a small percentage of users.

That's not to say we won't ever add new or complex features. We support powerful features like one-click streaming, dynamic piece prioritization, web peers (WebRTC), etc. but only when they have a clear benefit to at least 80% of our users. See the [80-20 rule](https://en.wikipedia.org/wiki/Pareto_principle).

For that reason, I don't think it makes sense to implement this feature. I hope that makes sense!

P.S. In the future, we might support [extensions](#664) and someone could implement this feature as an extension.
