### ISSUE TITLE
Skip / Priority to download files

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#930]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.14
**What operating system and version?**
ALL

As qbittorrent or any other famous torrent clients, every one has a feature of giving priorities to the torrent files or not to download some extra files in a torrent . We should add this as a feature in webtorrent .

**Comment by feross** [comment]
We support deselecting certain files from getting downloaded. It might be a bit hidden in the current design. Click a torrent to open the list of files, then click the little X icon on the right side to deselect the file.

I think that adding individual file priorities is really overkill. The idea of WebTorrent is to be a simpler torrent client. That's a feature that will only help maybe the top 5% of users, and it will add more code and complexity to the codebase.  Sorry, I'm -1 on that feature.

**Comment by Shankymahajan** [comment]
No problem :+1:
