### ISSUE TITLE
"Delete Data" is broken on Windows

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#935]
**What version of WebTorrent Desktop?** master

**What operating system and version?** Windows 10

**What did you do?** Go to any **multi-file** torrent. Right-click, then click Delete Data.

**What did you expect to happen?** It should delete the torrent from the list and also delete the whole folder for that torrent from the Downloads folder.

**What actually happened?** It deletes the torrent from the list, but only deletes the **first file**, leaving the rest of the folder intact.

This is the first bug found by the integration tests. @feross

**Comment by feross** [comment]
NICE 👍 👍 👍
