### ISSUE TITLE
Cast module is no longer being lazy loaded

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#939]
It used to be loaded lazily, but now playback-controller.js requires it immediately. We should fix this to improve startup time which has slowed down to a sad 1500ms. It used to be under 1000ms.

**Comment by mathiasvr** [comment]
I don't think it's the Cast module that slows the startup down. Requiring it is fast, calling `.init` is slower but that is still being done lazily.

**Comment by feross** [comment]
Lazy-requiring the cast module used to cause a noticeable speed improvement.

**Comment by feross** [comment]
After this PR (https://github.com/feross/webtorrent-desktop/pull/995), I ensured that all require() statements are lazy, so this can be closed.
