### ISSUE TITLE
Support for HTTPS tracker

### ISSUE THREAD

**Issue by henrypijames** [feross/webtorrent-desktop#942]
uTorrent supports tracker over HTTPS, using the same protocol as HTTP. (Its handles SSL certificates pretty loosely, either not checking it at all or at least allowing self-signed certificates to be used by the tracker.) I would be nice if WebTorrent could do this, too.

This is particularly useful where ISP filters and blocks BT tracker connections. In my case, my ISP blocks well-known public tracker, both HTTP and UDP, so I wrote an HTTPS-to-UDP-and-back-to-HTTPS proxy called [`trackergate`](/henrypijames/trackergate) to circumvent it. It is designed to be HTTPS only, so the ISP wouldn't learn, through simple packet inspection, that the proxy is a BT tracker. (It still could as long as I don't implement SSL cert check, but if and when that happens, I'd escalate by updating `trackergate` with the option to accept writelisted client certificates only.)

**Comment by feross** [comment]
WebTorrent Desktop should support HTTPS trackers, as the underlying [`bittorrent-tracker`](https://github.com/feross/bittorrent-tracker) package has support.

Are you sure that HTTPS trackers are not working in the app?

**Comment by henrypijames** [comment]
The same torrent, using HTTPS trackers, downloads in uTorrent, but not in WTD, no the same computer.

It would be nice if there's an option to produce some debug logs.

**Comment by feross** [comment]
@henrypijames Can you email me the torrent file that is having the issue? GitHub doesn't allow uploading files here. My email is on my GitHub profile page.

**Comment by feross** [comment]
I'm closing this issue because it's been a while without a response from the issue opener. It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
