### ISSUE TITLE
Update auto-launch to 5.0.0

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#947]
`auto-launch` 5.0.0 was just released: https://github.com/Teamwork/node-auto-launch/releases/tag/5.0.0

Let's remove the macOS workaround added in https://github.com/feross/webtorrent-desktop/pull/923 if we can.

@dcposch @noamokman

**Comment by noamokman** [comment]
PR is ready 👍

**Comment by feross** [comment]
Closing re @dcposch's comment here: https://github.com/feross/webtorrent-desktop/pull/968#issuecomment-249455373
