### ISSUE TITLE
App saves the wrong window bounds when quitting while in the player

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#961]
### Steps to reproduce
- Start playing a video. The window resizes to fit.
- Quit the app (Cmd+Q)
- Restart the app

### Expected result
The torrent list (home page) should open at the size it was before, as if you had hit Esc to quit out of the video.

### Actual result
The window opens at the same huge size as the video.

We can fix this by only saving window bounds on resize when *not* in the player.

CC @Flet https://github.com/feross/webtorrent-desktop/pull/827

**Comment by Flet** [comment]
aww :( I didn't think of this case.
