### ISSUE TITLE
Add recheck torrent feature

### ISSUE THREAD

**Issue by farribeiro** [feross/webtorrent-desktop#969]
Feature to recheck a torrent and consequence ability to recognize previously downloaded content.

**Comment by feross** [comment]
The app will recognize and verify files that exist in your Downloads folder. But only if they have the same file or folder name as the torrent. This is how WebTorrent names the files/folders already, so if you've already downloaded a torrent and still have the files on disk, you can re-add it to the app by just re-adding the .torrent file. 

If you're asking for an explicit option to re-check a torrent, that seems like it won't be used by 98%+ of our users, so we probably won't add it. The ability to move the download location of a torrent (which can help recognize a previously downloaded torrent) is being discussed in this issue: https://github.com/feross/webtorrent-desktop/issues/917
