### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by al3x4nder** [feross/webtorrent-desktop#975]
Version 0.16.0 (0.97.1) (64-bit)
Windows 10 Pro x64

Hello there. WebTorrent isn't translated to Russian language. Are you planning to add it? Maybe I can help you?

(plz, write to airx13@mail.ru)

**Comment by mathiasvr** [comment]
WebTorrent Desktop doesn't support translations yet but you can follow this feature request #371.
It is currently a `v2.0` milestone so it might be a while before translation help is needed, but some work has already been done in this PR #820.

Closing this issue for now.

**Comment by feross** [comment]
Btw, I would love to get this into WebTorrent Desktop sooner than version 2.0.

@al3x4nder, if you're interested in helping, definitely connect with @yciabaud and see what's left to get that PR merged.
