### ISSUE TITLE
Rebase merging only

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#980]
Let's try using "rebase only merging", which @dcposch is a huge fan of. I just removed the other options from the green merge button for this GitHub repo. Feedback welcome in this issue.

**Comment by Flet** [comment]
Educational Materials
https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by feross** [comment]
This seems to be working okay. I'll close this issue now.

I like the clean history, but unfortunately, 'Rebase and Merge' has the same issue as 'Squash and Merge' where it changes the commit hash. I have to force delete local branches, because git can't tell that the branch was merged. Am I doing it wrong?
