### ISSUE TITLE
WebTorrent Desktop doesn't run on Debian 8

### ISSUE THREAD

**Issue by k0nsl** [feross/webtorrent-desktop#990]
**What version of WebTorrent Desktop?**
Latest

**What operating system and version?**
Debian 8

**What did you do?**
I ran `/usr/bin/webtorrent-desktop` as an unprivileged user.

**What did you expect to happen?**
I expected WebTorrent Desktop to run like it would normally.

**What actually happened?**
When I ran `/usr/bin/webtorrent-desktop` it threw out this on the terminal:

```
k0nsl@debipv6:~$ /usr/bin/webtorrent-desktop
Production: true portable: false test: false
```

Webtorrent Desktop version `0.16.0-1` worked perfectly for a unprivileged user (non-root). But I cannot get the newest version (`0.17.0`) to work for non-root. I am not sure what has happened as I didn't do any major changes to my system and/or configuration.

**Comment by k0nsl** [comment]
Hrm, seems like it was somehow solved by another reboot. Remarkable!

**Comment by feross** [comment]
@k0nsl That's strange. Let us know if you see any weird behavior like this again, especially after an update.

Btw, the console output you saw is expected.
