### ISSUE TITLE
[Feature Request] Add a way to disable sound effects

### ISSUE THREAD

**Issue by cra0zy** [feross/webtorrent-desktop#998]
I am talking about the *ding* sound effect that plays when you drag a torrent or when you play a torrent. It's especially annoying when you have headphones since the strength that is used to play that *ding* sound is higher than an average video volume.

**Comment by feross** [comment]
This PR was just merged (https://github.com/feross/webtorrent-desktop/pull/992/files) and will be released in the next 24 hours. It reduces the volume of the sounds. They definitely shouldn't be louder than the average video volume. Can you let us know what you think of the UX sounds after the next version is released?

**Comment by cra0zy** [comment]
This is a request to allow disabling them, not lowering the volume of them.

**Comment by jarmitage** [comment]
Please let us turn off these sounds!
