### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by carlosarce233** [feross/webtorrent-desktop#999]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu) 
version 0.17, 64 bit
**What operating system and version?**
windows 10 64 bit, 2gb ram
**What did you do?**

**What did you expect to happen?**

**What actually happened?**
webtorrent is using all memory available. seems to happen when playing torrent.

**Comment by feross** [comment]
@carlosarce233 Can you press `Control` + `Alt` + `Delete` and open Task Manager and check the exact amount of memory that WebTorrent is using? Is it really using the full 2GB by itself? Or is it using less, like 1GB, and the other 1GB is used by other apps?

**Comment by carlosarce233** [comment]
its going past the 1GB, computer slows down to the point of freezing.

**Comment by feross** [comment]
@carlosarce233 A couple of questions:

- Did this just start happening on version 0.17? Or has this always been an issue?
- How many torrents are in the torrent list?
- How many torrents are active?
- What happens when you stop all the torrents from downloading? Does the app get faster?

**Comment by carlosarce233** [comment]
It started happening with 0.17. 
Just had one torrent downloading, when it started playing resource usage went up.
Indeed when i stop the torrent from playing the app gets more responsive.

**Comment by carlosarce233** [comment]
i have used version 0.17.1 and everything seems fine now. weird.

**Comment by feross** [comment]
Glad to hear it's working better for you.
